% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/hc-charts.R, R/shortcuts.R
\name{hcdensity}
\alias{hc_add_series_density}
\alias{hcdensity}
\title{Shorcut to create a density plot}
\usage{
hcdensity(x, area = FALSE, ...)

hc_add_series_density(hc, x, area = FALSE, ...)
}
\arguments{
\item{x}{A numeric vector}

\item{area}{A boolean value to show or not the area}

\item{...}{Aditional shared arguments for the data series
(\url{http://api.highcharts.com/highcharts#series}).}

\item{hc}{A \code{highchart} \code{htmlwidget} object.}
}
\description{
Shorcut to create a density plot
}
\examples{

highchart() \%>\%
  hc_add_series_density(rnorm(1000)) \%>\%
  hc_add_series_density(rexp(1000), area = TRUE)
 
}

