library(tidyverse)
library(rvest)

fout <- "dev/docs-and-examples/api-hc.R"

url <- "https://api.highcharts.com/highcharts"

apihmtl <- read_html(url)

opts <- apihmtl %>% 
  html_node("#options") %>% 
  html_nodes(".title")

opts_text <- html_text(opts) %>% 
  str_trim() %>% 
  str_remove_all(":") 

opts_url <- html_attr(opts, "href")

dfopts <- tibble(
 option = opts_text,
 url = file.path(url, opts_url)
)

rm(opts, opts_text, opts_url, apihmtl, url)

dfopts

opts_to_remove <- c("colors", "global", "lang", "noDate", "defs", "data",
                    "loading", "accessibility")

dfopts <- dfopts %>% 
  filter(!option %in% opts_to_remove)


# write doc & examples ----------------------------------------------------
file.remove(fout)

txt <- c(
  "# Generated by 'dev/docs-and-examples/00_generate_api-hc_from_hc_api_docs.R'",
  str_glue("# Generated in { dt }", dt = Sys.time()),
  "#",
  ""
)

write_lines(txt, fout)

dfopts %>% 
  sample_frac(1) %>%
  pmap(function(option, url){
    
    # url <- "https://api.highcharts.com/highcharts/drilldown"
    # option <- "drilldown"
    message(option, ": ", url)
    
    doc <- read_html(url) 
    
    roxy1 <- doc %>% 
      html_node("#option-list") %>% 
      html_node("div") %>% 
      html_text() %>% 
      str_trim() %>% 
      str_split("\n", simplify = TRUE) %>% 
      str_trim() %>% 
      c("") %>% 
      str_c("#' ", .)
    
    roxy1[1] <- str_c(roxy1[1], " options for highcharter objects")
    
    roxy1 
    
    roxy2 <- str_glue(
"#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in { url }. 
#' 
#' @examples",
url = url
    ) 
    
    roxy2
    
    roxy3 <- read_lines(str_glue("dev/docs-and-examples/{ opt }.R", opt = option)) %>% 
      str_c("", ., "") %>% 
      str_c("#' ", .)
    
    roxy3
    
    fun <- str_glue(
"#' 
#' @export
hc_{ opt }  <- function(hc, ...) {{
  
  .hc_opt(hc, \"{ opt }\", ...)
  
}}

",
opt = option)
    
    fun
    
    txt <- c(roxy1, roxy2, roxy3, fun) %>% 
      str_c(collapse = "\n") 
    
    
    write_lines(
      txt,
      fout,
      append = file.exists(fout)
      )
    
  })

