# Generated by 'dev/docs-and-examples/00_generate_api-hc_from_hc_api_docs.R'
# Generated in 2019-01-21 18:18:30
#

#' annotations options for highcharter objects
#' 
#' Options for configuring annotations, for example labels, arrows or
#' shapes. Annotations can be tied to points, axis coordinates or chart
#' pixel coordinates.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/annotations. 
#' 
#' @examples
#' df <- data.frame(
#'   x = 1:10,
#'   y = 1:10
#' )
#' 
#' highchart() %>% 
#'   hc_add_series(data = df, hcaes(x = x, y = y), type = "area") %>% 
#'   hc_annotations(
#'     list(
#'       labels = list(
#'         list(point = list(x = 5, y = 5, xAxis = 0, yAxis = 0), text = "Middle"),
#'         list(point = list(x = 1, y = 1, xAxis = 0, yAxis = 0), text = "Start")
#'       )
#'     )
#'   )
#' 
#' @export
hc_annotations  <- function(hc, ...) {
  
  .hc_opt(hc, "annotations", ...)
  
}

#' boost options for highcharter objects
#' 
#' Options for the Boost module. The Boost module allows certain series types
#' to be rendered by WebGL instead of the default SVG. This allows hundreds of
#' thousands of data points to be rendered in milliseconds. In addition to the
#' WebGL rendering it saves time by skipping processing and inspection of the
#' data wherever possible. This introduces some limitations to what features are
#' available in Boost mode. See the docs for
#' details.
#' In addition to the global boost option, each series has a
#' boostThreshold that defines when the
#' boost should kick in.
#' Requires the modules/boost.js module.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/boost. 
#' 
#' @examples
#' #  Ex 1
#' n <- 50000
#' 
#' x <- sin(4*2*pi*seq(n)/n) + rnorm(n)/10
#' 
#' x <- round(x, 3)
#' 
#' plot(x)
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "x") %>%
#'   hc_add_series(data = x) %>% 
#'   hc_title(text = "No boost") %>% 
#'   hc_boost(
#'     enabled = FALSE # Not recommended
#'   )
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "x") %>%
#'   hc_add_series(data = x) %>% 
#'   hc_title(text = "With boost") %>% 
#'   hc_boost(
#'     enabled = TRUE # Default :D
#'   )
#' 
#' # Ex 2
#' library(MASS)
#' 
#' n <- 100000
#' 
#' sigma <- matrix(c(10,3,3,2),2,2)
#' sigma
#' 
#' mvr <- round(mvrnorm(n, rep(c(0, 0)), sigma), 6)
#' 
#' vx <- ceiling(1+abs(max(mvr[, 1])))
#' vy <- ceiling(1+abs(max(mvr[, 2])))
#' 
#' ds <- list_parse2(as.data.frame(mvr))
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "xy") %>%
#'   hc_xAxis(min = -vx, max = vx) %>% 
#'   hc_yAxis(min = -vy, max = vy) %>% 
#'   hc_add_series(
#'     data = ds,
#'     type = "scatter",
#'     name = "A lot of points!",
#'     color = 'rgba(0,0,0,0.01)',
#'     marker = list(radius = 2),
#'     tooltip = list(
#'       followPointer = FALSE,
#'       pointFormat =  '[{point.x:.1f}, {point.y:.1f}]'
#'       )
#'     )
#' 
#' @export
hc_boost  <- function(hc, ...) {
  
  .hc_opt(hc, "boost", ...)
  
}

#' chart options for highcharter objects
#' 
#' General options for the chart.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/chart. 
#' 
#' @examples
#' hc <- highchart() %>% 
#'   hc_xAxis(categories = month.abb) %>% 
#'   hc_add_series(name = "Tokyo", data = sample(1:12)) %>% 
#'   hc_add_series(name = "London", data = sample(1:12) + 10)
#' 
#' hc
#' 
#' hc %>% 
#'   hc_chart(
#'     type = "column",
#'     options3d = list(enabled = TRUE, beta = 15, alpha = 15)
#'     )
#' 
#' 
#' hc %>% 
#'   hc_chart(
#'     borderColor = "#EBBA95",
#'     borderRadius = 10,
#'     borderWidth = 2,
#'     backgroundColor = list(
#'       linearGradient = c(0, 0, 500, 500),
#'       stops = list(
#'         list(0, 'rgb(255, 255, 255)'),
#'         list(1, 'rgb(200, 200, 255)')
#'              )
#'       )
#'     )
#' 
#' 
#' @export
hc_chart  <- function(hc, ...) {
  
  .hc_opt(hc, "chart", ...)
  
}

#' annotations options for highcharter objects
#' 
#' Options for configuring annotations, for example labels, arrows or
#' shapes. Annotations can be tied to points, axis coordinates or chart
#' pixel coordinates.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/annotations. 
#' 
#' @examples
#' df <- data.frame(
#'   x = 1:10,
#'   y = 1:10
#' )
#' 
#' highchart() %>% 
#'   hc_add_series(data = df, hcaes(x = x, y = y), type = "area") %>% 
#'   hc_annotations(
#'     list(
#'       labels = list(
#'         list(point = list(x = 5, y = 5, xAxis = 0, yAxis = 0), text = "Middle"),
#'         list(point = list(x = 1, y = 1, xAxis = 0, yAxis = 0), text = "Start")
#'       )
#'     )
#'   )
#' 
#' @export
hc_annotations  <- function(hc, ...) {
  
  .hc_opt(hc, "annotations", ...)
  
}

#' boost options for highcharter objects
#' 
#' Options for the Boost module. The Boost module allows certain series types
#' to be rendered by WebGL instead of the default SVG. This allows hundreds of
#' thousands of data points to be rendered in milliseconds. In addition to the
#' WebGL rendering it saves time by skipping processing and inspection of the
#' data wherever possible. This introduces some limitations to what features are
#' available in Boost mode. See the docs for
#' details.
#' In addition to the global boost option, each series has a
#' boostThreshold that defines when the
#' boost should kick in.
#' Requires the modules/boost.js module.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/boost. 
#' 
#' @examples
#' #  Ex 1
#' n <- 50000
#' 
#' x <- sin(4*2*pi*seq(n)/n) + rnorm(n)/10
#' 
#' x <- round(x, 3)
#' 
#' plot(x)
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "x") %>%
#'   hc_add_series(data = x) %>% 
#'   hc_title(text = "No boost") %>% 
#'   hc_boost(
#'     enabled = FALSE # Not recommended
#'   )
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "x") %>%
#'   hc_add_series(data = x) %>% 
#'   hc_title(text = "With boost") %>% 
#'   hc_boost(
#'     enabled = TRUE # Default :D
#'   )
#' 
#' # Ex 2
#' library(MASS)
#' 
#' n <- 100000
#' 
#' sigma <- matrix(c(10,3,3,2),2,2)
#' sigma
#' 
#' mvr <- round(mvrnorm(n, rep(c(0, 0)), sigma), 6)
#' 
#' vx <- ceiling(1+abs(max(mvr[, 1])))
#' vy <- ceiling(1+abs(max(mvr[, 2])))
#' 
#' ds <- list_parse2(as.data.frame(mvr))
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "xy") %>%
#'   hc_xAxis(min = -vx, max = vx) %>% 
#'   hc_yAxis(min = -vy, max = vy) %>% 
#'   hc_add_series(
#'     data = ds,
#'     type = "scatter",
#'     name = "A lot of points!",
#'     color = 'rgba(0,0,0,0.01)',
#'     marker = list(radius = 2),
#'     tooltip = list(
#'       followPointer = FALSE,
#'       pointFormat =  '[{point.x:.1f}, {point.y:.1f}]'
#'       )
#'     )
#' 
#' @export
hc_boost  <- function(hc, ...) {
  
  .hc_opt(hc, "boost", ...)
  
}

#' chart options for highcharter objects
#' 
#' General options for the chart.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/chart. 
#' 
#' @examples
#' hc <- highchart() %>% 
#'   hc_xAxis(categories = month.abb) %>% 
#'   hc_add_series(name = "Tokyo", data = sample(1:12)) %>% 
#'   hc_add_series(name = "London", data = sample(1:12) + 10)
#' 
#' hc
#' 
#' hc %>% 
#'   hc_chart(
#'     type = "column",
#'     options3d = list(enabled = TRUE, beta = 15, alpha = 15)
#'     )
#' 
#' 
#' hc %>% 
#'   hc_chart(
#'     borderColor = "#EBBA95",
#'     borderRadius = 10,
#'     borderWidth = 2,
#'     backgroundColor = list(
#'       linearGradient = c(0, 0, 500, 500),
#'       stops = list(
#'         list(0, 'rgb(255, 255, 255)'),
#'         list(1, 'rgb(200, 200, 255)')
#'              )
#'       )
#'     )
#' 
#' 
#' @export
hc_chart  <- function(hc, ...) {
  
  .hc_opt(hc, "chart", ...)
  
}

#' colorAxis options for highcharter objects
#' 
#' A color axis for choropleth maps and heat maps. Visually, the color
#' axis will appear as a gradient or as separate items inside the
#' legend, depending on whether the axis is scalar or based on data
#' classes.
#' For supported color formats, see the
#' docs article about colors.
#' A scalar color axis is represented by a gradient. The colors either
#' range between the minColor and the
#' maxColor, or for more fine grained control the
#' colors can be defined in stops. Often times, the
#' color axis needs to be adjusted to get the right color spread for the
#' data. In addition to stops, consider using a logarithmic
#' axis type, or setting min and
#' max to avoid the colors being determined by
#' outliers.
#' When dataClasses are used, the ranges are
#' subdivided into separate classes like categories based on their
#' values. This can be used for ranges between two values, but also for
#' a true category. However, when your data is categorized, it may be as
#' convenient to add each category to a separate series.
#' See the Axis object for
#' programmatic access to the axis.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/colorAxis. 
#' 
#' @examples
#' hc <- hchart(volcano)
#' 
#' hc
#' 
#' hc %>% 
#'   hc_colorAxis(
#'     minColor = "#FFFFFF",
#'     maxColor = "#434348"
#'     )
#' 
#' hc %>% 
#'   hc_colorAxis(
#'     minColor = "#FFFFFF",
#'     maxColor = "#434348",
#'     type = "logarithmic"
#'     )
#' 
#' 
#' require("viridisLite")
#' 
#' n <- 5
#' 
#' stops <- data.frame(
#'   q = 0:n/n,
#'   c = substring(viridis(n + 1), 0, 7),
#'   stringsAsFactors = FALSE
#'   )
#' 
#' stops <- list_parse2(stops)
#' 
#' hc %>% 
#'   hc_colorAxis(stops = stops, max = 200)
#' 
#' @export
hc_colorAxis  <- function(hc, ...) {
  
  .hc_opt(hc, "colorAxis", ...)
  
}

#' boost options for highcharter objects
#' 
#' Options for the Boost module. The Boost module allows certain series types
#' to be rendered by WebGL instead of the default SVG. This allows hundreds of
#' thousands of data points to be rendered in milliseconds. In addition to the
#' WebGL rendering it saves time by skipping processing and inspection of the
#' data wherever possible. This introduces some limitations to what features are
#' available in Boost mode. See the docs for
#' details.
#' In addition to the global boost option, each series has a
#' boostThreshold that defines when the
#' boost should kick in.
#' Requires the modules/boost.js module.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/boost. 
#' 
#' @examples
#' #  Ex 1
#' n <- 50000
#' 
#' x <- sin(4*2*pi*seq(n)/n) + rnorm(n)/10
#' 
#' x <- round(x, 3)
#' 
#' plot(x)
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "x") %>%
#'   hc_add_series(data = x) %>% 
#'   hc_title(text = "No boost") %>% 
#'   hc_boost(
#'     enabled = FALSE # Not recommended
#'   )
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "x") %>%
#'   hc_add_series(data = x) %>% 
#'   hc_title(text = "With boost") %>% 
#'   hc_boost(
#'     enabled = TRUE # Default :D
#'   )
#' 
#' # Ex 2
#' library(MASS)
#' 
#' n <- 100000
#' 
#' sigma <- matrix(c(10,3,3,2),2,2)
#' sigma
#' 
#' mvr <- round(mvrnorm(n, rep(c(0, 0)), sigma), 6)
#' 
#' vx <- ceiling(1+abs(max(mvr[, 1])))
#' vy <- ceiling(1+abs(max(mvr[, 2])))
#' 
#' ds <- list_parse2(as.data.frame(mvr))
#' 
#' highchart() %>%
#'   hc_chart(zoomType = "xy") %>%
#'   hc_xAxis(min = -vx, max = vx) %>% 
#'   hc_yAxis(min = -vy, max = vy) %>% 
#'   hc_add_series(
#'     data = ds,
#'     type = "scatter",
#'     name = "A lot of points!",
#'     color = 'rgba(0,0,0,0.01)',
#'     marker = list(radius = 2),
#'     tooltip = list(
#'       followPointer = FALSE,
#'       pointFormat =  '[{point.x:.1f}, {point.y:.1f}]'
#'       )
#'     )
#' 
#' @export
hc_boost  <- function(hc, ...) {
  
  .hc_opt(hc, "boost", ...)
  
}

#' legend options for highcharter objects
#' 
#' The legend is a box containing a symbol and name for each series
#' item or point item in the chart. Each series (or points in case
#' of pie charts) is represented by a symbol and its name in the legend.
#' It is possible to override the symbol creator function and create
#' custom legend symbols.
#' 
#' A Highmaps legend by default contains one legend item per series, but if
#' a colorAxis is defined, the axis will be displayed in the legend.
#' Either as a gradient, or as multiple legend items for dataClasses.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/legend. 
#' 
#' @examples
#' highchart() %>% 
#'   hc_xAxis(categories = month.abb) %>% 
#'   hc_add_series(name = "Tokyo", data = sample(1:12)) %>% 
#'   hc_add_series(name = "London", data = sample(1:12) + 10) %>%
#'   hc_add_series(name = "Other City", data = sample(1:12) + 20) %>%
#'   hc_legend(
#'     align = "left",
#'     verticalAlign = "top",
#'     layout = "vertical",
#'     x = 0,
#'     y = 100
#'     ) 
#' 
#' @export
hc_legend  <- function(hc, ...) {
  
  .hc_opt(hc, "legend", ...)
  
}

#' chart options for highcharter objects
#' 
#' General options for the chart.
#' 
#' @param hc A `highchart` `htmlwidget` object. 
#' @param ... Arguments defined in https://api.highcharts.com/highcharts/chart. 
#' 
#' @examples
#' hc <- highchart() %>% 
#'   hc_xAxis(categories = month.abb) %>% 
#'   hc_add_series(name = "Tokyo", data = sample(1:12)) %>% 
#'   hc_add_series(name = "London", data = sample(1:12) + 10)
#' 
#' hc
#' 
#' hc %>% 
#'   hc_chart(
#'     type = "column",
#'     options3d = list(enabled = TRUE, beta = 15, alpha = 15)
#'     )
#' 
#' 
#' hc %>% 
#'   hc_chart(
#'     borderColor = "#EBBA95",
#'     borderRadius = 10,
#'     borderWidth = 2,
#'     backgroundColor = list(
#'       linearGradient = c(0, 0, 500, 500),
#'       stops = list(
#'         list(0, 'rgb(255, 255, 255)'),
#'         list(1, 'rgb(200, 200, 255)')
#'              )
#'       )
#'     )
#' 
#' 
#' @export
hc_chart  <- function(hc, ...) {
  
  .hc_opt(hc, "chart", ...)
  
}

