---
title: Highcharts API
author: Joshua Kunst
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(highcharter)

try(source_api <- readLines("R/highcharts-api.R"))
try(source_api <- readLines("../../R/highcharts-api.R"))
source_api <- source_api[-c(1:3)]

api_funs <- source_api %>%
  str_extract("hc_.* <- function") %>%
  setdiff(NA) %>%
  str_remove_all(" <- function")

blank_lines <- which(source_api == "")

get_rmarkdown_fun <- function(f = "hc_annotations") {
  message(f)

  end_line <- which(str_detect(source_api, paste0("^", f))) - 2

  start_line <- tibble(line = blank_lines) %>%
    filter(line < end_line) %>%
    filter(line == max(line)) %>%
    pull() %>%
    magrittr::add(1)

  source_fun <- source_api[start_line:end_line]
  source_fun <- str_remove(source_fun, "#' ")
  source_fun

  break_lines <- which(source_fun == "")

  source_fun_txt <- source_fun[break_lines[1]:break_lines[2]]

  source_fun_exs <- source_fun[which(str_detect(source_fun, "@example")):length(source_fun)]
  source_fun_exs <- source_fun_exs[-1]
  source_fun_exs <- c("```{r}", source_fun_exs, "```")

  rmarkdown_fun <- c(
    "",
    paste("##", f),
    source_fun_txt,
    source_fun_exs,
    ""
  )

  rmarkdown_fun
}

api_funs <- unique(c("hc_chart", api_funs))

api_funs <- setdiff(api_funs, c("hc_boost", "hc_mapNavigation", ""))

rmarkdown_api <- api_funs %>%
  map(get_rmarkdown_fun) %>%
  reduce(c)

tfile <- tempfile(fileext = ".Rmd")

writeLines(rmarkdown_api, con = tfile)
```

```{r child = tfile}

```
