/*
 Highcharts Gantt JS v8.2.2 (2020-10-22)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(I){b(I);b.Highcharts=I;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function I(b,z,A,w){b.hasOwnProperty(z)||(b[z]=w.apply(null,A))}b=b?b._modules:{};I(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var z=b.extend,A=b.isNumber,w=b.pick,y=function(b,v){var c=b.reduce(function(c,
u){var x=w(u.parent,"");"undefined"===typeof c[x]&&(c[x]=[]);c[x].push(u);return c},{});Object.keys(c).forEach(function(r,u){var x=c[r];""!==r&&-1===v.indexOf(r)&&(x.forEach(function(c){u[""].push(c)}),delete u[r])});return c},p=function(b,v,c,r,u,x){var n=0,q=0,D=x&&x.after,e=x&&x.before;v={data:r,depth:c-1,id:b,level:c,parent:v};var m,h;"function"===typeof e&&e(v,x);e=(u[b]||[]).map(function(a){var g=p(a.id,b,c+1,a,u,x),d=a.start;a=!0===a.milestone?d:a.end;m=!A(m)||d<m?d:m;h=!A(h)||a>h?a:h;n=n+
1+g.descendants;q=Math.max(g.height+1,q);return g});r&&(r.start=w(r.start,m),r.end=w(r.end,h));z(v,{children:e,descendants:n,height:q});"function"===typeof D&&D(v,x);return v};return{getListOfParents:y,getNode:p,getTree:function(b,v){var c=b.map(function(c){return c.id});b=y(b,c);return p("",null,1,null,b,v)}}});I(b,"Core/Axis/TreeGridTick.js",[b["Core/Utilities.js"]],function(b){var z=b.addEvent,A=b.defined,w=b.isObject,y=b.isNumber,p=b.pick,E=b.wrap,v;(function(c){function r(){this.treeGrid||(this.treeGrid=
new D(this))}function u(e,m){e=e.treeGrid;var h=!e.labelIcon,a=m.renderer,g=m.xy,d=m.options,t=d.width,l=d.height,f=g.x-t/2-d.padding;g=g.y-l/2;var G=m.collapsed?90:180,J=m.show&&y(g),B=e.labelIcon;B||(e.labelIcon=B=a.path(a.symbols[d.type](d.x,d.y,t,l)).addClass("highcharts-label-icon").add(m.group));J||B.attr({y:-9999});a.styledMode||B.attr({"stroke-width":1,fill:p(m.color,"#666666")}).css({cursor:"pointer",stroke:d.lineColor,strokeWidth:d.lineWidth});B[h?"attr":"animate"]({translateX:f,translateY:g,
rotation:G})}function x(e,m,h,a,g,d,t,l,f){var G=p(this.options&&this.options.labels,d);d=this.pos;var J=this.axis,B="treegrid"===J.options.type;e=e.apply(this,[m,h,a,g,G,t,l,f]);B&&(m=G&&w(G.symbol,!0)?G.symbol:{},G=G&&y(G.indentation)?G.indentation:0,d=(d=(J=J.treeGrid.mapOfPosToGridNode)&&J[d])&&d.depth||1,e.x+=m.width+2*m.padding+(d-1)*G);return e}function n(e){var m=this,h=m.pos,a=m.axis,g=m.label,d=a.treeGrid.mapOfPosToGridNode,t=a.options,l=p(m.options&&m.options.labels,t&&t.labels),f=l&&w(l.symbol,
!0)?l.symbol:{},G=(d=d&&d[h])&&d.depth;t="treegrid"===t.type;var J=-1<a.tickPositions.indexOf(h);h=a.chart.styledMode;t&&d&&g&&g.element&&g.addClass("highcharts-treegrid-node-level-"+G);e.apply(m,Array.prototype.slice.call(arguments,1));t&&g&&g.element&&d&&d.descendants&&0<d.descendants&&(a=a.treeGrid.isCollapsed(d),u(m,{color:!h&&g.styles&&g.styles.color||"",collapsed:a,group:g.parentGroup,options:f,renderer:g.renderer,show:J,xy:g.xy}),f="highcharts-treegrid-node-"+(a?"expanded":"collapsed"),g.addClass("highcharts-treegrid-node-"+
(a?"collapsed":"expanded")).removeClass(f),h||g.css({cursor:"pointer"}),[g,m.treeGrid.labelIcon].forEach(function(a){a&&!a.attachedTreeGridEvents&&(z(a.element,"mouseover",function(){g.addClass("highcharts-treegrid-node-active");g.renderer.styledMode||g.css({textDecoration:"underline"})}),z(a.element,"mouseout",function(){var a=A(l.style)?l.style:{};g.removeClass("highcharts-treegrid-node-active");g.renderer.styledMode||g.css({textDecoration:a.textDecoration})}),z(a.element,"click",function(){m.treeGrid.toggleCollapse()}),
a.attachedTreeGridEvents=!0)}))}var q=!1;c.compose=function(e){q||(z(e,"init",r),E(e.prototype,"getLabelPosition",x),E(e.prototype,"renderLabel",n),e.prototype.collapse=function(e){this.treeGrid.collapse(e)},e.prototype.expand=function(e){this.treeGrid.expand(e)},e.prototype.toggleCollapse=function(e){this.treeGrid.toggleCollapse(e)},q=!0)};var D=function(){function e(e){this.tick=e}e.prototype.collapse=function(e){var h=this.tick,a=h.axis,g=a.brokenAxis;g&&a.treeGrid.mapOfPosToGridNode&&(h=a.treeGrid.collapse(a.treeGrid.mapOfPosToGridNode[h.pos]),
g.setBreaks(h,p(e,!0)))};e.prototype.expand=function(e){var h=this.tick,a=h.axis,g=a.brokenAxis;g&&a.treeGrid.mapOfPosToGridNode&&(h=a.treeGrid.expand(a.treeGrid.mapOfPosToGridNode[h.pos]),g.setBreaks(h,p(e,!0)))};e.prototype.toggleCollapse=function(e){var h=this.tick,a=h.axis,g=a.brokenAxis;g&&a.treeGrid.mapOfPosToGridNode&&(h=a.treeGrid.toggleCollapse(a.treeGrid.mapOfPosToGridNode[h.pos]),g.setBreaks(h,p(e,!0)))};return e}();c.Additions=D})(v||(v={}));return v});I(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],
b["Core/Utilities.js"]],function(b,z){var A=z.extend,w=z.isArray,y=z.isNumber,p=z.isObject,E=z.merge,v=z.pick;return{getColor:function(c,r){var u=r.index,x=r.mapOptionsToLevel,n=r.parentColor,q=r.parentColorIndex,D=r.series,e=r.colors,m=r.siblings,h=D.points,a=D.chart.options.chart,g;if(c){h=h[c.i];c=x[c.level]||{};if(x=h&&c.colorByPoint){var d=h.index%(e?e.length:a.colorCount);var t=e&&e[d]}if(!D.chart.styledMode){e=h&&h.options.color;a=c&&c.color;if(g=n)g=(g=c&&c.colorVariation)&&"brightness"===
g.key?b.parse(n).brighten(u/m*g.to).get():n;g=v(e,a,t,g,D.color)}var l=v(h&&h.options.colorIndex,c&&c.colorIndex,d,q,r.colorIndex)}return{color:g,colorIndex:l}},getLevelOptions:function(c){var r=null;if(p(c)){r={};var u=y(c.from)?c.from:1;var x=c.levels;var n={};var q=p(c.defaults)?c.defaults:{};w(x)&&(n=x.reduce(function(c,e){if(p(e)&&y(e.level)){var m=E({},e);var h="boolean"===typeof m.levelIsConstant?m.levelIsConstant:q.levelIsConstant;delete m.levelIsConstant;delete m.level;e=e.level+(h?0:u-1);
p(c[e])?A(c[e],m):c[e]=m}return c},{}));x=y(c.to)?c.to:1;for(c=0;c<=x;c++)r[c]=E({},q,p(n[c])?n[c]:{})}return r},setTreeValues:function x(r,u){var n=u.before,q=u.idRoot,D=u.mapIdToNode[q],e=u.points[r.i],m=e&&e.options||{},h=0,a=[];A(r,{levelDynamic:r.level-(("boolean"===typeof u.levelIsConstant?u.levelIsConstant:1)?0:D.level),name:v(e&&e.name,""),visible:q===r.id||("boolean"===typeof u.visible?u.visible:!1)});"function"===typeof n&&(r=n(r,u));r.children.forEach(function(g,d){var t=A({},u);A(t,{index:d,
siblings:r.children.length,visible:r.visible});g=x(g,t);a.push(g);g.visible&&(h+=g.val)});r.visible=0<h||r.visible;n=v(m.value,h);A(r,{children:a,childrenTotal:h,isLeaf:r.visible&&!h,val:n});return r},updateRootId:function(r){if(p(r)){var u=p(r.options)?r.options:{};u=v(r.rootNode,u.rootId,"");p(r.userOptions)&&(r.userOptions.rootId=u);r.rootNode=u}return u}}});I(b,"Core/Axis/GridAxis.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],
function(b,z,A,w,y){var p=y.addEvent,E=y.defined,v=y.erase,c=y.find,r=y.isArray,u=y.isNumber,x=y.merge,n=y.pick,q=y.timeUnits,D=y.wrap;A=z.Chart;var e=function(a){var g=a.options;g.labels||(g.labels={});g.labels.align=n(g.labels.align,"center");a.categories||(g.showLastLabel=!1);a.labelRotation=0;g.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(a,g){var d={width:0,height:0};g.forEach(function(g){g=a[g];if(y.isObject(g,!0)){var l=y.isObject(g.label,!0)?g.label:{};g=l.getBBox?l.getBBox().height:
0;l.textStr&&!u(l.textPxLength)&&(l.textPxLength=l.getBBox().width);var f=u(l.textPxLength)?Math.round(l.textPxLength):0;l.textStr&&(f=Math.round(l.getBBox().width));d.height=Math.max(g,d.height);d.width=Math.max(f,d.width)}});return d};z.dateFormats.W=function(a){a=new this.Date(a);var g=(this.get("Day",a)+6)%7,d=new this.Date(a.valueOf());this.set("Date",d,this.get("Date",a)-g+3);g=new this.Date(this.get("FullYear",d),0,1);4!==this.get("Day",g)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",
g))%7));return(1+Math.floor((d.valueOf()-g.valueOf())/6048E5)).toString()};z.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};p(A,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})});p(w,"afterGetLabelPosition",function(a){var g=this.label,d=this.axis,t=d.reversed,l=d.chart,f=d.options.grid||{},e=d.options.labels,J=e.align,B=h.Side[d.side],c=a.tickmarkOffset,m=d.tickPositions,
H=this.pos-c;m=u(m[a.index+1])?m[a.index+1]-c:d.max+c;var k=d.tickSize("tick");c=k?k[0]:0;k=k?k[1]/2:0;if(!0===f.enabled){if("top"===B){f=d.top+d.offset;var C=f-c}else"bottom"===B?(C=l.chartHeight-d.bottom+d.offset,f=C+c):(f=d.top+d.len-d.translate(t?m:H),C=d.top+d.len-d.translate(t?H:m));"right"===B?(B=l.chartWidth-d.right+d.offset,t=B+c):"left"===B?(t=d.left+d.offset,B=t-c):(B=Math.round(d.left+d.translate(t?m:H))-k,t=Math.round(d.left+d.translate(t?H:m))-k);this.slotWidth=t-B;a.pos.x="left"===
J?B:"right"===J?t:B+(t-B)/2;a.pos.y=C+(f-C)/2;l=l.renderer.fontMetrics(e.style.fontSize,g.element);g=g.getBBox().height;e.useHTML?a.pos.y+=l.b+-(g/2):(g=Math.round(g/l.h),a.pos.y+=(l.b-(l.h-l.f))/2+-((g-1)*l.h/2));a.pos.x+=d.horiz&&e.x||0}});var m=function(){function a(a){this.axis=a}a.prototype.isOuterAxis=function(){var a=this.axis,d=a.grid.columnIndex,t=a.linkedParent&&a.linkedParent.grid.columns||a.grid.columns,l=d?a.linkedParent:a,f=-1,e=0;a.chart[a.coll].forEach(function(g,d){g.side!==a.side||
g.options.isInternal||(e=d,g===l&&(f=d))});return e===f&&(u(d)?t.length===d:!0)};a.prototype.renderBorder=function(a){var d=this.axis,g=d.chart.renderer,l=d.options;a=g.path(a).addClass("highcharts-axis-line").add(d.axisBorder);g.styledMode||a.attr({stroke:l.lineColor,"stroke-width":l.lineWidth,zIndex:7});return a};return a}(),h=function(){function a(){}a.compose=function(g){b.keepProps.push("grid");D(g.prototype,"unsquish",a.wrapUnsquish);p(g,"init",a.onInit);p(g,"afterGetOffset",a.onAfterGetOffset);
p(g,"afterGetTitlePosition",a.onAfterGetTitlePosition);p(g,"afterInit",a.onAfterInit);p(g,"afterRender",a.onAfterRender);p(g,"afterSetAxisTranslation",a.onAfterSetAxisTranslation);p(g,"afterSetOptions",a.onAfterSetOptions);p(g,"afterSetOptions",a.onAfterSetOptions2);p(g,"afterSetScale",a.onAfterSetScale);p(g,"afterTickSize",a.onAfterTickSize);p(g,"trimTicks",a.onTrimTicks);p(g,"destroy",a.onDestroy)};a.onAfterGetOffset=function(){var a=this.grid;(a&&a.columns||[]).forEach(function(a){a.getOffset()})};
a.onAfterGetTitlePosition=function(g){if(!0===(this.options.grid||{}).enabled){var d=this.axisTitle,t=this.height,l=this.horiz,f=this.left,e=this.offset,h=this.opposite,B=this.options.title,c=void 0===B?{}:B;B=this.top;var m=this.width,H=this.tickSize(),k=d&&d.getBBox().width,C=c.x||0,F=c.y||0,P=n(c.margin,l?5:10);d=this.chart.renderer.fontMetrics(c.style&&c.style.fontSize,d).f;H=(l?B+t:f)+(l?1:-1)*(h?-1:1)*(H?H[0]/2:0)+(this.side===a.Side.bottom?d:0);g.titlePosition.x=l?f-k/2-P+C:H+(h?m:0)+e+C;g.titlePosition.y=
l?H-(h?t:0)+(h?d:-d)/2+e+F:B-P+F}};a.onAfterInit=function(){var a=this.chart,d=this.options.grid;d=void 0===d?{}:d;var t=this.userOptions;d.enabled&&(e(this),D(this,"labelFormatter",function(a){var d=this.axis,g=this.value,l=d.tickPositions,f=(d.isLinked?d.linkedParent:d).series[0],k=g===l[0];l=g===l[l.length-1];var C=f&&c(f.options.data,function(k){return k[d.isXAxis?"x":"y"]===g});if(C&&f.is("gantt")){var F=x(C);z.seriesTypes.gantt.prototype.setGanttPointAliases(F)}this.isFirst=k;this.isLast=l;
this.point=F;return a.call(this)}));if(d.columns)for(var l=this.grid.columns=[],f=this.grid.columnIndex=0;++f<d.columns.length;){var h=x(t,d.columns[d.columns.length-f-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete h.grid.columns;h=new b(this.chart,h);h.grid.isColumn=!0;h.grid.columnIndex=f;v(a.axes,h);v(a[this.coll],h);l.push(h)}};a.onAfterRender=function(){var g,d=this.grid,t=this.options;if(!0===(t.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,
this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(t=t.lineWidth)){t=this.getLinePath(t);var l=t[0],f=t[1],e=((this.tickSize("tick")||[1])[0]-1)*(this.side===a.Side.top||this.side===a.Side.left?-1:1);"M"===l[0]&&"L"===f[0]&&(this.horiz?(l[2]+=e,f[2]+=e):(l[1]+=e,f[1]+=e));!this.horiz&&this.chart.marginRight&&(l=[l,["L",this.left,l[2]]],e=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],f=
[["M",f[1],this.toPixels(this.max+this.tickmarkOffset)],e],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(l)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:l}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(f)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:f}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:t}):this.grid.axisLineExtra=this.grid.renderBorder(t);this.axisLine[this.showAxis?"show":
"hide"](!0)}(d&&d.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(g=this.linkedParent)||void 0===g?0:g.scrollbar))&&(g=this.max,d=this.tickmarkOffset,t=this.tickPositions[this.tickPositions.length-1],f=this.tickPositions[0],this.min-f>d?this.ticks[f].label.hide():this.ticks[f].label.show(),t-g>d?this.ticks[t].label.hide():this.ticks[t].label.show(),t-g<d&&0<t-g&&this.ticks[t].isLast?this.ticks[t].mark.hide():this.ticks[t-1].mark.show())}};
a.onAfterSetAxisTranslation=function(){var a,d=this.tickPositions&&this.tickPositions.info,e=this.options,l=e.grid||{},f=this.userOptions.labels||{};this.horiz?(!0===l.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),d&&e.dateTimeLabelFormats&&e.labels&&!E(f.align)&&(!1===e.dateTimeLabelFormats[d.unitName].range||1<d.count)&&(e.labels.align="left",E(f.x)||(e.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};
a.onAfterSetOptions=function(a){var d=this.options;a=a.userOptions;var g=d&&y.isObject(d.grid,!0)?d.grid:{};if(!0===g.enabled){var l=x(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(E(a.linkedTo)&&!E(a.tickPixelInterval)&&(l.tickPixelInterval=350),E(a.tickPixelInterval)||!E(a.linkedTo)||E(a.tickPositioner)||E(a.tickInterval)||(l.tickPositioner=function(a,d){var g=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(g){var f,e=l.units;for(f=0;f<e.length;f++)if(e[f][0]===g.unitName){var t=f;break}if(e[t+1]){var H=e[t+
1][0];var k=(e[t+1][1]||[1])[0]}else"year"===g.unitName&&(H="year",k=10*g.count);g=q[H];this.tickInterval=g*k;return this.getTimeTicks({unitRange:g,count:k,unitName:H},a,d,this.options.startOfWeek)}}));x(!0,this.options,l);this.horiz&&(d.minPadding=n(a.minPadding,0),d.maxPadding=n(a.maxPadding,0));u(d.grid.borderWidth)&&(d.tickWidth=d.lineWidth=g.borderWidth)}};a.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var d=a.columns;a.enabled&&d&&x(!0,this.options,d[d.length-1])};a.onAfterSetScale=
function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};a.onAfterTickSize=function(a){var d=b.defaultLeftAxisOptions,g=this.horiz,l=this.maxLabelDimensions,f=this.options.grid;f=void 0===f?{}:f;f.enabled&&l&&(d=2*Math.abs(d.labels.x),g=g?f.cellHeight||d+l.height:d+l.width,r(a.tickSize)?a.tickSize[0]=g:a.tickSize=[g,0])};a.onDestroy=function(a){var d=this.grid;(d.columns||[]).forEach(function(d){d.destroy(a.keepEvents)});d.columns=void 0};a.onInit=function(a){a=a.userOptions||{};var d=
a.grid||{};d.enabled&&E(d.borderColor)&&(a.tickColor=a.lineColor=d.borderColor);this.grid||(this.grid=new m(this))};a.onTrimTicks=function(){var a=this.options,d=this.categories,e=this.tickPositions,l=e[0],f=e[e.length-1],h=this.linkedParent&&this.linkedParent.min||this.min,c=this.linkedParent&&this.linkedParent.max||this.max,B=this.tickInterval;!0!==(a.grid||{}).enabled||d||!this.horiz&&!this.isLinked||(l<h&&l+B>h&&!a.startOnTick&&(e[0]=h),f>c&&f-B<c&&!a.endOnTick&&(e[e.length-1]=c))};a.wrapUnsquish=
function(a){var d=this.options.grid;return!0===(void 0===d?{}:d).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return a}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});I(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,z,A,w){var y=w.addEvent,p=w.find,
E=w.fireEvent,v=w.isArray,c=w.isNumber,r=w.pick,u=function(){function c(c){this.hasBreaks=!1;this.axis=c}c.isInBreak=function(c,q){var D=c.repeat||Infinity,e=c.from,m=c.to-c.from;q=q>=e?(q-e)%D:D-(e-q)%D;return c.inclusive?q<=m:q<m&&0!==q};c.lin2Val=function(n){var q=this.brokenAxis;q=q&&q.breakArray;if(!q)return n;var D;for(D=0;D<q.length;D++){var e=q[D];if(e.from>=n)break;else e.to<n?n+=e.len:c.isInBreak(e,n)&&(n+=e.len)}return n};c.val2Lin=function(n){var q=this.brokenAxis;q=q&&q.breakArray;if(!q)return n;
var D=n,e;for(e=0;e<q.length;e++){var m=q[e];if(m.to<=n)D-=m.len;else if(m.from>=n)break;else if(c.isInBreak(m,n)){D-=n-m.from;break}}return D};c.prototype.findBreakAt=function(c,q){return p(q,function(q){return q.from<c&&c<q.to})};c.prototype.isInAnyBreak=function(n,q){var D=this.axis,e=D.options.breaks,m=e&&e.length,h;if(m){for(;m--;)if(c.isInBreak(e[m],n)){var a=!0;h||(h=r(e[m].showPoints,!D.isXAxis))}var g=a&&q?a&&!h:a}return g};c.prototype.setBreaks=function(n,q){var D=this,e=D.axis,m=v(n)&&
!!n.length;e.isDirty=D.hasBreaks!==m;D.hasBreaks=m;e.options.breaks=e.userOptions.breaks=n;e.forceRedraw=!0;e.series.forEach(function(e){e.isDirty=!0});m||e.val2lin!==c.val2Lin||(delete e.val2lin,delete e.lin2val);m&&(e.userOptions.ordinal=!1,e.lin2val=c.lin2Val,e.val2lin=c.val2Lin,e.setExtremes=function(e,a,g,d,c){if(D.hasBreaks){for(var l,f=this.options.breaks;l=D.findBreakAt(e,f);)e=l.to;for(;l=D.findBreakAt(a,f);)a=l.from;a<e&&(a=e)}b.prototype.setExtremes.call(this,e,a,g,d,c)},e.setAxisTranslation=
function(h){b.prototype.setAxisTranslation.call(this,h);D.unitLength=null;if(D.hasBreaks){h=e.options.breaks||[];var a=[],g=[],d=0,t,l=e.userMin||e.min,f=e.userMax||e.max,m=r(e.pointRangePadding,0),J;h.forEach(function(a){t=a.repeat||Infinity;c.isInBreak(a,l)&&(l+=a.to%t-l%t);c.isInBreak(a,f)&&(f-=f%t-a.from%t)});h.forEach(function(d){q=d.from;for(t=d.repeat||Infinity;q-t>l;)q-=t;for(;q<l;)q+=t;for(J=q;J<f;J+=t)a.push({value:J,move:"in"}),a.push({value:J+(d.to-d.from),move:"out",size:d.breakSize})});
a.sort(function(a,d){return a.value===d.value?("in"===a.move?0:1)-("in"===d.move?0:1):a.value-d.value});var B=0;var q=l;a.forEach(function(a){B+="in"===a.move?1:-1;1===B&&"in"===a.move&&(q=a.value);0===B&&(g.push({from:q,to:a.value,len:a.value-q-(a.size||0)}),d+=a.value-q-(a.size||0))});e.breakArray=D.breakArray=g;D.unitLength=f-l-d+m;E(e,"afterBreaks");e.staticScale?e.transA=e.staticScale:D.unitLength&&(e.transA*=(f-e.min+m)/D.unitLength);m&&(e.minPixelPadding=e.transA*e.minPointOffset);e.min=l;
e.max=f}});r(q,!0)&&e.chart.redraw()};return c}();w=function(){function x(){}x.compose=function(n,q){n.keepProps.push("brokenAxis");var D=z.prototype;D.drawBreaks=function(e,m){var h=this,a=h.points,g,d,t,l;if(e&&e.brokenAxis&&e.brokenAxis.hasBreaks){var f=e.brokenAxis;m.forEach(function(m){g=f&&f.breakArray||[];d=e.isXAxis?e.min:r(h.options.threshold,e.min);a.forEach(function(a){l=r(a["stack"+m.toUpperCase()],a[m]);g.forEach(function(f){if(c(d)&&c(l)){t=!1;if(d<f.from&&l>f.to||d>f.from&&l<f.from)t=
"pointBreak";else if(d<f.from&&l>f.from&&l<f.to||d>f.from&&l>f.to&&l<f.from)t="pointInBreak";t&&E(e,t,{point:a,brk:f})}})})})}};D.gappedPath=function(){var e=this.currentDataGrouping,c=e&&e.gapSize;e=this.options.gapSize;var h=this.points.slice(),a=h.length-1,g=this.yAxis,d;if(e&&0<a)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),c&&c>e&&c>=this.basePointRange&&(e=c),d=void 0;a--;)d&&!1!==d.visible||(d=h[a+1]),c=h[a],!1!==d.visible&&!1!==c.visible&&(d.x-c.x>e&&(d=(c.x+d.x)/2,h.splice(a+
1,0,{isNull:!0,x:d}),g.stacking&&this.options.stacking&&(d=g.stacking.stacks[this.stackKey][d]=new A(g,g.options.stackLabels,!1,d,this.stack),d.total=0)),d=c);return this.getGraphPath(h)};y(n,"init",function(){this.brokenAxis||(this.brokenAxis=new u(this))});y(n,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});y(n,"afterSetTickPositions",function(){var e=this.brokenAxis;if(e&&e.hasBreaks){var c=this.tickPositions,h=this.tickPositions.info,
a=[],g;for(g=0;g<c.length;g++)e.isInAnyBreak(c[g])||a.push(c[g]);this.tickPositions=a;this.tickPositions.info=h}});y(n,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});y(q,"afterGeneratePoints",function(){var e=this.options.connectNulls,c=this.points,h=this.xAxis,a=this.yAxis;if(this.isDirty)for(var g=c.length;g--;){var d=c[g],t=!(null===d.y&&!1===e)&&(h&&h.brokenAxis&&h.brokenAxis.isInAnyBreak(d.x,!0)||a&&a.brokenAxis&&a.brokenAxis.isInAnyBreak(d.y,
!0));d.visible=t?!1:!1!==d.options.visible}});y(q,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,r(this.pointArrayMap,["y"]))})};return x}();w.compose(b,z);return w});I(b,"Core/Axis/TreeGridAxis.js",[b["Core/Globals.js"],b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,z,A,w,y,p,E){var v=p.getLevelOptions,c=E.addEvent,r=E.find,u=E.fireEvent,x=E.isArray,
n=E.isNumber,q=E.isObject,D=E.isString,e=E.merge,m=E.pick,h=E.wrap,a;(function(a){function d(a,k){var d=a.collapseStart||0;a=a.collapseEnd||0;a>=k&&(d-=.5);return{from:d,to:a,showPoints:!1}}function g(a,k,d){var f=[],l=[],C={},e={},g=-1,c="boolean"===typeof k?k:!1;a=w.getTree(a,{after:function(a){a=e[a.pos];var k=0,d=0;a.children.forEach(function(a){d+=(a.descendants||0)+1;k=Math.max((a.height||0)+1,k)});a.descendants=d;a.height=k;a.collapsed&&l.push(a)},before:function(a){var k=q(a.data,!0)?a.data:
{},d=D(k.name)?k.name:"",l=C[a.parent];l=q(l,!0)?e[l.pos]:null;var F=function(a){return a.name===d},t;c&&q(l,!0)&&(t=r(l.children,F))?(F=t.pos,t.nodes.push(a)):F=g++;e[F]||(e[F]=t={depth:l?l.depth+1:0,name:d,id:k.id,nodes:[a],children:[],pos:F},-1!==F&&f.push(d),q(l,!0)&&l.children.push(t));D(a.id)&&(C[a.id]=a);t&&!0===k.collapsed&&(t.collapsed=!0);a.pos=F}});e=function(a,k){var d=function(a,l,f){var C=l+(-1===l?0:k-1),e=(C-l)/2,g=l+e;a.nodes.forEach(function(a){var k=a.data;q(k,!0)&&(k.y=l+(k.seriesIndex||
0),delete k.seriesIndex);a.pos=g});f[g]=a;a.pos=g;a.tickmarkOffset=e+.5;a.collapseStart=C+.5;a.children.forEach(function(a){d(a,C+1,f);C=(a.collapseEnd||0)-.5});a.collapseEnd=C+.5;return f};return d(a["-1"],-1,{})}(e,d);return{categories:f,mapOfIdToNode:C,mapOfPosToGridNode:e,collapsedNodes:l,tree:a}}function l(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(k){var d=k.options||{},l=d.labels,f=d.uniqueNames,c=0;d=d.max;if(!k.treeGrid.mapOfPosToGridNode||k.series.some(function(a){return!a.hasRendered||
a.isDirtyData||a.isDirty})){var t=k.series.reduce(function(a,k){k.visible&&((k.options.data||[]).forEach(function(d){k.options.keys&&k.options.keys.length&&(d=k.pointClass.prototype.optionsToObject.call({series:k},d),b.seriesTypes.gantt.prototype.setGanttPointAliases(d));q(d,!0)&&(d.seriesIndex=c,a.push(d))}),!0===f&&c++);return a},[]);if(d&&t.length<d)for(var h=t.length;h<=d;h++)t.push({name:h+"\u200b"});d=g(t,f||!1,!0===f?c:1);k.categories=d.categories;k.treeGrid.mapOfPosToGridNode=d.mapOfPosToGridNode;
k.hasNames=!0;k.treeGrid.tree=d.tree;k.series.forEach(function(a){var k=(a.options.data||[]).map(function(k){x(k)&&a.options.keys&&a.options.keys.length&&t.forEach(function(a){0<=k.indexOf(a.x)&&0<=k.indexOf(a.x2)&&(k=a)});return q(k,!0)?e(k):k});a.visible&&a.setData(k,!1)});k.treeGrid.mapOptionsToLevel=v({defaults:l,from:1,levels:l&&l.levels,to:k.treeGrid.tree&&k.treeGrid.tree.height});"beforeRender"===a.type&&(k.treeGrid.collapsedNodes=d.collapsedNodes)}})}function f(a,k){var d=this.treeGrid.mapOptionsToLevel||
{},l=this.ticks,f=l[k],e;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[k];(d=d[g.depth])&&(e={labels:d});f?(f.parameters.category=g.name,f.options=e,f.addLabel()):l[k]=new A(this,k,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:e})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function G(a){var k=this.options;k=(k=k&&k.labels)&&n(k.indentation)?k.indentation:0;var d=a.apply(this,Array.prototype.slice.call(arguments,
1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var l=this.treeGrid.mapOfPosToGridNode[-1].height||0;d.width+=k*(l-1)}return d}function J(a,k,d){var f=this,C="treegrid"===d.type;f.treeGrid||(f.treeGrid=new p(f));C&&(c(k,"beforeRender",l),c(k,"beforeRedraw",l),c(k,"addSeries",function(a){a.options.data&&(a=g(a.options.data,d.uniqueNames||!1,1),f.treeGrid.collapsedNodes=(f.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),c(f,"foundExtremes",function(){f.treeGrid.collapsedNodes&&
f.treeGrid.collapsedNodes.forEach(function(a){var k=f.treeGrid.collapse(a);f.brokenAxis&&(f.brokenAxis.setBreaks(k,!1),f.treeGrid.collapsedNodes&&(f.treeGrid.collapsedNodes=f.treeGrid.collapsedNodes.filter(function(k){return a.collapseStart!==k.collapseStart||a.collapseEnd!==k.collapseEnd})))})}),c(f,"afterBreaks",function(){var a;"yAxis"===f.coll&&!f.staticScale&&(null===(a=f.chart.options.chart)||void 0===a?0:a.height)&&(f.isDirty=!0)}),d=e({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},
{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));a.apply(f,[k,d]);C&&(f.hasNames=!0,f.options.showLastLabel=!0)}function B(a){var k=this.options;"treegrid"===k.type?(this.min=m(this.userMin,k.min,this.dataMin),this.max=m(this.userMax,k.max,this.dataMax),u(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?
this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var M=!1;a.compose=function(a){M||(h(a.prototype,"generateTick",f),h(a.prototype,"getMaxLabelDimensions",G),h(a.prototype,"init",J),h(a.prototype,"setTickInterval",B),y.compose(A),M=!0)};var p=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var k=this.axis,d=k.chart;k.series.forEach(function(k){var f=k.options.data;if(a.id&&f){var l=d.get(a.id);k=f[k.data.indexOf(l)];l&&k&&(l.collapsed=
a.collapsed,k.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var k=this.axis,f=k.options.breaks||[],l=d(a,k.max);f.push(l);a.collapsed=!0;k.treeGrid.setCollapsedStatus(a);return f};a.prototype.expand=function(a){var k=this.axis,f=k.options.breaks||[],l=d(a,k.max);a.collapsed=!1;k.treeGrid.setCollapsedStatus(a);return f.reduce(function(a,k){k.to===l.to&&k.from===l.from||a.push(k);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis,d=Math.floor(a.min/a.tickInterval)*
a.tickInterval,f=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(k,l){l=+l;!(l>=d&&l<=f)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(l)||k.push(l);return k},[])};a.prototype.isCollapsed=function(a){var k=this.axis,f=k.options.breaks||[],l=d(a,k.max);return f.some(function(a){return a.from===l.from&&a.to===l.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();a.Additions=
p})(a||(a={}));z.prototype.utils={getNode:w.getNode};a.compose(z);return a});I(b,"Extensions/CurrentDateIndication.js",[b["Core/Axis/Axis.js"],b["Core/Utilities.js"],b["Core/Axis/PlotLineOrBand.js"]],function(b,z,A){var w=z.addEvent,y=z.merge;z=z.wrap;var p={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(b,v){return this.axis.chart.time.dateFormat(v,b)},rotation:0,style:{fontSize:"10px"}}};w(b,"afterSetOptions",function(){var b=this.options,
v=b.currentDateIndicator;v&&(v="object"===typeof v?y(p,v):y(p),v.value=new Date,b.plotLines||(b.plotLines=[]),b.plotLines.push(v))});w(A,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});z(A.prototype,"getLabelText",function(b,v){var c=this.options;return c.currentDateIndicator&&c.label&&"function"===typeof c.label.formatter?(c.value=new Date,c.label.formatter.call(this,c.value,c.label.format)):b.call(this,v)})});I(b,"Extensions/StaticScale.js",[b["Core/Axis/Axis.js"],
b["Core/Chart/Chart.js"],b["Core/Utilities.js"]],function(b,z,A){var w=A.addEvent,y=A.defined,p=A.isNumber,E=A.pick;w(b,"afterSetOptions",function(){var b=this.chart.options&&this.chart.options.chart;!this.horiz&&p(this.options.staticScale)&&(!b.height||b.scrollablePlotArea&&b.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});z.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(b){var c=b.chart,r=!!c.initiatedScale&&
c.options.animation,u=b.options.staticScale;if(b.staticScale&&y(b.min)){var x=E(b.brokenAxis&&b.brokenAxis.unitLength,b.max+b.tickInterval-b.min)*u;x=Math.max(x,u);u=x-c.plotHeight;1<=Math.abs(u)&&(c.plotHeight=x,c.redrawTrigger="adjustHeight",c.setSize(void 0,c.chartHeight+u,r));b.series.forEach(function(b){(b=b.sharedClipKey&&c[b.sharedClipKey])&&b.attr({height:c.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};w(z,"render",z.prototype.adjustHeight)});I(b,"Extensions/ArrowSymbols.js",
[b["Core/Renderer/SVG/SVGRenderer.js"]],function(b){b.prototype.symbols.arrow=function(b,A,w,y){return[["M",b,A+y/2],["L",b+w,A],["L",b,A+y/2],["L",b+w,A+y]]};b.prototype.symbols["arrow-half"]=function(z,A,w,y){return b.prototype.symbols.arrow(z,A,w/2,y)};b.prototype.symbols["triangle-left"]=function(b,A,w,y){return[["M",b+w,A],["L",b,A+y/2],["L",b+w,A+y],["Z"]]};b.prototype.symbols["arrow-filled"]=b.prototype.symbols["triangle-left"];b.prototype.symbols["triangle-left-half"]=function(z,A,w,y){return b.prototype.symbols["triangle-left"](z,
A,w/2,y)};b.prototype.symbols["arrow-filled-half"]=b.prototype.symbols["triangle-left-half"]});I(b,"Gantt/Connection.js",[b["Core/Globals.js"],b["Core/Options.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,z,A,w){function y(c){var b=c.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=c.graphic&&c.graphic.getBBox())?{xMin:c.plotX-b.width/2,xMax:c.plotX+b.width/2,yMin:c.plotY-b.height/2,yMax:c.plotY+b.height/2}:null}"";var p=w.defined,E=w.error,v=w.extend,
c=w.merge,r=w.objectEach,u=b.deg2rad,x=Math.max,n=Math.min;v(z.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});z=function(){function b(c,e,b){this.toPoint=this.pathfinder=this.graphics=this.fromPoint=this.chart=void 0;this.init(c,e,b)}b.prototype.init=function(c,e,b){this.fromPoint=c;this.toPoint=e;this.options=b;this.chart=c.series.chart;this.pathfinder=
this.chart.pathfinder};b.prototype.renderPath=function(c,e,b){var h=this.chart,a=h.styledMode,g=h.pathfinder,d=!h.options.chart.forExport&&!1!==b,t=this.graphics&&this.graphics.path;g.group||(g.group=h.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(h.seriesGroup));g.group.translate(h.plotLeft,h.plotTop);t&&t.renderer||(t=h.renderer.path().add(g.group),a||t.attr({opacity:0}));t.attr(e);c={d:c};a||(c.opacity=1);t[d?"animate":"attr"](c,b);this.graphics=this.graphics||{};this.graphics.path=
t};b.prototype.addMarker=function(c,e,b){var h=this.fromPoint.series.chart,a=h.pathfinder;h=h.renderer;var g="start"===c?this.fromPoint:this.toPoint,d=g.getPathfinderAnchorPoint(e);if(e.enabled&&((b="start"===c?b[1]:b[b.length-2])&&"M"===b[0]||"L"===b[0])){b={x:b[1],y:b[2]};b=g.getRadiansToVector(b,d);d=g.getMarkerVector(b,e.radius,d);b=-b/u;if(e.width&&e.height){var t=e.width;var l=e.height}else t=l=2*e.radius;this.graphics=this.graphics||{};d={x:d.x-t/2,y:d.y-l/2,width:t,height:l,rotation:b,rotationOriginX:d.x,
rotationOriginY:d.y};this.graphics[c]?this.graphics[c].animate(d):(this.graphics[c]=h.symbol(e.symbol).addClass("highcharts-point-connecting-path-"+c+"-marker").attr(d).add(a.group),h.styledMode||this.graphics[c].attr({fill:e.color||this.fromPoint.color,stroke:e.lineColor,"stroke-width":e.lineWidth,opacity:0}).animate({opacity:1},g.series.options.animation))}};b.prototype.getPath=function(b){var e=this.pathfinder,m=this.chart,h=e.algorithms[b.type],a=e.chartObstacles;if("function"!==typeof h)return E('"'+
b.type+'" is not a Pathfinder algorithm.'),{path:[],obstacles:[]};h.requiresObstacles&&!a&&(a=e.chartObstacles=e.getChartObstacles(b),m.options.connectors.algorithmMargin=b.algorithmMargin,e.chartObstacleMetrics=e.getObstacleMetrics(a));return h(this.fromPoint.getPathfinderAnchorPoint(b.startMarker),this.toPoint.getPathfinderAnchorPoint(b.endMarker),c({chartObstacles:a,lineObstacles:e.lineObstacles||[],obstacleMetrics:e.chartObstacleMetrics,hardBounds:{xMin:0,xMax:m.plotWidth,yMin:0,yMax:m.plotHeight},
obstacleOptions:{margin:b.algorithmMargin},startDirectionX:e.getAlgorithmStartDirection(b.startMarker)},b))};b.prototype.render=function(){var b=this.fromPoint,e=b.series,m=e.chart,h=m.pathfinder,a=c(m.options.connectors,e.options.connectors,b.options.connectors,this.options),g={};m.styledMode||(g.stroke=a.lineColor||b.color,g["stroke-width"]=a.lineWidth,a.dashStyle&&(g.dashstyle=a.dashStyle));g["class"]="highcharts-point-connecting-path highcharts-color-"+b.colorIndex;a=c(g,a);p(a.marker.radius)||
(a.marker.radius=n(x(Math.ceil((a.algorithmMargin||8)/2)-1,1),5));b=this.getPath(a);m=b.path;b.obstacles&&(h.lineObstacles=h.lineObstacles||[],h.lineObstacles=h.lineObstacles.concat(b.obstacles));this.renderPath(m,g,e.options.animation);this.addMarker("start",c(a.marker,a.startMarker),m);this.addMarker("end",c(a.marker,a.endMarker),m)};b.prototype.destroy=function(){this.graphics&&(r(this.graphics,function(c){c.destroy()}),delete this.graphics)};return b}();b.Connection=z;v(A.prototype,{getPathfinderAnchorPoint:function(c){var b=
y(this);switch(c.align){case "right":var e="xMax";break;case "left":e="xMin"}switch(c.verticalAlign){case "top":var m="yMin";break;case "bottom":m="yMax"}return{x:e?b[e]:(b.xMin+b.xMax)/2,y:m?b[m]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(c,b){var e;p(b)||(e=y(this))&&(b={x:(e.xMin+e.xMax)/2,y:(e.yMin+e.yMax)/2});return Math.atan2(b.y-c.y,c.x-b.x)},getMarkerVector:function(c,b,e){var m=2*Math.PI,h=y(this),a=h.xMax-h.xMin,g=h.yMax-h.yMin,d=Math.atan2(g,a),t=!1;a/=2;var l=g/2,f=h.xMin+a;h=h.yMin+
l;for(var G=f,J=h,B={},u=1,n=1;c<-Math.PI;)c+=m;for(;c>Math.PI;)c-=m;m=Math.tan(c);c>-d&&c<=d?(n=-1,t=!0):c>d&&c<=Math.PI-d?n=-1:c>Math.PI-d||c<=-(Math.PI-d)?(u=-1,t=!0):u=-1;t?(G+=u*a,J+=n*a*m):(G+=g/(2*m)*u,J+=n*l);e.x!==f&&(G=e.x);e.y!==h&&(J=e.y);B.x=G+b*Math.cos(c);B.y=J-b*Math.sin(c);return B}});return z});I(b,"Gantt/PathfinderAlgorithms.js",[b["Core/Utilities.js"]],function(b){function z(c,b,n){n=n||0;var u=c.length-1;b-=1e-7;for(var x,e;n<=u;)if(x=u+n>>1,e=b-c[x].xMin,0<e)n=x+1;else if(0>
e)u=x-1;else return x;return 0<n?n-1:0}function A(c,b){for(var u=z(c,b.x+1)+1;u--;){var q;if(q=c[u].xMax>=b.x)q=c[u],q=b.x<=q.xMax&&b.x>=q.xMin&&b.y<=q.yMax&&b.y>=q.yMin;if(q)return u}return-1}function w(c){var b=[];if(c.length){b.push(["M",c[0].start.x,c[0].start.y]);for(var u=0;u<c.length;++u)b.push(["L",c[u].end.x,c[u].end.y])}return b}function y(b,x){b.yMin=c(b.yMin,x.yMin);b.yMax=v(b.yMax,x.yMax);b.xMin=c(b.xMin,x.xMin);b.xMax=v(b.xMax,x.xMax)}var p=b.extend,E=b.pick,v=Math.min,c=Math.max,r=
Math.abs;b=p(function(c,b,n){function q(a,d,f,c,b){a={x:a.x,y:a.y};a[d]=f[c||d]+(b||0);return a}function u(a,d,f){var c=r(d[f]-a[f+"Min"])>r(d[f]-a[f+"Max"]);return q(d,f,a,f+(c?"Max":"Min"),c?1:-1)}var e=[],m=E(n.startDirectionX,r(b.x-c.x)>r(b.y-c.y))?"x":"y",h=n.chartObstacles,a=A(h,c);n=A(h,b);if(-1<n){var g=h[n];n=u(g,b,m);g={start:n,end:b};var d=n}else d=b;-1<a&&(h=h[a],n=u(h,c,m),e.push({start:c,end:n}),n[m]>=c[m]===n[m]>=d[m]&&(m="y"===m?"x":"y",b=c[m]<b[m],e.push({start:n,end:q(n,m,h,m+(b?
"Max":"Min"),b?1:-1)}),m="y"===m?"x":"y"));c=e.length?e[e.length-1].end:c;n=q(c,m,d);e.push({start:c,end:n});m=q(n,"y"===m?"x":"y",d);e.push({start:n,end:m});e.push(g);return{path:w(e),obstacles:e}},{requiresObstacles:!0});return{fastAvoid:p(function(b,x,n){function q(a,k,d){var f,c=a.x<k.x?1:-1;if(a.x<k.x){var l=a;var b=k}else l=k,b=a;if(a.y<k.y){var e=a;var g=k}else e=k,g=a;for(f=0>c?v(z(B,b.x),B.length-1):0;B[f]&&(0<c&&B[f].xMin<=b.x||0>c&&B[f].xMax>=l.x);){if(B[f].xMin<=b.x&&B[f].xMax>=l.x&&B[f].yMin<=
g.y&&B[f].yMax>=e.y)return d?{y:a.y,x:a.x<k.x?B[f].xMin-1:B[f].xMax+1,obstacle:B[f]}:{x:a.x,y:a.y<k.y?B[f].yMin-1:B[f].yMax+1,obstacle:B[f]};f+=c}return k}function u(a,k,d,f,c){var l=c.soft,b=c.hard,e=f?"x":"y",g={x:k.x,y:k.y},C={x:k.x,y:k.y};c=a[e+"Max"]>=l[e+"Max"];l=a[e+"Min"]<=l[e+"Min"];var t=a[e+"Max"]>=b[e+"Max"];b=a[e+"Min"]<=b[e+"Min"];var h=r(a[e+"Min"]-k[e]),F=r(a[e+"Max"]-k[e]);d=10>r(h-F)?k[e]<d[e]:F<h;C[e]=a[e+"Min"];g[e]=a[e+"Max"];a=q(k,C,f)[e]!==C[e];k=q(k,g,f)[e]!==g[e];d=a?k?d:
!0:k?!1:d;d=l?c?d:!0:c?!1:d;return b?t?d:!0:t?!1:d}function e(a,k,b){if(a.x===k.x&&a.y===k.y)return[];var g=b?"x":"y",C=n.obstacleOptions.margin;var t={soft:{xMin:l,xMax:f,yMin:G,yMax:J},hard:n.hardBounds};var h=A(B,a);if(-1<h){h=B[h];t=u(h,a,k,b,t);y(h,n.hardBounds);var m=b?{y:a.y,x:h[t?"xMax":"xMin"]+(t?1:-1)}:{x:a.x,y:h[t?"yMax":"yMin"]+(t?1:-1)};var H=A(B,m);-1<H&&(H=B[H],y(H,n.hardBounds),m[g]=t?c(h[g+"Max"]-C+1,(H[g+"Min"]+h[g+"Max"])/2):v(h[g+"Min"]+C-1,(H[g+"Max"]+h[g+"Min"])/2),a.x===m.x&&
a.y===m.y?(d&&(m[g]=t?c(h[g+"Max"],H[g+"Max"])+1:v(h[g+"Min"],H[g+"Min"])-1),d=!d):d=!1);a=[{start:a,end:m}]}else g=q(a,{x:b?k.x:a.x,y:b?a.y:k.y},b),a=[{start:a,end:{x:g.x,y:g.y}}],g[b?"x":"y"]!==k[b?"x":"y"]&&(t=u(g.obstacle,g,k,!b,t),y(g.obstacle,n.hardBounds),t={x:b?g.x:g.obstacle[t?"xMax":"xMin"]+(t?1:-1),y:b?g.obstacle[t?"yMax":"yMin"]+(t?1:-1):g.y},b=!b,a=a.concat(e({x:g.x,y:g.y},t,b)));return a=a.concat(e(a[a.length-1].end,k,!b))}function m(a,k,d){var f=v(a.xMax-k.x,k.x-a.xMin)<v(a.yMax-k.y,
k.y-a.yMin);d=u(a,k,d,f,{soft:n.hardBounds,hard:n.hardBounds});return f?{y:k.y,x:a[d?"xMax":"xMin"]+(d?1:-1)}:{x:k.x,y:a[d?"yMax":"yMin"]+(d?1:-1)}}var h=E(n.startDirectionX,r(x.x-b.x)>r(x.y-b.y)),a=h?"x":"y",g=[],d=!1,t=n.obstacleMetrics,l=v(b.x,x.x)-t.maxWidth-10,f=c(b.x,x.x)+t.maxWidth+10,G=v(b.y,x.y)-t.maxHeight-10,J=c(b.y,x.y)+t.maxHeight+10,B=n.chartObstacles;var M=z(B,l);t=z(B,f);B=B.slice(M,t+1);if(-1<(t=A(B,x))){var p=m(B[t],x,b);g.push({end:x,start:p});x=p}for(;-1<(t=A(B,x));)M=0>x[a]-b[a],
p={x:x.x,y:x.y},p[a]=B[t][M?a+"Max":a+"Min"]+(M?1:-1),g.push({end:x,start:p}),x=p;b=e(b,x,h);b=b.concat(g.reverse());return{path:w(b),obstacles:b}},{requiresObstacles:!0}),straight:function(c,b){return{path:[["M",c.x,c.y],["L",b.x,b.y]],obstacles:[{start:c,end:b}]}},simpleConnect:b}});I(b,"Gantt/Pathfinder.js",[b["Gantt/Connection.js"],b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"],b["Gantt/PathfinderAlgorithms.js"]],function(b,
z,A,w,y,p,E){function v(a){var d=a.shapeArgs;return d?{xMin:d.x,xMax:d.x+d.width,yMin:d.y,yMax:d.y+d.height}:(d=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-d.width/2,xMax:a.plotX+d.width/2,yMin:a.plotY-d.height/2,yMax:a.plotY+d.height/2}:null}function c(d){for(var c=d.length,b=0,f,g,m=[],B=function(d,f,c){c=e(c,10);var k=d.yMax+c>f.yMin-c&&d.yMin-c<f.yMax+c,b=d.xMax+c>f.xMin-c&&d.xMin-c<f.xMax+c,l=k?d.xMin>f.xMax?d.xMin-f.xMax:f.xMin-d.xMax:Infinity,g=b?d.yMin>f.yMax?d.yMin-f.yMax:f.yMin-d.yMax:
Infinity;return b&&k?c?B(d,f,Math.floor(c/2)):Infinity:a(l,g)};b<c;++b)for(f=b+1;f<c;++f)g=B(d[b],d[f]),80>g&&m.push(g);m.push(80);return h(Math.floor(m.sort(function(a,d){return a-d})[Math.floor(m.length/10)]/2-1),1)}function r(a){if(a.options.pathfinder||a.series.reduce(function(a,d){d.options&&D(!0,d.options.connectors=d.options.connectors||{},d.options.pathfinder);return a||d.options&&d.options.pathfinder},!1))D(!0,a.options.connectors=a.options.connectors||{},a.options.pathfinder),n('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}
"";var u=p.addEvent,x=p.defined,n=p.error,q=p.extend,D=p.merge,e=p.pick,m=p.splat,h=Math.max,a=Math.min;q(w.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});var g=function(){function a(a){this.lineObstacles=this.group=this.connections=this.chartObstacleMetrics=this.chartObstacles=this.chart=void 0;this.init(a)}a.prototype.init=function(a){this.chart=
a;this.connections=[];u(a,"redraw",function(){this.pathfinder.update()})};a.prototype.update=function(a){var d=this.chart,f=this,c=f.connections;f.connections=[];d.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var k=a.options;k&&k.dependency&&(k.connect=k.dependency);var c;k=a.options&&a.options.connect&&m(a.options.connect);a.visible&&!1!==a.isInside&&k&&k.forEach(function(k){c=d.get("string"===typeof k?k:k.to);c instanceof y&&c.series.visible&&c.visible&&
!1!==c.isInside&&f.connections.push(new b(a,c,"string"===typeof k?{}:k))})})});for(var g=0,e,h,t=c.length,n=f.connections.length;g<t;++g){h=!1;for(e=0;e<n;++e)if(c[g].fromPoint===f.connections[e].fromPoint&&c[g].toPoint===f.connections[e].toPoint){f.connections[e].graphics=c[g].graphics;h=!0;break}h||c[g].destroy()}delete this.chartObstacles;delete this.lineObstacles;f.renderConnections(a)};a.prototype.renderConnections=function(a){a?this.chart.series.forEach(function(a){var d=function(){var d=a.chart.pathfinder;
(d&&d.connections||[]).forEach(function(d){d.fromPoint&&d.fromPoint.series===a&&d.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?d():a.pathfinderRemoveRenderEvent=u(a,"afterAnimate",d)}):this.connections.forEach(function(a){a.render()})};a.prototype.getChartObstacles=function(a){for(var d=[],f=this.chart.series,b=e(a.algorithmMargin,0),g,h=0,t=f.length;h<t;++h)if(f[h].visible&&!f[h].options.isInternal)for(var m=
0,n=f[h].points.length,k;m<n;++m)k=f[h].points[m],k.visible&&(k=v(k))&&d.push({xMin:k.xMin-b,xMax:k.xMax+b,yMin:k.yMin-b,yMax:k.yMax+b});d=d.sort(function(a,d){return a.xMin-d.xMin});x(a.algorithmMargin)||(g=a.algorithmMargin=c(d),d.forEach(function(a){a.xMin-=g;a.xMax+=g;a.yMin-=g;a.yMax+=g}));return d};a.prototype.getObstacleMetrics=function(a){for(var d=0,c=0,b,g,e=a.length;e--;)b=a[e].xMax-a[e].xMin,g=a[e].yMax-a[e].yMin,d<b&&(d=b),c<g&&(c=g);return{maxHeight:c,maxWidth:d}};a.prototype.getAlgorithmStartDirection=
function(a){var d="top"!==a.verticalAlign&&"bottom"!==a.verticalAlign;return"left"!==a.align&&"right"!==a.align?d?void 0:!1:d?!0:void 0};return a}();g.prototype.algorithms=E;A.Pathfinder=g;q(y.prototype,{getPathfinderAnchorPoint:function(a){var d=v(this);switch(a.align){case "right":var c="xMax";break;case "left":c="xMin"}switch(a.verticalAlign){case "top":var f="yMin";break;case "bottom":f="yMax"}return{x:c?d[c]:(d.xMin+d.xMax)/2,y:f?d[f]:(d.yMin+d.yMax)/2}},getRadiansToVector:function(a,c){var d;
x(c)||(d=v(this))&&(c={x:(d.xMin+d.xMax)/2,y:(d.yMin+d.yMax)/2});return Math.atan2(c.y-a.y,a.x-c.x)},getMarkerVector:function(a,c,b){var d=2*Math.PI,g=v(this),e=g.xMax-g.xMin,l=g.yMax-g.yMin,h=Math.atan2(l,e),t=!1;e/=2;var m=l/2,k=g.xMin+e;g=g.yMin+m;for(var C=k,F=g,n={},q=1,r=1;a<-Math.PI;)a+=d;for(;a>Math.PI;)a-=d;d=Math.tan(a);a>-h&&a<=h?(r=-1,t=!0):a>h&&a<=Math.PI-h?r=-1:a>Math.PI-h||a<=-(Math.PI-h)?(q=-1,t=!0):q=-1;t?(C+=q*e,F+=r*e*d):(C+=l/(2*d)*q,F+=r*m);b.x!==k&&(C=b.x);b.y!==g&&(F=b.y);n.x=
C+c*Math.cos(a);n.y=F-c*Math.sin(a);return n}});z.prototype.callbacks.push(function(a){!1!==a.options.connectors.enabled&&(r(a),this.pathfinder=new g(this),this.pathfinder.update(!0))});return g});I(b,"Series/XRangeSeries.js",[b["Core/Axis/Axis.js"],b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Color/Color.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,z,A,w,y,p){var E=w.parse;w=p.addEvent;var v=p.clamp,c=p.correctFloat,r=p.defined,u=p.find,x=p.isNumber,n=p.isObject,q=
p.merge,D=p.pick,e=A.Series,m=z.seriesTypes,h=m.column;z.seriesType("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;n(a)&&(a=a.amount);if(x(a)&&0<a)return c(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x",
"x2","y"],requireSorting:!1,animate:m.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:A.noop,buildKDTree:A.noop,init:function(){m.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function a(){c.series.forEach(function(a){var d=a.xAxis;a.xAxis=a.yAxis;a.yAxis=d})}var c=this.chart;a();var d=h.prototype.getColumnMetrics.call(this);a();return d},cropData:function(a,c,d,b){c=e.prototype.cropData.call(this,this.x2Data,c,d,b);
c.xData=a.slice(c.start,c.end);return c},findPointIndex:function(a){var c=this.cropped,d=this.cropStart,b=this.points,e=a.id;if(e)var f=(f=u(b,function(a){return a.id===e}))?f.index:void 0;"undefined"===typeof f&&(f=(f=u(b,function(d){return d.x===a.x&&d.x2===a.x2&&!d.touched}))?f.index:void 0);c&&x(f)&&x(d)&&f>=d&&(f-=d);return f},translatePoint:function(a){var c=this.xAxis,d=this.yAxis,b=this.columnMetrics,e=this.options,f=e.minPointLength||0,h=a.plotX,m=D(a.x2,a.x+(a.len||0)),B=c.translate(m,0,
0,0,1);m=Math.abs(B-h);var u=this.chart.inverted,p=D(e.borderWidth,1)%2/2,H=b.offset,k=Math.round(b.width);f&&(f-=m,0>f&&(f=0),h-=f/2,B+=f/2);h=Math.max(h,-10);B=v(B,-10,c.len+10);r(a.options.pointWidth)&&(H-=(Math.ceil(a.options.pointWidth)-k)/2,k=Math.ceil(a.options.pointWidth));e.pointPlacement&&x(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,e.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(h,B))+p,y:Math.floor(a.plotY+H)+p,width:Math.round(Math.abs(B-h)),height:k,r:this.options.borderRadius};
e=a.shapeArgs.x;f=e+a.shapeArgs.width;0>e||f>c.len?(e=v(e,0,c.len),f=v(f,0,c.len),B=f-e,a.dlBox=q(a.shapeArgs,{x:e,width:f-e,centerX:B?B/2:null})):a.dlBox=null;e=a.tooltipPos;f=u?1:0;B=u?0:1;b=this.columnMetrics?this.columnMetrics.offset:-b.width/2;e[f]=v(e[f]+m/2*(c.reversed?-1:1)*(u?-1:1),0,c.len-1);e[B]=v(e[B]+(u?-1:1)*b,0,d.len-1);if(b=a.partialFill)n(b)&&(b=b.amount),x(b)||(b=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},h=Math.max(Math.round(m*
b+a.plotX-h),0),a.clipRectArgs={x:c.reversed?d.x+m-h:d.x,y:d.y,width:h,height:d.height}},translate:function(){h.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,c){var d=this.options,b=this.chart.renderer,e=a.graphic,f=a.shapeType,g=a.shapeArgs,h=a.partShapeArgs,m=a.clipRectArgs,r=a.partialFill,u=d.stacking&&!d.borderRadius,H=a.state,k=d.states[H||"normal"]||{},C="undefined"===typeof H?"attr":c;H=this.pointAttribs(a,H);k=
D(this.chart.options.chart.animation,k.animation);if(a.isNull||!1===a.visible)e&&(a.graphic=e.destroy());else{if(e)e.rect[c](g);else a.graphic=e=b.g("point").addClass(a.getClassName()).add(a.group||this.group),e.rect=b[f](q(g)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);h&&(e.partRect?(e.partRect[c](q(h)),e.partialClipRect[c](q(m))):(e.partialClipRect=b.clipRect(m.x,m.y,m.width,m.height),e.partRect=b[f](h).addClass("highcharts-partfill-overlay").add(e).clip(e.partialClipRect)));
this.chart.styledMode||(e.rect[c](H,k).shadow(d.shadow,null,u),h&&(n(r)||(r={}),n(d.partialFill)&&(r=q(d.partialFill,r)),a=r.fill||E(H.fill).brighten(-.3).get()||E(a.color||this.color).brighten(-.3).get(),H.fill=a,e.partRect[C](H,k).shadow(d.shadow,null,u)))}},drawPoints:function(){var a=this,c=a.getAnimationVerb();a.points.forEach(function(d){a.drawPoint(d,c)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=
this.series;if(a.options.colorByPoint&&!this.options.color){var c=a.options.colors||a.chart.options.colors;var d=this.y%(c?c.length:a.chart.options.chart.colorCount);c=c&&c[d];a.chart.styledMode||(this.color=c);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){y.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){y.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},
getLabelConfig:function(){var a=y.prototype.getLabelConfig.call(this),c=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=c&&c[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});w(b,"afterGetSeriesExtremes",function(){var a=this.series,c;if(this.isXAxis){var d=D(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>d&&(d=a,c=!0)})});c&&(this.dataMax=d)}});""});I(b,
"Series/GanttSeries.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Utilities.js"]],function(b,z,A,w){var y=w.isNumber;A=w.merge;var p=w.pick,E=w.splat,v=b.seriesTypes.xrange;b.seriesType("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var c=this.series,b=c.chart.tooltip,u=c.xAxis,x=c.tooltipOptions.dateTimeLabelFormats,n=u.options.startOfWeek,
q=c.tooltipOptions,p=q.xDateFormat,e=this.options.milestone,m="<b>"+(this.name||this.yCategory)+"</b>";if(q.pointFormat)return this.tooltipFormatter(q.pointFormat);p||(p=E(b.getDateFormat(u.closestPointRange,this.start,n,x))[0]);b=c.chart.time.dateFormat(p,this.start);c=c.chart.time.dateFormat(p,this.end);m+="<br/>";return e?m+(b+"<br/>"):m+("Start: "+b+"<br/>End: ")+(c+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",
align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(c){v.prototype.translatePoint.call(this,c);if(c.options.milestone){var b=c.shapeArgs;var u=b.height;c.shapeArgs={x:b.x-u/2,y:b.y,width:u,height:u}}},drawPoint:function(c,b){var u=this.options,r=this.chart.renderer,n=c.shapeArgs,q=c.plotY,p=c.graphic,e=c.selected&&"select",m=u.stacking&&!u.borderRadius;if(c.options.milestone)if(y(q)&&null!==c.y&&!1!==c.visible){n=
r.symbols.diamond(n.x,n.y,n.width,n.height);if(p)p[b]({d:n});else c.graphic=r.path(n).addClass(c.getClassName(),!0).add(c.group||this.group);this.chart.styledMode||c.graphic.attr(this.pointAttribs(c,e)).shadow(u.shadow,null,m)}else p&&(c.graphic=p.destroy());else v.prototype.drawPoint.call(this,c,b)},setData:z.Series.prototype.setData,setGanttPointAliases:function(c){function b(b,r){"undefined"!==typeof r&&(c[b]=r)}b("x",p(c.start,c.x));b("x2",p(c.end,c.x2));b("partialFill",p(c.completed,c.partialFill))}},
A(v.prototype.pointClass.prototype,{applyOptions:function(c,b){c=v.prototype.pointClass.prototype.applyOptions.call(this,c,b);z.seriesTypes.gantt.prototype.setGanttPointAliases(c);return c},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});I(b,"Core/Chart/GanttChart.js",[b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,z,A){var w=A.getOptions,y=A.isArray,
p=A.merge,E=A.splat;z.ganttChart=function(v,c,r){var u="string"===typeof v||v.nodeName,x=c.series,n=w(),q,z=c;c=arguments[u?1:0];y(c.xAxis)||(c.xAxis=[c.xAxis||{},{}]);c.xAxis=c.xAxis.map(function(c,b){1===b&&(q=0);return p(n.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:q},c,{type:"datetime"})});c.yAxis=E(c.yAxis||{}).map(function(c){return p(n.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:c.categories?c.type:"treegrid"},c)});c.series=null;c=p(!0,{chart:{type:"gantt"},title:{text:null},
legend:{enabled:!1},navigator:{series:{type:"gantt"},yAxis:{type:"category"}}},c,{isGantt:!0});c.series=z.series=x;return u?new b(v,c,r):new b(c,c)}});I(b,"Core/Axis/ScrollbarAxis.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,z){var A=z.addEvent,w=z.defined,y=z.pick;return function(){function p(){}p.compose=function(p,v){A(p,"afterInit",function(){var c=this;c.options&&c.options.scrollbar&&c.options.scrollbar.enabled&&(c.options.scrollbar.vertical=!c.horiz,c.options.startOnTick=c.options.endOnTick=
!1,c.scrollbar=new v(c.chart.renderer,c.options.scrollbar,c.chart),A(c.scrollbar,"changed",function(r){var u=y(c.options&&c.options.min,c.min),p=y(c.options&&c.options.max,c.max),n=w(c.dataMin)?Math.min(u,c.min,c.dataMin):u,q=(w(c.dataMax)?Math.max(p,c.max,c.dataMax):p)-n;w(u)&&w(p)&&(c.horiz&&!c.reversed||!c.horiz&&c.reversed?(u=n+q*this.to,n+=q*this.from):(u=n+q*(1-this.from),n+=q*(1-this.to)),y(this.options.liveRedraw,b.svg&&!b.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===r.DOMType||!w(r.DOMType)?
c.setExtremes(n,u,!0,"mousemove"!==r.DOMType,r):this.setRange(this.from,this.to))}))});A(p,"afterRender",function(){var c=Math.min(y(this.options.min,this.min),this.min,y(this.dataMin,this.min)),b=Math.max(y(this.options.max,this.max),this.max,y(this.dataMax,this.max)),u=this.scrollbar,p=this.axisTitleMargin+(this.titleOffset||0),n=this.chart.scrollbarsOffsets,q=this.options.margin||0;u&&(this.horiz?(this.opposite||(n[1]+=p),u.position(this.left,this.top+this.height+2+n[1]-(this.opposite?q:0),this.width,
this.height),this.opposite||(n[1]+=q),p=1):(this.opposite&&(n[0]+=p),u.position(this.left+this.width+2+n[0]-(this.opposite?0:q),this.top,this.width,this.height),this.opposite&&(n[0]+=q),p=0),n[p]+=u.size+u.options.margin,isNaN(c)||isNaN(b)||!w(this.min)||!w(this.max)||this.min===this.max?u.setRange(0,1):(n=(this.min-c)/(b-c),c=(this.max-c)/(b-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?u.setRange(n,c):u.setRange(1-c,1-n)))});A(p,"afterGetOffset",function(){var c=this.horiz?2:1,b=this.scrollbar;
b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=b.size+b.options.margin)})};return p}()});I(b,"Core/Scrollbar.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Axis/ScrollbarAxis.js"],b["Core/Utilities.js"],b["Core/Options.js"]],function(b,z,A,w,y){var p=w.addEvent,E=w.correctFloat,v=w.defined,c=w.destroyObjectProperties,r=w.fireEvent,u=w.merge,x=w.pick,n=w.removeEvent;w=y.defaultOptions;var q=z.hasTouch,D=z.isTouchDevice,e=z.swapXY=function(c,b){b&&c.forEach(function(a){for(var c=
a.length,d,b=0;b<c;b+=2)d=a[b+1],"number"===typeof d&&(a[b+1]=a[b+2],a[b+2]=d)});return c};y=function(){function b(b,a,c){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=c;this.options=a;this.renderer=c.renderer;
this.init(b,a,c)}b.prototype.addEvents=function(){var b=this.options.inverted?[1,0]:[0,1],a=this.scrollbarButtons,c=this.scrollbarGroup.element,d=this.track.element,e=this.mouseDownHandler.bind(this),l=this.mouseMoveHandler.bind(this),f=this.mouseUpHandler.bind(this);b=[[a[b[0]].element,"click",this.buttonToMinClick.bind(this)],[a[b[1]].element,"click",this.buttonToMaxClick.bind(this)],[d,"click",this.trackClick.bind(this)],[c,"mousedown",e],[c.ownerDocument,"mousemove",l],[c.ownerDocument,"mouseup",
f]];q&&b.push([c,"touchstart",e],[c.ownerDocument,"touchmove",l],[c.ownerDocument,"touchend",f]);b.forEach(function(a){p.apply(null,a)});this._events=b};b.prototype.buttonToMaxClick=function(b){var a=(this.to-this.from)*x(this.options.step,.2);this.updatePosition(this.from+a,this.to+a);r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.buttonToMinClick=function(b){var a=E(this.to-this.from)*x(this.options.step,.2);this.updatePosition(E(this.from-a),E(this.to-
a));r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.cursorToScrollbarPosition=function(b){var a=this.options;a=a.minWidth>this.calculatedWidth?a.minWidth:0;return{chartX:(b.chartX-this.x-this.xOffset)/(this.barWidth-a),chartY:(b.chartY-this.y-this.yOffset)/(this.barWidth-a)}};b.prototype.destroy=function(){var b=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&
(this[a]=this[a].destroy())},this);b&&this===b.scrollbar&&(b.scrollbar=null,c(b.scrollbarButtons))};b.prototype.drawScrollbarButton=function(b){var a=this.renderer,c=this.scrollbarButtons,d=this.options,h=this.size;var l=a.g().add(this.group);c.push(l);l=a.rect().addClass("highcharts-scrollbar-button").add(l);this.chart.styledMode||l.attr({stroke:d.buttonBorderColor,"stroke-width":d.buttonBorderWidth,fill:d.buttonBackgroundColor});l.attr(l.crisp({x:-.5,y:-.5,width:h+1,height:h+1,r:d.buttonBorderRadius},
l.strokeWidth()));l=a.path(e([["M",h/2+(b?-1:1),h/2-3],["L",h/2+(b?-1:1),h/2+3],["L",h/2+(b?2:-2),h/2]],d.vertical)).addClass("highcharts-scrollbar-arrow").add(c[b]);this.chart.styledMode||l.attr({fill:d.buttonArrowColor})};b.prototype.init=function(c,a,e){this.scrollbarButtons=[];this.renderer=c;this.userOptions=a;this.options=u(b.defaultOptions,a);this.chart=e;this.size=x(this.options.size,this.options.height);a.enabled&&(this.render(),this.addEvents())};b.prototype.mouseDownHandler=function(b){b=
this.chart.pointer.normalize(b);b=this.cursorToScrollbarPosition(b);this.chartX=b.chartX;this.chartY=b.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};b.prototype.mouseMoveHandler=function(b){var a=this.chart.pointer.normalize(b),c=this.options.vertical?"chartY":"chartX",d=this.initPositions||[];!this.grabbedCenter||b.touches&&0===b.touches[0][c]||(a=this.cursorToScrollbarPosition(a)[c],c=this[c],c=a-c,this.hasDragged=!0,this.updatePosition(d[0]+c,d[1]+c),this.hasDragged&&r(this,
"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};b.prototype.mouseUpHandler=function(b){this.hasDragged&&r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};b.prototype.position=function(b,a,c,d){var e=this.options.vertical,g=0,f=this.rendered?"animate":"attr";this.x=b;this.y=a+this.trackBorderWidth;this.width=c;this.xOffset=this.height=d;this.yOffset=g;e?
(this.width=this.yOffset=c=g=this.size,this.xOffset=a=0,this.barWidth=d-2*c,this.x=b+=this.options.margin):(this.height=this.xOffset=d=a=this.size,this.barWidth=c-2*d,this.y+=this.options.margin);this.group[f]({translateX:b,translateY:this.y});this.track[f]({width:c,height:d});this.scrollbarButtons[1][f]({translateX:e?0:c-a,translateY:e?d-g:0})};b.prototype.removeEvents=function(){this._events.forEach(function(b){n.apply(null,b)});this._events.length=0};b.prototype.render=function(){var b=this.renderer,
a=this.options,c=this.size,d=this.chart.styledMode,m;this.group=m=b.g("scrollbar").attr({zIndex:a.zIndex,translateY:-99999}).add();this.track=b.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:a.trackBorderRadius||0,height:c,width:c}).add(m);d||this.track.attr({fill:a.trackBackgroundColor,stroke:a.trackBorderColor,"stroke-width":a.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=b.g().add(m);this.scrollbar=
b.rect().addClass("highcharts-scrollbar-thumb").attr({height:c,width:c,r:a.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=b.path(e([["M",-3,c/4],["L",-3,2*c/3],["M",0,c/4],["L",0,2*c/3],["M",3,c/4],["L",3,2*c/3]],a.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);d||(this.scrollbar.attr({fill:a.barBackgroundColor,stroke:a.barBorderColor,"stroke-width":a.barBorderWidth}),this.scrollbarRifles.attr({stroke:a.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=
this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};b.prototype.setRange=function(b,a){var c=this.options,d=c.vertical,e=c.minWidth,l=this.barWidth,f,h=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(v(l)){b=Math.max(b,0);var m=Math.ceil(l*b);this.calculatedWidth=f=E(l*Math.min(a,1)-m);f<e&&(m=(l-e+f)*b,f=e);e=Math.floor(m+
this.xOffset+this.yOffset);l=f/2-.5;this.from=b;this.to=a;d?(this.scrollbarGroup[h]({translateY:e}),this.scrollbar[h]({height:f}),this.scrollbarRifles[h]({translateY:l}),this.scrollbarTop=e,this.scrollbarLeft=0):(this.scrollbarGroup[h]({translateX:e}),this.scrollbar[h]({width:f}),this.scrollbarRifles[h]({translateX:l}),this.scrollbarLeft=e,this.scrollbarTop=0);12>=f?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===c.showFull&&(0>=b&&1<=a?this.group.hide():this.group.show());this.rendered=
!0}};b.prototype.trackClick=function(b){var a=this.chart.pointer.normalize(b),c=this.to-this.from,d=this.y+this.scrollbarTop,e=this.x+this.scrollbarLeft;this.options.vertical&&a.chartY>d||!this.options.vertical&&a.chartX>e?this.updatePosition(this.from+c,this.to+c):this.updatePosition(this.from-c,this.to-c);r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.update=function(b){this.destroy();this.init(this.chart.renderer,u(!0,this.options,b),this.chart)};b.prototype.updatePosition=
function(b,a){1<a&&(b=E(1-E(a-b)),a=1);0>b&&(a=E(a-b),b=0);this.from=b;this.to=a};b.defaultOptions={height:D?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return b}();z.Scrollbar||
(w.scrollbar=u(!0,y.defaultOptions,w.scrollbar),z.Scrollbar=y,A.compose(b,y));return z.Scrollbar});I(b,"Extensions/RangeSelector.js",[b["Core/Axis/Axis.js"],b["Core/Chart/Chart.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Utilities.js"]],function(b,z,A,w,y,p){var E=w.defaultOptions,v=p.addEvent,c=p.createElement,r=p.css,u=p.defined,x=p.destroyObjectProperties,n=p.discardElement,q=p.extend,D=p.fireEvent,e=p.isNumber,m=p.merge,h=p.objectEach,a=p.pick,g=
p.pInt,d=p.splat;q(E,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});E.lang=m(E.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var t=function(){function l(a){this.buttons=void 0;this.buttonOptions=l.prototype.defaultButtons;this.options=void 0;this.chart=a;this.init(a)}l.prototype.clickButton=
function(c,g){var f=this.chart,l=this.buttonOptions[c],h=f.xAxis[0],m=f.scroller&&f.scroller.getUnionExtremes()||h||{},n=m.dataMin,k=m.dataMax,C=h&&Math.round(Math.min(h.max,a(k,h.max))),F=l.type;m=l._range;var q,t=l.dataGrouping;if(null!==n&&null!==k){f.fixedRange=m;t&&(this.forcedDataGrouping=!0,b.prototype.setDataGrouping.call(h||{chart:this.chart},t,!1),this.frozenStates=l.preserveDataGrouping);if("month"===F||"year"===F)if(h){F={range:l,max:C,chart:f,dataMin:n,dataMax:k};var p=h.minFromRange.call(F);
e(F.newMax)&&(C=F.newMax)}else m=l;else if(m)p=Math.max(C-m,n),C=Math.min(p+m,k);else if("ytd"===F)if(h)"undefined"===typeof k&&(n=Number.MAX_VALUE,k=Number.MIN_VALUE,f.series.forEach(function(a){a=a.xData;n=Math.min(a[0],n);k=Math.max(a[a.length-1],k)}),g=!1),C=this.getYTDExtremes(k,n,f.time.useUTC),p=q=C.min,C=C.max;else{this.deferredYTDClick=c;return}else"all"===F&&h&&(p=n,C=k);u(p)&&(p+=l._offsetMin);u(C)&&(C+=l._offsetMax);this.setSelected(c);if(h)h.setExtremes(p,C,a(g,1),null,{trigger:"rangeSelectorButton",
rangeSelectorButton:l});else{var r=d(f.options.xAxis)[0];var S=r.range;r.range=m;var G=r.min;r.min=q;v(f,"load",function(){r.range=S;r.min=G})}}};l.prototype.setSelected=function(a){this.selected=this.options.selected=a};l.prototype.init=function(a){var b=this,c=a.options.rangeSelector,d=c.buttons||b.defaultButtons.slice(),e=c.selected,f=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&D(a,"blur");c&&c.blur&&D(c,"blur")};b.chart=a;b.options=c;b.buttons=[];b.buttonOptions=d;this.unMouseDown=v(a.container,
"mousedown",f);this.unResize=v(a,"resize",f);d.forEach(b.computeButtonRange);"undefined"!==typeof e&&d[e]&&this.clickButton(e,!1);v(a,"load",function(){a.xAxis&&a.xAxis[0]&&v(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})};l.prototype.updateButtonStates=function(){var a=this,b=this.chart,c=b.xAxis[0],d=Math.round(c.max-c.min),g=!c.hasVisibleSeries,
l=b.scroller&&b.scroller.getUnionExtremes()||c,h=l.dataMin,k=l.dataMax;b=a.getYTDExtremes(k,h,b.time.useUTC);var C=b.min,m=b.max,n=a.selected,q=e(n),t=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,e){var f=b._range,l=b.type,F=b.count||1,B=u[e],p=0,r=b._offsetMax-b._offsetMin;b=e===n;var H=f>k-h,J=f<c.minRange,P=!1,x=!1;f=f===d;("month"===l||"year"===l)&&d+36E5>=864E5*{month:28,year:365}[l]*F-r&&d-36E5<=864E5*{month:31,year:366}[l]*F+r?f=!0:"ytd"===l?(f=m-C+r===d,P=!b):
"all"===l&&(f=c.max-c.min>=k-h,x=!b&&q&&f);l=!t&&(H||J||x||g);F=b&&f||f&&!q&&!P||b&&a.frozenStates;l?p=3:F&&(q=!0,p=2);B.state!==p&&(B.setState(p),0===p&&n===e&&a.setSelected(null))})};l.prototype.computeButtonRange=function(b){var c=b.type,d=b.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[c])b._range=e[c]*d;else if("month"===c||"year"===c)b._range=864E5*{month:30,year:365}[c]*d;b._offsetMin=a(b.offsetMin,0);b._offsetMax=a(b.offsetMax,0);b._range+=b._offsetMax-
b._offsetMin};l.prototype.setInputValue=function(a,b){var c=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];u(b)&&(e.previousValue=e.HCTime,e.HCTime=b);e.value=d.dateFormat(c.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",e.HCTime)})};l.prototype.showInput=function(a){var b=this.inputGroup,c=this[a+"DateBox"];r(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-
2+"px",border:"2px solid silver"})};l.prototype.hideInput=function(a){r(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)};l.prototype.defaultInputDateParser=function(a,b){var c=new Date;return A.isSafari?Date.parse(a.split(" ").join("T")):b?Date.parse(a+"Z"):Date.parse(a)-6E4*c.getTimezoneOffset()};l.prototype.drawInput=function(a){function b(){var a=F.value,b=f.xAxis[0];var c=f.scroller&&f.scroller.xAxis?f.scroller.xAxis:b;var k=c.dataMin,l=c.dataMax;c=(n.inputDateParser||
u)(a,f.time.useUTC);c!==F.previousValue&&(F.previousValue=c,e(c)||(c=a.split("-"),c=Date.UTC(g(c[0]),g(c[1])-1,g(c[2]))),e(c)&&(f.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),C?c>d.maxInput.HCTime?c=void 0:c<k&&(c=k):c<d.minInput.HCTime?c=void 0:c>l&&(c=l),"undefined"!==typeof c&&b.setExtremes(C?c:b.min,C?b.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,f=d.chart,l=f.renderer.style||{},h=f.renderer,n=f.options.rangeSelector,k=d.div,C="min"===a,F,t,p=this.inputGroup,u=this.defaultInputDateParser;
this[a+"Label"]=t=h.label(E.lang[C?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(p);p.offset+=t.width+5;this[a+"DateBox"]=h=h.label("",p.offset).addClass("highcharts-range-input").attr({padding:2,width:n.inputBoxWidth||90,height:n.inputBoxHeight||17,"text-align":"center"}).on("click",function(){d.showInput(a);d[a+"Input"].focus()});f.styledMode||h.attr({stroke:n.inputBoxBorderColor||"#cccccc","stroke-width":1});h.add(p);p.offset+=
h.width+(C?10:0);this[a+"Input"]=F=c("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:f.plotTop+"px"},k);f.styledMode||(t.css(m(l,n.labelStyle)),h.css(m({color:"#333333"},l,n.inputStyle)),r(F,q({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:l.fontSize,fontFamily:l.fontFamily,top:"-9999em"},n.inputStyle)));F.onfocus=function(){d.showInput(a)};F.onblur=function(){F===A.doc.activeElement&&b();d.hideInput(a);F.blur()};F.onchange=b;F.onkeypress=
function(a){13===a.keyCode&&b()}};l.prototype.getPosition=function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};l.prototype.getYTDExtremes=function(a,b,c){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);c=c?d.Date.UTC(f,0,1):+new d.Date(f,0,1);b=Math.max(b||0,c);e=e.getTime();return{max:Math.min(a||e,e),min:b}};l.prototype.render=function(b,d){var e=this,f=e.chart,
l=f.renderer,g=f.container,h=f.options,k=h.exporting&&!1!==h.exporting.enabled&&h.navigation&&h.navigation.buttonOptions,C=E.lang,m=e.div,n=h.rangeSelector,q=a(h.chart.style&&h.chart.style.zIndex,0)+1;h=n.floating;var t=e.buttons;m=e.inputGroup;var p=n.buttonTheme,u=n.buttonPosition,r=n.inputPosition,x=n.inputEnabled,y=p&&p.states,v=f.plotLeft,w=e.buttonGroup,z,A=e.options.verticalAlign,D=f.legend,G=D&&D.options,I=u.y,O=r.y,K=f.hasLoaded,Q=K?"animate":"attr",N=0,L=0;if(!1!==n.enabled){e.rendered||
(e.group=z=l.g("range-selector-group").attr({zIndex:7}).add(),e.buttonGroup=w=l.g("range-selector-buttons").add(z),e.zoomText=l.text(C.rangeSelectorZoom,0,15).add(w),f.styledMode||(e.zoomText.css(n.labelStyle),p["stroke-width"]=a(p["stroke-width"],0)),e.buttonOptions.forEach(function(a,b){t[b]=l.button(a.text,0,0,function(c){var d=a.events&&a.events.click,k;d&&(k=d.call(a,c));!1!==k&&e.clickButton(b);e.isActive=!0},p,y&&y.hover,y&&y.select,y&&y.disabled).attr({"text-align":"center"}).add(w)}),!1!==
x&&(e.div=m=c("div",null,{position:"relative",height:0,zIndex:q}),g.parentNode.insertBefore(m,g),e.inputGroup=m=l.g("input-group").add(z),m.offset=0,e.drawInput("min"),e.drawInput("max")));e.zoomText[Q]({x:a(v+u.x,v)});var R=a(v+u.x,v)+e.zoomText.getBBox().width+5;e.buttonOptions.forEach(function(b,c){t[c][Q]({x:R});R+=t[c].width+a(n.buttonSpacing,5)});v=f.plotLeft-f.spacing[3];e.updateButtonStates();k&&this.titleCollision(f)&&"top"===A&&"right"===u.align&&u.y+w.getBBox().height-12<(k.y||0)+k.height&&
(N=-40);g=u.x-f.spacing[3];"right"===u.align?g+=N-v:"center"===u.align&&(g-=v/2);w.align({y:u.y,width:w.getBBox().width,align:u.align,x:g},!0,f.spacingBox);e.group.placed=K;e.buttonGroup.placed=K;!1!==x&&(N=k&&this.titleCollision(f)&&"top"===A&&"right"===r.align&&r.y-m.getBBox().height-12<(k.y||0)+k.height+f.spacing[0]?-40:0,"left"===r.align?g=v:"right"===r.align&&(g=-Math.max(f.axisOffset[1],-N)),m.align({y:r.y,width:m.getBBox().width,align:r.align,x:r.x+g-2},!0,f.spacingBox),k=m.alignAttr.translateX+
m.alignOptions.x-N+m.getBBox().x+2,g=m.alignOptions.width,C=w.alignAttr.translateX+w.getBBox().x,v=w.getBBox().width+20,(r.align===u.align||C+v>k&&k+g>C&&I<O+m.getBBox().height)&&m.attr({translateX:m.alignAttr.translateX+(f.axisOffset[1]>=-N?0:-N),translateY:m.alignAttr.translateY+w.getBBox().height+10}),e.setInputValue("min",b),e.setInputValue("max",d),e.inputGroup.placed=K);e.group.align({verticalAlign:A},!0,f.spacingBox);b=e.group.getBBox().height+20;d=e.group.alignAttr.translateY;"bottom"===A&&
(D=G&&"bottom"===G.verticalAlign&&G.enabled&&!G.floating?D.legendHeight+a(G.margin,10):0,b=b+D-20,L=d-b-(h?0:n.y)-(f.titleOffset?f.titleOffset[2]:0)-10);if("top"===A)h&&(L=0),f.titleOffset&&f.titleOffset[0]&&(L=f.titleOffset[0]),L+=f.margin[0]-f.spacing[0]||0;else if("middle"===A)if(O===I)L=0>O?d+void 0:d;else if(O||I)L=0>O||0>I?L-Math.min(O,I):d-b+NaN;e.group.translate(n.x,n.y+Math.floor(L));!1!==x&&(e.minInput.style.marginTop=e.group.translateY+"px",e.maxInput.style.marginTop=e.group.translateY+
"px");e.rendered=!0}};l.prototype.getHeight=function(){var a=this.options,b=this.group,c=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+c:0;b=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(b);return a};l.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};l.prototype.update=function(a){var b=this.chart;m(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()};l.prototype.destroy=
function(){var a=this,b=a.minInput,c=a.maxInput;a.unMouseDown();a.unResize();x(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);h(a,function(b,c){b&&"chart"!==c&&(b instanceof y?b.destroy():b instanceof window.HTMLElement&&n(b));b!==l.prototype[c]&&(a[c]=null)},this)};return l}();t.prototype.defaultButtons=[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},
{type:"all",text:"All"}];b.prototype.minFromRange=function(){var b=this.range,c=b.type,d=this.max,g=this.chart.time,h=function(a,b){var d="year"===c?"FullYear":"Month",e=new g.Date(a),k=g.get(d,e);g.set(d,e,k+b);k===g.get(d,e)&&g.set("Date",e,0);return e.getTime()-a};if(e(b)){var m=d-b;var n=b}else m=d+h(d,-b.count),this.chart&&(this.chart.fixedRange=d-m);var q=a(this.dataMin,Number.MIN_VALUE);e(m)||(m=q);m<=q&&(m=q,"undefined"===typeof n&&(n=h(m,b.count)),this.newMax=Math.min(m+n,this.dataMax));
e(d)||(m=void 0);return m};A.RangeSelector||(v(z,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new t(this))}),v(z,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(e(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=
!0)))}),v(z,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!u(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new t(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=
!0)}),v(z,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),v(z,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),z.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();g=a.legend;l=null===d||void 0===d?void 0:d.options.verticalAlign;
e(c.min)&&d.render(c.min,c.max);d&&g.display&&"top"===l&&l===g.options.verticalAlign&&(h=m(a.spacingBox),h.y="vertical"===g.options.layout?a.plotTop:h.y+d.getHeight(),g.group.placed=!1,g.align(h))}var c,d=a.rangeSelector,g,h,l;if(d){var n=v(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var k=v(a,"redraw",b);b()}v(a,"destroy",function(){d&&(k(),n())})}),A.RangeSelector=t);return A.RangeSelector});I(b,"Core/Axis/NavigatorAxis.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,
z){var A=b.isTouchDevice,w=z.addEvent,y=z.correctFloat,p=z.defined,E=z.isNumber,v=z.pick,c=function(){function b(b){this.axis=b}b.prototype.destroy=function(){this.axis=void 0};b.prototype.toFixedRange=function(b,c,n,q){var r=this.axis,e=r.chart;e=e&&e.fixedRange;var m=(r.pointRange||0)/2;b=v(n,r.translate(b,!0,!r.horiz));c=v(q,r.translate(c,!0,!r.horiz));r=e&&(c-b)/e;p(n)||(b=y(b+m));p(q)||(c=y(c-m));.7<r&&1.3>r&&(q?b=c-e:c=b+e);E(b)&&E(c)||(b=c=void 0);return{min:b,max:c}};return b}();return function(){function b(){}
b.compose=function(b){b.keepProps.push("navigatorAxis");w(b,"init",function(){this.navigatorAxis||(this.navigatorAxis=new c(this))});w(b,"zoom",function(b){var c=this.chart.options,q=c.navigator,r=this.navigatorAxis,e=c.chart.pinchType,m=c.rangeSelector;c=c.chart.zoomType;this.isXAxis&&(q&&q.enabled||m&&m.enabled)&&("y"===c?b.zoomed=!1:(!A&&"xy"===c||A&&"xy"===e)&&this.options.range&&(q=r.previousZoom,p(b.newMin)?r.previousZoom=[this.min,this.max]:q&&(b.newMin=q[0],b.newMax=q[1],r.previousZoom=void 0)));
"undefined"!==typeof b.zoomed&&b.preventDefault()})};b.AdditionsClass=c;return b}()});I(b,"Core/Navigator.js",[b["Core/Axis/Axis.js"],b["Core/Series/Series.js"],b["Core/Chart/Chart.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Series/LineSeries.js"],b["Core/Axis/NavigatorAxis.js"],b["Core/Options.js"],b["Core/Scrollbar.js"],b["Core/Utilities.js"]],function(b,z,A,w,y,p,E,v,c,r){w=w.parse;var u=y.hasTouch,x=y.isTouchDevice,n=v.defaultOptions,q=r.addEvent,D=r.clamp,e=r.correctFloat,m=r.defined,
h=r.destroyObjectProperties,a=r.erase,g=r.extend,d=r.find,t=r.isArray,l=r.isNumber,f=r.merge,G=r.pick,J=r.removeEvent,B=r.splat,I=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,l);if(b.length)return Math[a].apply(0,b)};z="undefined"===typeof z.seriesTypes.areaspline?"line":"areaspline";g(n,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",
borderColor:"#999999"},maskFill:w("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:z,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",
className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});
y.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=(e&&e.width||0)/2;b=Math.round(a/3)+.5;e=e&&e.height||0;return[["M",-a-1,.5],["L",a,.5],["L",a,e+.5],["L",-a-1,e+.5],["L",-a-1,.5],["M",-b,4],["L",-b,e-3],["M",b-1,4],["L",b-1,e-3]]};var K=function(){function p(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=
this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}p.prototype.drawHandle=function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-e/2-1)})};p.prototype.drawOutline=function(a,b,c,d){var e=this.navigatorOptions.maskInside,
k=this.outline.strokeWidth(),f=k/2,g=k%2/2;k=this.outlineHeight;var h=this.scrollbarHeight||0,l=this.size,m=this.left-h,C=this.top;c?(m-=f,c=C+b+g,b=C+a+g,g=[["M",m+k,C-h-g],["L",m+k,c],["L",m,c],["L",m,b],["L",m+k,b],["L",m+k,C+l+h]],e&&g.push(["M",m+k,c-f],["L",m+k,b+f])):(a+=m+h-g,b+=m+h-g,C+=f,g=[["M",m,C],["L",a,C],["L",a,C+k],["L",b,C+k],["L",b,C],["L",m+l+2*h,C]],e&&g.push(["M",a-f,C],["L",b+f,C]));this.outline[d]({d:g})};p.prototype.drawMasks=function(a,b,c,d){var e=this.left,k=this.top,f=
this.height;if(c){var g=[e,e,e];var h=[k,k+a,k+b];var l=[f,f,f];var m=[a,b-a,this.size-b]}else g=[e,e+a,e+b],h=[k,k,k],l=[a,b-a,this.size-b],m=[f,f,f];this.shades.forEach(function(a,b){a[d]({x:g[b],y:h[b],width:l[b],height:m[b]})})};p.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,k){a.shades[k]=
e.rect().addClass("highcharts-navigator-mask"+(1===k?"-inside":"-outside")).add(f);d.styledMode||a.shades[k].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===k&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);
a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var k=b.handles;a.handles[c].attr({fill:k.backgroundColor,stroke:k.borderColor,"stroke-width":k.lineWidth}).css(g)}})};p.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();f(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};p.prototype.render=function(a,
b,c,d){var k=this.chart,f=this.scrollbarHeight,g,h=this.xAxis,n=h.pointRange||0;var C=h.navigatorAxis.fake?k.xAxis[0]:h;var p=this.navigatorEnabled,q,t=this.rendered;var r=k.inverted;var u=k.xAxis[0].minRange,F=k.xAxis[0].options.maxRange;if(!this.hasDragged||m(c)){a=e(a-n/2);b=e(b+n/2);if(!l(a)||!l(b))if(t)c=0,d=G(h.width,C.width);else return;this.left=G(h.left,k.plotLeft+f+(r?k.plotWidth:0));this.size=q=g=G(h.len,(r?k.plotHeight:k.plotWidth)-2*f);k=r?f:g+2*f;c=G(c,h.toPixels(a,!0));d=G(d,h.toPixels(b,
!0));l(c)&&Infinity!==Math.abs(c)||(c=0,d=k);a=h.toValue(c,!0);b=h.toValue(d,!0);var v=Math.abs(e(b-a));v<u?this.grabbedLeft?c=h.toPixels(b-u-n,!0):this.grabbedRight&&(d=h.toPixels(a+u+n,!0)):m(F)&&e(v-n)>F&&(this.grabbedLeft?c=h.toPixels(b-F-n,!0):this.grabbedRight&&(d=h.toPixels(a+F+n,!0)));this.zoomedMax=D(Math.max(c,d),0,q);this.zoomedMin=D(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,q);this.range=this.zoomedMax-this.zoomedMin;q=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);
p&&(this.navigatorGroup.attr({visibility:"visible"}),t=t&&!this.hasDragged?"animate":"attr",this.drawMasks(c,q,r,t),this.drawOutline(c,q,r,t),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,r,t),this.drawHandle(q,1,r,t)));this.scrollbar&&(r?(r=this.top-f,C=this.left-f+(p||!C.opposite?0:(C.titleOffset||0)+C.axisTitleMargin),f=g+2*f):(r=this.top+(p?this.height:-f),C=this.left-f),this.scrollbar.position(C,r,k,f),this.scrollbar.setRange(this.zoomedMin/(g||1),this.zoomedMax/(g||1)));this.rendered=
!0}};p.prototype.addMouseEvents=function(){var a=this,b=a.chart,c=b.container,d=[],e,f;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};a.mouseUpHandler=f=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(q(b.renderTo,"mousemove",e),q(c.ownerDocument,"mouseup",f));u&&(d.push(q(b.renderTo,"touchmove",e),q(c.ownerDocument,"touchend",f)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(q(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))};
p.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,k){c.push(q(e.element,a,function(a){b[d+"Mousedown"](a,k)}))})});return c};p.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,k=this.left,f=this.size,g=this.range,h=a.chartX;c.inverted&&(h=a.chartY,k=this.top);if(1===b)this.grabbedCenter=h,this.fixedWidth=g,this.dragOffset=h-e;else{a=h-k-g/2;if(0===b)a=Math.max(0,
a);else if(2===b&&a+g>=f)if(a=f-g,this.reversedExtremes){a-=g;var l=this.getUnionExtremes().dataMin}else var n=this.getUnionExtremes().dataMax;a!==e&&(this.fixedWidth=g,b=d.navigatorAxis.toFixedRange(a,a+g,l,n),m(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};p.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,
this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null};p.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,e=b.navigatorSize,k=b.range,f=b.dragOffset,g=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,g&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&
(b.hasDragged=!0,c<f?c=f:c>e+f-k&&(c=e+f-k),b.render(0,0,c-f,c-f+k)),b.hasDragged&&b.scrollbar&&G(b.scrollbar.options.liveRedraw,y.svg&&!x&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};p.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,k=b.inverted,f=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var g=
this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var h=this.fixedExtreme;this.zoomedMax===this.size&&(h=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(g=this.reversedExtremes?d.dataMax:d.dataMin);c=c.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,g,h);m(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&
(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&l(this.zoomedMin)&&l(this.zoomedMax)&&(b=Math.round(this.zoomedMin),a=Math.round(this.zoomedMax),this.shades&&this.drawMasks(b,a,k,f),this.outline&&this.drawOutline(b,a,k,f),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(b,0,k,f),this.drawHandle(a,1,k,f)))};p.prototype.removeEvents=
function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};p.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){J(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&J(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};p.prototype.init=function(a){var d=a.options,e=d.navigator,k=e.enabled,
g=d.scrollbar,h=g.enabled;d=k?e.height:0;var l=h?g.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=d;this.scrollbarHeight=l;this.scrollbarEnabled=h;this.navigatorEnabled=k;this.navigatorOptions=e;this.scrollbarOptions=g;this.outlineHeight=d+l;this.opposite=G(e.opposite,!(k||!a.inverted));var m=this;k=m.baseSeries;g=a.xAxis.length;h=a.yAxis.length;var n=k&&k[0]&&k[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;m.navigatorEnabled?(m.xAxis=new b(a,f({breaks:n.options.breaks,
ordinal:n.options.ordinal},e.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:g,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[l,0,-l,0],width:d}:{offsets:[0,-l,0,l],height:d})),m.yAxis=new b(a,f(e.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:h,isInternal:!0,reversed:G(e.yAxis&&e.yAxis.reversed,a.yAxis[0]&&a.yAxis[0].reversed,!1),zoomEnabled:!1},a.inverted?{width:d}:
{height:d})),k||e.series.data?m.updateNavigatorSeries(!1):0===a.series.length&&(m.unbindRedraw=q(a,"beforeRedraw",function(){0<a.series.length&&!m.series&&(m.setBaseSeries(),m.unbindRedraw())})),m.reversedExtremes=a.inverted&&!m.xAxis.reversed||!a.inverted&&m.xAxis.reversed,m.renderElements(),m.addMouseEvents()):(m.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*l,k=I("min",d.options.min,e.dataMin);d=I("max",d.options.max,e.dataMax)-k;return c?
b*d/f+k:f*(b-k)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},m.xAxis.navigatorAxis.axis=m.xAxis,m.xAxis.navigatorAxis.toFixedRange=E.AdditionsClass.prototype.toFixedRange.bind(m.xAxis.navigatorAxis));a.options.scrollbar.enabled&&(a.scrollbar=m.scrollbar=new c(a.renderer,f(a.options.scrollbar,{margin:m.navigatorEnabled?0:10,vertical:a.inverted}),a),q(m.scrollbar,"changed",function(b){var c=m.size,d=c*this.to;c*=this.from;m.hasDragged=m.scrollbar.hasDragged;
m.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){m.onMouseUp(b)})}));m.addBaseSeriesEvents();m.addChartEvents()};p.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,f;a&&null===b.dataMin||(f={dataMin:G(d&&d.min,I("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:G(d&&d.max,I("max",e.max,b.dataMax,c.dataMax,c.max))});return f};p.prototype.setBaseSeries=function(a,b){var c=this.chart,
e=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?d(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||e.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};p.prototype.updateNavigatorSeries=function(a,b){var c=this,d=c.chart,e=c.baseSeries,k,h,l=c.navigatorOptions.series,m,
p={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},q=c.series=(c.series||[]).filter(function(a){var b=a.baseSeries;return 0>e.indexOf(b)?(b&&(J(b,"updatedData",c.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});e&&e.length&&e.forEach(function(a){var r=a.navigatorSeries,u=g({color:a.color,visible:a.visible},t(l)?n.navigator.series:
l);r&&!1===c.navigatorOptions.adaptToUpdatedData||(p.name="Navigator "+e.length,k=a.options||{},m=k.navigatorOptions||{},h=f(k,p,u,m),h.pointRange=G(u.pointRange,m.pointRange,n.plotOptions[h.type||"line"].pointRange),u=m.data||u.data,c.hasNavigatorData=c.hasNavigatorData||!!u,h.data=u||k.data&&k.data.slice(0),r&&r.options?r.update(h,b):(a.navigatorSeries=d.initSeries(h),a.navigatorSeries.baseSeries=a,q.push(a.navigatorSeries)))});if(l.data&&(!e||!e.length)||t(l))c.hasNavigatorData=!1,l=B(l),l.forEach(function(a,
b){p.name="Navigator "+(q.length+1);h=f(n.navigator.series,{color:d.series[b]&&!d.series[b].options.isInternal&&d.series[b].color||d.options.colors[b]||d.options.colors[0]},p,a);h.data=a.data;h.data&&(c.hasNavigatorData=!0,q.push(d.initSeries(h)))});a&&this.addBaseSeriesEvents()};p.prototype.addBaseSeriesEvents=function(){var b=this,c=b.baseSeries||[];c[0]&&c[0].xAxis&&q(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);c.forEach(function(c){q(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,
!1)});q(c,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&q(c,"updatedData",this.updatedDataHandler);q(c,"remove",function(){this.navigatorSeries&&(a(b.series,this.navigatorSeries),m(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};p.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};
p.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};p.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,g=G(this.options.overscroll,0),h=a.series&&a.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var n=
c;var p=n+b}f&&(p=d+g,e||(n=Math.max(c,p-b,a.getBaseSeriesMin(h&&h.xData?h.xData[0]:-Number.MAX_VALUE))));m&&(e||f)&&l(n)&&(this.min=this.userMin=n,this.max=this.userMax=p)}a.stickToMin=a.stickToMax=null};p.prototype.updatedDataHandler=function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=l(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||
!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};p.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(q(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),q(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?
"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};p.prototype.destroy=function(){this.removeEvents();this.xAxis&&(a(this.chart.xAxis,this.xAxis),a(this.chart.axes,this.xAxis));this.yAxis&&(a(this.chart.yAxis,this.yAxis),a(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){h(a)},this)};return p}();y.Navigator||(y.Navigator=K,E.compose(b),q(A,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!x&&"x"===a.chart.zoomType||x&&"x"===a.chart.pinchType))return!1}),q(A,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new K(this)}),q(A,"afterSetChartSize",
function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&"proximate"!==c.layout&&c.enabled&&!c.floating?a.legendHeight+G(c.margin,
10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),q(A,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(f(!0,this.options.navigator,b),f(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),q(A,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&
!this.options.scrollbar.enabled||(this.scroller=this.navigator=new K(this),G(a.redraw,!0)&&this.redraw(a.animation))}),q(A,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),q(p,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),A.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));y.Navigator=K;return y.Navigator});I(b,"masters/modules/gantt.src.js",
[],function(){})});
//# sourceMappingURL=gantt.js.map