/*
 Highcharts Gantt JS v8.2.2 (2020-10-22)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(B){b(B);b.Highcharts=B;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function B(b,t,E,w){b.hasOwnProperty(t)||(b[t]=w.apply(null,E))}b=b?b._modules:{};B(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var t=b.extend,x=b.isNumber,w=b.pick,q=function(b,k){var p=b.reduce(function(d,
p){var m=w(p.parent,"");"undefined"===typeof d[m]&&(d[m]=[]);d[m].push(p);return d},{});Object.keys(p).forEach(function(d,b){var m=p[d];""!==d&&-1===k.indexOf(d)&&(m.forEach(function(d){b[""].push(d)}),delete b[d])});return p},k=function(b,q,p,d,C,m){var r=0,n=0,l=m&&m.after,a=m&&m.before;q={data:d,depth:p-1,id:b,level:p,parent:q};var g,h;"function"===typeof a&&a(q,m);a=(C[b]||[]).map(function(e){var c=k(e.id,b,p+1,e,C,m),f=e.start;e=!0===e.milestone?f:e.end;g=!x(g)||f<g?f:g;h=!x(h)||e>h?e:h;r=r+
1+c.descendants;n=Math.max(c.height+1,n);return c});d&&(d.start=w(d.start,g),d.end=w(d.end,h));t(q,{children:a,descendants:r,height:n});"function"===typeof l&&l(q,m);return q};return{getListOfParents:q,getNode:k,getTree:function(b,t){var p=b.map(function(d){return d.id});b=q(b,p);return k("",null,1,null,b,t)}}});B(b,"Core/Axis/TreeGridTick.js",[b["Core/Utilities.js"]],function(b){var t=b.addEvent,E=b.defined,w=b.isObject,q=b.isNumber,k=b.pick,u=b.wrap,x;(function(b){function d(){this.treeGrid||(this.treeGrid=
new l(this))}function p(a,g){a=a.treeGrid;var h=!a.labelIcon,e=g.renderer,c=g.xy,f=g.options,A=f.width,D=f.height,H=c.x-A/2-f.padding;c=c.y-D/2;var b=g.collapsed?90:180,d=g.show&&q(c),v=a.labelIcon;v||(a.labelIcon=v=e.path(e.symbols[f.type](f.x,f.y,A,D)).addClass("highcharts-label-icon").add(g.group));d||v.attr({y:-9999});e.styledMode||v.attr({"stroke-width":1,fill:k(g.color,"#666666")}).css({cursor:"pointer",stroke:f.lineColor,strokeWidth:f.lineWidth});v[h?"attr":"animate"]({translateX:H,translateY:c,
rotation:b})}function m(a,g,h,e,c,f,A,D,b){var d=k(this.options&&this.options.labels,f);f=this.pos;var H=this.axis,v="treegrid"===H.options.type;a=a.apply(this,[g,h,e,c,d,A,D,b]);v&&(g=d&&w(d.symbol,!0)?d.symbol:{},d=d&&q(d.indentation)?d.indentation:0,f=(f=(H=H.treeGrid.mapOfPosToGridNode)&&H[f])&&f.depth||1,a.x+=g.width+2*g.padding+(f-1)*d);return a}function r(a){var g=this,h=g.pos,e=g.axis,c=g.label,f=e.treeGrid.mapOfPosToGridNode,A=e.options,D=k(g.options&&g.options.labels,A&&A.labels),d=D&&w(D.symbol,
!0)?D.symbol:{},b=(f=f&&f[h])&&f.depth;A="treegrid"===A.type;var r=-1<e.tickPositions.indexOf(h);h=e.chart.styledMode;A&&f&&c&&c.element&&c.addClass("highcharts-treegrid-node-level-"+b);a.apply(g,Array.prototype.slice.call(arguments,1));A&&c&&c.element&&f&&f.descendants&&0<f.descendants&&(e=e.treeGrid.isCollapsed(f),p(g,{color:!h&&c.styles&&c.styles.color||"",collapsed:e,group:c.parentGroup,options:d,renderer:c.renderer,show:r,xy:c.xy}),d="highcharts-treegrid-node-"+(e?"expanded":"collapsed"),c.addClass("highcharts-treegrid-node-"+
(e?"collapsed":"expanded")).removeClass(d),h||c.css({cursor:"pointer"}),[c,g.treeGrid.labelIcon].forEach(function(f){f&&!f.attachedTreeGridEvents&&(t(f.element,"mouseover",function(){c.addClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:"underline"})}),t(f.element,"mouseout",function(){var f=E(D.style)?D.style:{};c.removeClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:f.textDecoration})}),t(f.element,"click",function(){g.treeGrid.toggleCollapse()}),
f.attachedTreeGridEvents=!0)}))}var n=!1;b.compose=function(a){n||(t(a,"init",d),u(a.prototype,"getLabelPosition",m),u(a.prototype,"renderLabel",r),a.prototype.collapse=function(a){this.treeGrid.collapse(a)},a.prototype.expand=function(a){this.treeGrid.expand(a)},a.prototype.toggleCollapse=function(a){this.treeGrid.toggleCollapse(a)},n=!0)};var l=function(){function a(a){this.tick=a}a.prototype.collapse=function(a){var h=this.tick,e=h.axis,c=e.brokenAxis;c&&e.treeGrid.mapOfPosToGridNode&&(h=e.treeGrid.collapse(e.treeGrid.mapOfPosToGridNode[h.pos]),
c.setBreaks(h,k(a,!0)))};a.prototype.expand=function(a){var h=this.tick,e=h.axis,c=e.brokenAxis;c&&e.treeGrid.mapOfPosToGridNode&&(h=e.treeGrid.expand(e.treeGrid.mapOfPosToGridNode[h.pos]),c.setBreaks(h,k(a,!0)))};a.prototype.toggleCollapse=function(a){var h=this.tick,e=h.axis,c=e.brokenAxis;c&&e.treeGrid.mapOfPosToGridNode&&(h=e.treeGrid.toggleCollapse(e.treeGrid.mapOfPosToGridNode[h.pos]),c.setBreaks(h,k(a,!0)))};return a}();b.Additions=l})(x||(x={}));return x});B(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],
b["Core/Utilities.js"]],function(b,t){var x=t.extend,w=t.isArray,q=t.isNumber,k=t.isObject,u=t.merge,G=t.pick;return{getColor:function(p,d){var k=d.index,m=d.mapOptionsToLevel,r=d.parentColor,n=d.parentColorIndex,l=d.series,a=d.colors,g=d.siblings,h=l.points,e=l.chart.options.chart,c;if(p){h=h[p.i];p=m[p.level]||{};if(m=h&&p.colorByPoint){var f=h.index%(a?a.length:e.colorCount);var A=a&&a[f]}if(!l.chart.styledMode){a=h&&h.options.color;e=p&&p.color;if(c=r)c=(c=p&&p.colorVariation)&&"brightness"===
c.key?b.parse(r).brighten(k/g*c.to).get():r;c=G(a,e,A,c,l.color)}var D=G(h&&h.options.colorIndex,p&&p.colorIndex,f,n,d.colorIndex)}return{color:c,colorIndex:D}},getLevelOptions:function(b){var d=null;if(k(b)){d={};var p=q(b.from)?b.from:1;var m=b.levels;var r={};var n=k(b.defaults)?b.defaults:{};w(m)&&(r=m.reduce(function(b,a){if(k(a)&&q(a.level)){var d=u({},a);var h="boolean"===typeof d.levelIsConstant?d.levelIsConstant:n.levelIsConstant;delete d.levelIsConstant;delete d.level;a=a.level+(h?0:p-1);
k(b[a])?x(b[a],d):b[a]=d}return b},{}));m=q(b.to)?b.to:1;for(b=0;b<=m;b++)d[b]=u({},n,k(r[b])?r[b]:{})}return d},setTreeValues:function m(b,k){var d=k.before,n=k.idRoot,l=k.mapIdToNode[n],a=k.points[b.i],g=a&&a.options||{},h=0,e=[];x(b,{levelDynamic:b.level-(("boolean"===typeof k.levelIsConstant?k.levelIsConstant:1)?0:l.level),name:G(a&&a.name,""),visible:n===b.id||("boolean"===typeof k.visible?k.visible:!1)});"function"===typeof d&&(b=d(b,k));b.children.forEach(function(c,f){var a=x({},k);x(a,{index:f,
siblings:b.children.length,visible:b.visible});c=m(c,a);e.push(c);c.visible&&(h+=c.val)});b.visible=0<h||b.visible;d=G(g.value,h);x(b,{children:e,childrenTotal:h,isLeaf:b.visible&&!h,val:d});return b},updateRootId:function(b){if(k(b)){var d=k(b.options)?b.options:{};d=G(b.rootNode,d.rootId,"");k(b.userOptions)&&(b.userOptions.rootId=d);b.rootNode=d}return d}}});B(b,"Core/Axis/GridAxis.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Options.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],
function(b,t,E,w,q){var k=q.addEvent,u=q.defined,x=q.erase,p=q.find,d=q.isArray,C=q.isNumber,m=q.merge,r=q.pick,n=q.timeUnits,l=q.wrap;E=t.Chart;var a=function(e){var c=e.options;c.labels||(c.labels={});c.labels.align=r(c.labels.align,"center");e.categories||(c.showLastLabel=!1);e.labelRotation=0;c.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(e,c){var f={width:0,height:0};c.forEach(function(c){c=e[c];if(q.isObject(c,!0)){var a=q.isObject(c.label,!0)?c.label:{};c=a.getBBox?a.getBBox().height:
0;a.textStr&&!C(a.textPxLength)&&(a.textPxLength=a.getBBox().width);var b=C(a.textPxLength)?Math.round(a.textPxLength):0;a.textStr&&(b=Math.round(a.getBBox().width));f.height=Math.max(c,f.height);f.width=Math.max(b,f.width)}});return f};t.dateFormats.W=function(a){a=new this.Date(a);var c=(this.get("Day",a)+6)%7,f=new this.Date(a.valueOf());this.set("Date",f,this.get("Date",a)-c+3);c=new this.Date(this.get("FullYear",f),0,1);4!==this.get("Day",c)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",
c))%7));return(1+Math.floor((f.valueOf()-c.valueOf())/6048E5)).toString()};t.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};k(E,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})});k(w,"afterGetLabelPosition",function(a){var c=this.label,f=this.axis,e=f.reversed,b=f.chart,d=f.options.grid||{},g=f.options.labels,r=g.align,v=h.Side[f.side],n=a.tickmarkOffset,l=f.tickPositions,
F=this.pos-n;l=C(l[a.index+1])?l[a.index+1]-n:f.max+n;var y=f.tickSize("tick");n=y?y[0]:0;y=y?y[1]/2:0;if(!0===d.enabled){if("top"===v){d=f.top+f.offset;var z=d-n}else"bottom"===v?(z=b.chartHeight-f.bottom+f.offset,d=z+n):(d=f.top+f.len-f.translate(e?l:F),z=f.top+f.len-f.translate(e?F:l));"right"===v?(v=b.chartWidth-f.right+f.offset,e=v+n):"left"===v?(e=f.left+f.offset,v=e-n):(v=Math.round(f.left+f.translate(e?l:F))-y,e=Math.round(f.left+f.translate(e?F:l))-y);this.slotWidth=e-v;a.pos.x="left"===
r?v:"right"===r?e:v+(e-v)/2;a.pos.y=z+(d-z)/2;b=b.renderer.fontMetrics(g.style.fontSize,c.element);c=c.getBBox().height;g.useHTML?a.pos.y+=b.b+-(c/2):(c=Math.round(c/b.h),a.pos.y+=(b.b-(b.h-b.f))/2+-((c-1)*b.h/2));a.pos.x+=f.horiz&&g.x||0}});var g=function(){function a(c){this.axis=c}a.prototype.isOuterAxis=function(){var c=this.axis,a=c.grid.columnIndex,e=c.linkedParent&&c.linkedParent.grid.columns||c.grid.columns,b=a?c.linkedParent:c,h=-1,d=0;c.chart[c.coll].forEach(function(a,f){a.side!==c.side||
a.options.isInternal||(d=f,a===b&&(h=f))});return d===h&&(C(a)?e.length===a:!0)};a.prototype.renderBorder=function(c){var a=this.axis,e=a.chart.renderer,b=a.options;c=e.path(c).addClass("highcharts-axis-line").add(a.axisBorder);e.styledMode||c.attr({stroke:b.lineColor,"stroke-width":b.lineWidth,zIndex:7});return c};return a}(),h=function(){function e(){}e.compose=function(c){b.keepProps.push("grid");l(c.prototype,"unsquish",e.wrapUnsquish);k(c,"init",e.onInit);k(c,"afterGetOffset",e.onAfterGetOffset);
k(c,"afterGetTitlePosition",e.onAfterGetTitlePosition);k(c,"afterInit",e.onAfterInit);k(c,"afterRender",e.onAfterRender);k(c,"afterSetAxisTranslation",e.onAfterSetAxisTranslation);k(c,"afterSetOptions",e.onAfterSetOptions);k(c,"afterSetOptions",e.onAfterSetOptions2);k(c,"afterSetScale",e.onAfterSetScale);k(c,"afterTickSize",e.onAfterTickSize);k(c,"trimTicks",e.onTrimTicks);k(c,"destroy",e.onDestroy)};e.onAfterGetOffset=function(){var c=this.grid;(c&&c.columns||[]).forEach(function(c){c.getOffset()})};
e.onAfterGetTitlePosition=function(c){if(!0===(this.options.grid||{}).enabled){var a=this.axisTitle,b=this.height,h=this.horiz,d=this.left,g=this.offset,n=this.opposite,l=this.options.title,k=void 0===l?{}:l;l=this.top;var m=this.width,F=this.tickSize(),y=a&&a.getBBox().width,z=k.x||0,K=k.y||0,p=r(k.margin,h?5:10);a=this.chart.renderer.fontMetrics(k.style&&k.style.fontSize,a).f;F=(h?l+b:d)+(h?1:-1)*(n?-1:1)*(F?F[0]/2:0)+(this.side===e.Side.bottom?a:0);c.titlePosition.x=h?d-y/2-p+z:F+(n?m:0)+g+z;c.titlePosition.y=
h?F-(n?b:0)+(n?a:-a)/2+g+K:l-p+K}};e.onAfterInit=function(){var c=this.chart,f=this.options.grid;f=void 0===f?{}:f;var e=this.userOptions;f.enabled&&(a(this),l(this,"labelFormatter",function(a){var c=this.axis,f=this.value,e=c.tickPositions,b=(c.isLinked?c.linkedParent:c).series[0],h=f===e[0];e=f===e[e.length-1];var d=b&&p(b.options.data,function(a){return a[c.isXAxis?"x":"y"]===f});if(d&&b.is("gantt")){var g=m(d);t.seriesTypes.gantt.prototype.setGanttPointAliases(g)}this.isFirst=h;this.isLast=e;
this.point=g;return a.call(this)}));if(f.columns)for(var h=this.grid.columns=[],d=this.grid.columnIndex=0;++d<f.columns.length;){var g=m(e,f.columns[f.columns.length-d-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete g.grid.columns;g=new b(this.chart,g);g.grid.isColumn=!0;g.grid.columnIndex=d;x(c.axes,g);x(c[this.coll],g);h.push(g)}};e.onAfterRender=function(){var c,a=this.grid,b=this.options;if(!0===(b.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,
this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(b=b.lineWidth)){b=this.getLinePath(b);var h=b[0],d=b[1],g=((this.tickSize("tick")||[1])[0]-1)*(this.side===e.Side.top||this.side===e.Side.left?-1:1);"M"===h[0]&&"L"===d[0]&&(this.horiz?(h[2]+=g,d[2]+=g):(h[1]+=g,d[1]+=g));!this.horiz&&this.chart.marginRight&&(h=[h,["L",this.left,h[2]]],g=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],d=
[["M",d[1],this.toPixels(this.max+this.tickmarkOffset)],g],this.grid.upperBorder||0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(h)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:h}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(d)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:d}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:b}):this.grid.axisLineExtra=this.grid.renderBorder(b);this.axisLine[this.showAxis?"show":
"hide"](!0)}(a&&a.columns||[]).forEach(function(a){a.render()});!this.horiz&&this.chart.hasRendered&&(this.scrollbar||(null===(c=this.linkedParent)||void 0===c?0:c.scrollbar))&&(c=this.max,a=this.tickmarkOffset,b=this.tickPositions[this.tickPositions.length-1],d=this.tickPositions[0],this.min-d>a?this.ticks[d].label.hide():this.ticks[d].label.show(),b-c>a?this.ticks[b].label.hide():this.ticks[b].label.show(),b-c<a&&0<b-c&&this.ticks[b].isLast?this.ticks[b].mark.hide():this.ticks[b-1].mark.show())}};
e.onAfterSetAxisTranslation=function(){var a,b=this.tickPositions&&this.tickPositions.info,e=this.options,d=e.grid||{},h=this.userOptions.labels||{};this.horiz?(!0===d.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),b&&e.dateTimeLabelFormats&&e.labels&&!u(h.align)&&(!1===e.dateTimeLabelFormats[b.unitName].range||1<b.count)&&(e.labels.align="left",u(h.x)||(e.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};
e.onAfterSetOptions=function(a){var c=this.options;a=a.userOptions;var b=c&&q.isObject(c.grid,!0)?c.grid:{};if(!0===b.enabled){var e=m(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(u(a.linkedTo)&&!u(a.tickPixelInterval)&&(e.tickPixelInterval=350),u(a.tickPixelInterval)||!u(a.linkedTo)||u(a.tickPositioner)||u(a.tickInterval)||(e.tickPositioner=function(a,c){var b=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var f,h=e.units;for(f=0;f<h.length;f++)if(h[f][0]===b.unitName){var d=f;break}if(h[d+1]){var g=h[d+
1][0];var y=(h[d+1][1]||[1])[0]}else"year"===b.unitName&&(g="year",y=10*b.count);b=n[g];this.tickInterval=b*y;return this.getTimeTicks({unitRange:b,count:y,unitName:g},a,c,this.options.startOfWeek)}}));m(!0,this.options,e);this.horiz&&(c.minPadding=r(a.minPadding,0),c.maxPadding=r(a.maxPadding,0));C(c.grid.borderWidth)&&(c.tickWidth=c.lineWidth=b.borderWidth)}};e.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var c=a.columns;a.enabled&&c&&m(!0,this.options,c[c.length-1])};e.onAfterSetScale=
function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};e.onAfterTickSize=function(a){var c=b.defaultLeftAxisOptions,e=this.horiz,h=this.maxLabelDimensions,g=this.options.grid;g=void 0===g?{}:g;g.enabled&&h&&(c=2*Math.abs(c.labels.x),e=e?g.cellHeight||c+h.height:c+h.width,d(a.tickSize)?a.tickSize[0]=e:a.tickSize=[e,0])};e.onDestroy=function(a){var c=this.grid;(c.columns||[]).forEach(function(c){c.destroy(a.keepEvents)});c.columns=void 0};e.onInit=function(a){a=a.userOptions||{};var c=
a.grid||{};c.enabled&&u(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor);this.grid||(this.grid=new g(this))};e.onTrimTicks=function(){var a=this.options,b=this.categories,e=this.tickPositions,h=e[0],d=e[e.length-1],g=this.linkedParent&&this.linkedParent.min||this.min,n=this.linkedParent&&this.linkedParent.max||this.max,l=this.tickInterval;!0!==(a.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(h<g&&h+l>g&&!a.startOnTick&&(e[0]=g),d>n&&d-l<n&&!a.endOnTick&&(e[e.length-1]=n))};e.wrapUnsquish=
function(a){var c=this.options.grid;return!0===(void 0===c?{}:c).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return e}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});B(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,t,E,w){var q=w.addEvent,k=w.find,
u=w.fireEvent,x=w.isArray,p=w.isNumber,d=w.pick,C=function(){function m(b){this.hasBreaks=!1;this.axis=b}m.isInBreak=function(b,d){var l=b.repeat||Infinity,a=b.from,g=b.to-b.from;d=d>=a?(d-a)%l:l-(a-d)%l;return b.inclusive?d<=g:d<g&&0!==d};m.lin2Val=function(b){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return b;var l;for(l=0;l<d.length;l++){var a=d[l];if(a.from>=b)break;else a.to<b?b+=a.len:m.isInBreak(a,b)&&(b+=a.len)}return b};m.val2Lin=function(b){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return b;
var l=b,a;for(a=0;a<d.length;a++){var g=d[a];if(g.to<=b)l-=g.len;else if(g.from>=b)break;else if(m.isInBreak(g,b)){l-=b-g.from;break}}return l};m.prototype.findBreakAt=function(b,d){return k(d,function(d){return d.from<b&&b<d.to})};m.prototype.isInAnyBreak=function(b,k){var l=this.axis,a=l.options.breaks,g=a&&a.length,h;if(g){for(;g--;)if(m.isInBreak(a[g],b)){var e=!0;h||(h=d(a[g].showPoints,!l.isXAxis))}var c=e&&k?e&&!h:e}return c};m.prototype.setBreaks=function(k,n){var l=this,a=l.axis,g=x(k)&&
!!k.length;a.isDirty=l.hasBreaks!==g;l.hasBreaks=g;a.options.breaks=a.userOptions.breaks=k;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=!0});g||a.val2lin!==m.val2Lin||(delete a.val2lin,delete a.lin2val);g&&(a.userOptions.ordinal=!1,a.lin2val=m.lin2Val,a.val2lin=m.val2Lin,a.setExtremes=function(a,e,c,d,g){if(l.hasBreaks){for(var f,h=this.options.breaks;f=l.findBreakAt(a,h);)a=f.to;for(;f=l.findBreakAt(e,h);)e=f.from;e<a&&(e=a)}b.prototype.setExtremes.call(this,a,e,c,d,g)},a.setAxisTranslation=
function(h){b.prototype.setAxisTranslation.call(this,h);l.unitLength=null;if(l.hasBreaks){h=a.options.breaks||[];var e=[],c=[],f=0,g,k=a.userMin||a.min,n=a.userMax||a.max,p=d(a.pointRangePadding,0),q;h.forEach(function(a){g=a.repeat||Infinity;m.isInBreak(a,k)&&(k+=a.to%g-k%g);m.isInBreak(a,n)&&(n-=n%g-a.from%g)});h.forEach(function(a){r=a.from;for(g=a.repeat||Infinity;r-g>k;)r-=g;for(;r<k;)r+=g;for(q=r;q<n;q+=g)e.push({value:q,move:"in"}),e.push({value:q+(a.to-a.from),move:"out",size:a.breakSize})});
e.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var v=0;var r=k;e.forEach(function(a){v+="in"===a.move?1:-1;1===v&&"in"===a.move&&(r=a.value);0===v&&(c.push({from:r,to:a.value,len:a.value-r-(a.size||0)}),f+=a.value-r-(a.size||0))});a.breakArray=l.breakArray=c;l.unitLength=n-k-f+p;u(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:l.unitLength&&(a.transA*=(n-a.min+p)/l.unitLength);p&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=k;
a.max=n}});d(n,!0)&&a.chart.redraw()};return m}();w=function(){function b(){}b.compose=function(b,k){b.keepProps.push("brokenAxis");var l=t.prototype;l.drawBreaks=function(a,b){var g=this,e=g.points,c,f,k,l;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var n=a.brokenAxis;b.forEach(function(b){c=n&&n.breakArray||[];f=a.isXAxis?a.min:d(g.options.threshold,a.min);e.forEach(function(e){l=d(e["stack"+b.toUpperCase()],e[b]);c.forEach(function(b){if(p(f)&&p(l)){k=!1;if(f<b.from&&l>b.to||f>b.from&&l<b.from)k=
"pointBreak";else if(f<b.from&&l>b.from&&l<b.to||f>b.from&&l>b.to&&l<b.from)k="pointInBreak";k&&u(a,k,{point:e,brk:b})}})})})}};l.gappedPath=function(){var a=this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var d=this.points.slice(),e=d.length-1,c=this.yAxis,f;if(a&&0<e)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),f=void 0;e--;)f&&!1!==f.visible||(f=d[e+1]),b=d[e],!1!==f.visible&&!1!==b.visible&&(f.x-b.x>a&&(f=(b.x+f.x)/2,d.splice(e+
1,0,{isNull:!0,x:f}),c.stacking&&this.options.stacking&&(f=c.stacking.stacks[this.stackKey][f]=new E(c,c.options.stackLabels,!1,f,this.stack),f.total=0)),f=b);return this.getGraphPath(d)};q(b,"init",function(){this.brokenAxis||(this.brokenAxis=new C(this))});q(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});q(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=this.tickPositions,d=this.tickPositions.info,
e=[],c;for(c=0;c<b.length;c++)a.isInAnyBreak(b[c])||e.push(b[c]);this.tickPositions=e;this.tickPositions.info=d}});q(b,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});q(k,"afterGeneratePoints",function(){var a=this.options.connectNulls,b=this.points,d=this.xAxis,e=this.yAxis;if(this.isDirty)for(var c=b.length;c--;){var f=b[c],k=!(null===f.y&&!1===a)&&(d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(f.x,!0)||e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(f.y,
!0));f.visible=k?!1:!1!==f.options.visible}});q(k,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,d(this.pointArrayMap,["y"]))})};return b}();w.compose(b,t);return w});B(b,"Core/Axis/TreeGridAxis.js",[b["Core/Globals.js"],b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,t,E,w,q,k,u){var x=k.getLevelOptions,p=u.addEvent,d=u.find,C=u.fireEvent,m=u.isArray,
r=u.isNumber,n=u.isObject,l=u.isString,a=u.merge,g=u.pick,h=u.wrap,e;(function(c){function e(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}}function k(a,b,c){var e=[],f=[],g={},h={},k=-1,y="boolean"===typeof b?b:!1;a=w.getTree(a,{after:function(a){a=h[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=c;a.height=b;a.collapsed&&f.push(a)},before:function(a){var b=n(a.data,!0)?a.data:
{},c=l(b.name)?b.name:"",f=g[a.parent];f=n(f,!0)?h[f.pos]:null;var m=function(a){return a.name===c},z;y&&n(f,!0)&&(z=d(f.children,m))?(m=z.pos,z.nodes.push(a)):m=k++;h[m]||(h[m]=z={depth:f?f.depth+1:0,name:c,id:b.id,nodes:[a],children:[],pos:m},-1!==m&&e.push(c),n(f,!0)&&f.children.push(z));l(a.id)&&(g[a.id]=a);z&&!0===b.collapsed&&(z.collapsed=!0);a.pos=m}});h=function(a,b){var c=function(a,e,d){var f=e+(-1===e?0:b-1),h=(f-e)/2,g=e+h;a.nodes.forEach(function(a){var b=a.data;n(b,!0)&&(b.y=e+(b.seriesIndex||
0),delete b.seriesIndex);a.pos=g});d[g]=a;a.pos=g;a.tickmarkOffset=h+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,d);f=(a.collapseEnd||0)-.5});a.collapseEnd=f+.5;return d};return c(a["-1"],-1,{})}(h,c);return{categories:e,mapOfIdToNode:g,mapOfPosToGridNode:h,collapsedNodes:f,tree:a}}function t(c){c.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(e){var d=e.options||{},f=d.labels,g=d.uniqueNames,h=0;d=d.max;if(!e.treeGrid.mapOfPosToGridNode||e.series.some(function(a){return!a.hasRendered||
a.isDirtyData||a.isDirty})){var l=e.series.reduce(function(a,c){c.visible&&((c.options.data||[]).forEach(function(e){c.options.keys&&c.options.keys.length&&(e=c.pointClass.prototype.optionsToObject.call({series:c},e),b.seriesTypes.gantt.prototype.setGanttPointAliases(e));n(e,!0)&&(e.seriesIndex=h,a.push(e))}),!0===g&&h++);return a},[]);if(d&&l.length<d)for(var y=l.length;y<=d;y++)l.push({name:y+"\u200b"});d=k(l,g||!1,!0===g?h:1);e.categories=d.categories;e.treeGrid.mapOfPosToGridNode=d.mapOfPosToGridNode;
e.hasNames=!0;e.treeGrid.tree=d.tree;e.series.forEach(function(b){var c=(b.options.data||[]).map(function(c){m(c)&&b.options.keys&&b.options.keys.length&&l.forEach(function(a){0<=c.indexOf(a.x)&&0<=c.indexOf(a.x2)&&(c=a)});return n(c,!0)?a(c):c});b.visible&&b.setData(c,!1)});e.treeGrid.mapOptionsToLevel=x({defaults:f,from:1,levels:f&&f.levels,to:e.treeGrid.tree&&e.treeGrid.tree.height});"beforeRender"===c.type&&(e.treeGrid.collapsedNodes=d.collapsedNodes)}})}function u(a,b){var c=this.treeGrid.mapOptionsToLevel||
{},e=this.ticks,d=e[b],f;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[b];(c=c[g.depth])&&(f={labels:c});d?(d.parameters.category=g.name,d.options=f,d.addLabel()):e[b]=new E(this,b,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function B(a){var b=this.options;b=(b=b&&b.labels)&&r(b.indentation)?b.indentation:0;var c=a.apply(this,Array.prototype.slice.call(arguments,
1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var e=this.treeGrid.mapOfPosToGridNode[-1].height||0;c.width+=b*(e-1)}return c}function G(b,c,e){var d=this,f="treegrid"===e.type;d.treeGrid||(d.treeGrid=new J(d));f&&(p(c,"beforeRender",t),p(c,"beforeRedraw",t),p(c,"addSeries",function(a){a.options.data&&(a=k(a.options.data,e.uniqueNames||!1,1),d.treeGrid.collapsedNodes=(d.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),p(d,"foundExtremes",function(){d.treeGrid.collapsedNodes&&
d.treeGrid.collapsedNodes.forEach(function(a){var b=d.treeGrid.collapse(a);d.brokenAxis&&(d.brokenAxis.setBreaks(b,!1),d.treeGrid.collapsedNodes&&(d.treeGrid.collapsedNodes=d.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),p(d,"afterBreaks",function(){var a;"yAxis"===d.coll&&!d.staticScale&&(null===(a=d.chart.options.chart)||void 0===a?0:a.height)&&(d.isDirty=!0)}),e=a({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},
{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},e,{reversed:!0,grid:{columns:void 0}}));b.apply(d,[c,e]);f&&(d.hasNames=!0,d.options.showLastLabel=!0)}function v(a){var b=this.options;"treegrid"===b.type?(this.min=g(this.userMin,b.min,this.dataMin),this.max=g(this.userMax,b.max,this.dataMax),C(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?
this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var I=!1;c.compose=function(a){I||(h(a.prototype,"generateTick",u),h(a.prototype,"getMaxLabelDimensions",B),h(a.prototype,"init",G),h(a.prototype,"setTickInterval",v),q.compose(E),I=!0)};var J=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var b=this.axis,c=b.chart;b.series.forEach(function(b){var e=b.options.data;if(a.id&&e){var d=c.get(a.id);b=e[b.data.indexOf(d)];d&&b&&(d.collapsed=
a.collapsed,b.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var b=this.axis,c=b.options.breaks||[],d=e(a,b.max);c.push(d);a.collapsed=!0;b.treeGrid.setCollapsedStatus(a);return c};a.prototype.expand=function(a){var b=this.axis,c=b.options.breaks||[],d=e(a,b.max);a.collapsed=!1;b.treeGrid.setCollapsedStatus(a);return c.reduce(function(a,b){b.to===d.to&&b.from===d.from||a.push(b);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis,b=Math.floor(a.min/a.tickInterval)*
a.tickInterval,c=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(e,d){d=+d;!(d>=b&&d<=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(d)||e.push(d);return e},[])};a.prototype.isCollapsed=function(a){var b=this.axis,c=b.options.breaks||[],d=e(a,b.max);return c.some(function(a){return a.from===d.from&&a.to===d.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();c.Additions=
J})(e||(e={}));t.prototype.utils={getNode:w.getNode};e.compose(t);return e});B(b,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map