/*
 Highcharts JS v8.1.1 (2020-06-09)

 Accessibility module

 (c) 2010-2019 Highsoft AS
 Author: Oystein Moseng

 License: www.highcharts.com/license
*/
(function(x){"object"===typeof module&&module.exports?(x["default"]=x,module.exports=x):"function"===typeof define&&define.amd?define("highcharts/modules/accessibility",["highcharts"],function(r){x(r);x.Highcharts=r;return x}):x("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(x){function r(a,g,q,n){a.hasOwnProperty(g)||(a[g]=n.apply(null,q))}var a=x?x._modules:{};r(a,"modules/accessibility/utils/htmlUtilities.js",[a["parts/Utilities.js"],a["parts/Globals.js"]],function(a,g){function l(a){return a.replace(/&/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")}var n=a.merge,p=g.win,f=p.document;return{addClass:function(a,f){a.classList?a.classList.add(f):0>a.className.indexOf(f)&&(a.className+=f)},escapeStringForHTML:l,getElement:function(a){return f.getElementById(a)},getFakeMouseEvent:function(a){if("function"===typeof p.MouseEvent)return new p.MouseEvent(a);if(f.createEvent){var h=f.createEvent("MouseEvent");if(h.initMouseEvent)return h.initMouseEvent(a,
!0,!0,p,"click"===a?1:0,0,0,0,0,!1,!1,!1,!1,0,null),h}return{type:a}},removeElement:function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},reverseChildNodes:function(a){for(var f=a.childNodes.length;f--;)a.appendChild(a.childNodes[f])},setElAttrs:function(a,f){Object.keys(f).forEach(function(m){var c=f[m];null===c?a.removeAttribute(m):(c=l(""+c),a.setAttribute(m,c))})},stripHTMLTagsFromString:function(a){return"string"===typeof a?a.replace(/<\/?[^>]+(>|$)/g,""):a},visuallyHideElement:function(a){n(!0,
a.style,{position:"absolute",width:"1px",height:"1px",overflow:"hidden",whiteSpace:"nowrap",clip:"rect(1px, 1px, 1px, 1px)",marginTop:"-3px","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",filter:"alpha(opacity=1)",opacity:"0.01"})}}});r(a,"modules/accessibility/utils/chartUtilities.js",[a["modules/accessibility/utils/htmlUtilities.js"],a["parts/Utilities.js"]],function(a,g){function l(a){if(a.points&&a.points.length&&a.points[0].graphic)return a.points[0].graphic.element}function n(a){var c=
l(a);return c&&c.parentNode||a.graph&&a.graph.element||a.group&&a.group.element}function p(a,c){c.setAttribute("aria-hidden",!1);c!==a.renderTo&&c.parentNode&&(Array.prototype.forEach.call(c.parentNode.childNodes,function(e){e.hasAttribute("aria-hidden")||e.setAttribute("aria-hidden",!0)}),p(a,c.parentNode))}var f=a.stripHTMLTagsFromString,h=g.defined,y=g.find;return{getChartTitle:function(a){return f(a.options.title.text||a.langFormat("accessibility.defaultChartTitle",{chart:a}))},getAxisDescription:function(a){return f(a&&
(a.userOptions&&a.userOptions.accessibility&&a.userOptions.accessibility.description||a.axisTitle&&a.axisTitle.textStr||a.options.id||a.categories&&"categories"||a.dateTime&&"Time"||"values"))},getPointFromXY:function(a,c,e){for(var b=a.length,k;b--;)if(k=y(a[b].points||[],function(b){return b.x===c&&b.y===e}))return k},getSeriesFirstPointElement:l,getSeriesFromName:function(a,c){return c?(a.series||[]).filter(function(e){return e.name===c}):a.series},getSeriesA11yElement:n,unhideChartElementFromAT:p,
hideSeriesFromAT:function(a){(a=n(a))&&a.setAttribute("aria-hidden",!0)},scrollToPoint:function(a){var c=a.series.xAxis,e=a.series.yAxis,b=(null===c||void 0===c?0:c.scrollbar)?c:e;if((c=null===b||void 0===b?void 0:b.scrollbar)&&h(c.to)&&h(c.from)){e=c.to-c.from;if(h(b.dataMin)&&h(b.dataMax)){var k=b.toPixels(b.dataMin),d=b.toPixels(b.dataMax);a=(b.toPixels(a["xAxis"===b.coll?"x":"y"]||0)-k)/(d-k)}else a=0;c.updatePosition(a-e/2,a+e/2);x.fireEvent(c,"changed",{from:c.from,to:c.to,trigger:"scrollbar",
DOMEvent:null})}}}});r(a,"modules/accessibility/KeyboardNavigationHandler.js",[a["parts/Utilities.js"]],function(a){function l(a,l){this.chart=a;this.keyCodeMap=l.keyCodeMap||[];this.validate=l.validate;this.init=l.init;this.terminate=l.terminate;this.response={success:1,prev:2,next:3,noHandler:4,fail:5}}var q=a.find;l.prototype={run:function(a){var l=a.which||a.keyCode,f=this.response.noHandler,h=q(this.keyCodeMap,function(a){return-1<a[0].indexOf(l)});h?f=h[1].call(this,l,a):9===l&&(f=this.response[a.shiftKey?
"prev":"next"]);return f}};return l});r(a,"modules/accessibility/utils/EventProvider.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var l=g.addEvent;g=g.extend;var n=function(){this.eventRemovers=[]};g(n.prototype,{addEvent:function(){var g=l.apply(a,arguments);this.eventRemovers.push(g);return g},removeAddedEvents:function(){this.eventRemovers.forEach(function(a){a()});this.eventRemovers=[]}});return n});r(a,"modules/accessibility/utils/DOMElementProvider.js",[a["parts/Globals.js"],
a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g,q){var l=a.win.document;a=g.extend;var p=q.removeElement;q=function(){this.elements=[]};a(q.prototype,{createElement:function(){var a=l.createElement.apply(l,arguments);this.elements.push(a);return a},destroyCreatedElements:function(){this.elements.forEach(function(a){p(a)});this.elements=[]}});return q});r(a,"modules/accessibility/AccessibilityComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],
a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/DOMElementProvider.js"]],function(a,g,q,n,p,f){function h(){}var l=a.win,m=l.document;a=g.extend;var c=g.fireEvent,e=g.merge,b=q.removeElement,k=q.getFakeMouseEvent,d=n.unhideChartElementFromAT;h.prototype={initBase:function(b){this.chart=b;this.eventProvider=new p;this.domElementProvider=new f;this.keyCodes={left:37,right:39,up:38,down:40,enter:13,space:32,esc:27,tab:9}},
addEvent:function(){return this.eventProvider.addEvent.apply(this.eventProvider,arguments)},createElement:function(){return this.domElementProvider.createElement.apply(this.domElementProvider,arguments)},fireEventOnWrappedOrUnwrappedElement:function(b,d){var a=d.type;m.createEvent&&(b.dispatchEvent||b.fireEvent)?b.dispatchEvent?b.dispatchEvent(d):b.fireEvent(a,d):c(b,a,d)},fakeClickEvent:function(b){if(b){var d=k("click");this.fireEventOnWrappedOrUnwrappedElement(b,d)}},addProxyGroup:function(b){this.createOrUpdateProxyContainer();
var d=this.createElement("div");Object.keys(b||{}).forEach(function(a){null!==b[a]&&d.setAttribute(a,b[a])});this.chart.a11yProxyContainer.appendChild(d);return d},createOrUpdateProxyContainer:function(){var b=this.chart,d=b.renderer.box;b.a11yProxyContainer=b.a11yProxyContainer||this.createProxyContainerElement();d.nextSibling!==b.a11yProxyContainer&&b.container.insertBefore(b.a11yProxyContainer,d.nextSibling)},createProxyContainerElement:function(){var b=m.createElement("div");b.className="highcharts-a11y-proxy-container";
return b},createProxyButton:function(b,a,k,c,f){var u=b.element,v=this.createElement("button"),m=e({"aria-label":u.getAttribute("aria-label")},k);Object.keys(m).forEach(function(b){null!==m[b]&&v.setAttribute(b,m[b])});v.className="highcharts-a11y-proxy-button";f&&this.addEvent(v,"click",f);this.setProxyButtonStyle(v);this.updateProxyButtonPosition(v,c||b);this.proxyMouseEventsForButton(u,v);a.appendChild(v);m["aria-hidden"]||d(this.chart,v);return v},getElementPosition:function(b){var d=b.element;
return(b=this.chart.renderTo)&&d&&d.getBoundingClientRect?(d=d.getBoundingClientRect(),b=b.getBoundingClientRect(),{x:d.left-b.left,y:d.top-b.top,width:d.right-d.left,height:d.bottom-d.top}):{x:0,y:0,width:1,height:1}},setProxyButtonStyle:function(b){e(!0,b.style,{"border-width":0,"background-color":"transparent",cursor:"pointer",outline:"none",opacity:.001,filter:"alpha(opacity=1)","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity=1)",zIndex:999,overflow:"hidden",padding:0,margin:0,display:"block",
position:"absolute"})},updateProxyButtonPosition:function(b,d){d=this.getElementPosition(d);e(!0,b.style,{width:(d.width||1)+"px",height:(d.height||1)+"px",left:(d.x||0)+"px",top:(d.y||0)+"px"})},proxyMouseEventsForButton:function(b,d){var a=this;"click touchstart touchend touchcancel touchmove mouseover mouseenter mouseleave mouseout".split(" ").forEach(function(e){a.addEvent(d,e,function(d){var e=a.cloneMouseEvent(d);b&&a.fireEventOnWrappedOrUnwrappedElement(b,e);d.stopPropagation();d.preventDefault()})})},
cloneMouseEvent:function(b){if("function"===typeof l.MouseEvent){var d=new l.MouseEvent(b.type,b);d.touches=b.touches;d.changedTouches=b.changedTouches;return d}return m.createEvent&&(d=m.createEvent("MouseEvent"),d.initMouseEvent)?(d.initMouseEvent(b.type,b.bubbles,b.cancelable,b.view||l,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget),d):k(b.type)},destroyBase:function(){b(this.chart.a11yProxyContainer);this.domElementProvider.destroyCreatedElements();
this.eventProvider.removeAddedEvents()}};a(h.prototype,{init:function(){},getKeyboardNavigation:function(){},onChartUpdate:function(){},onChartRender:function(){},destroy:function(){}});return h});r(a,"modules/accessibility/KeyboardNavigation.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/EventProvider.js"]],function(a,g,q,n){function l(a,b){this.init(a,b)}var f=a.doc,h=a.win,y=g.addEvent,m=g.fireEvent,c=q.getElement;
y(f,"keydown",function(e){27===(e.which||e.keyCode)&&a.charts&&a.charts.forEach(function(b){b&&b.dismissPopupContent&&b.dismissPopupContent()})});a.Chart.prototype.dismissPopupContent=function(){var a=this;m(this,"dismissPopupContent",{},function(){a.tooltip&&a.tooltip.hide(0);a.hideExportMenu()})};l.prototype={init:function(a,b){var e=this,d=this.eventProvider=new n;this.chart=a;this.components=b;this.modules=[];this.currentModuleIx=0;d.addEvent(a.renderTo,"keydown",function(b){return e.onKeydown(b)});
d.addEvent(a.container,"focus",function(b){return e.onFocus(b)});d.addEvent(f,"mouseup",function(){return e.onMouseUp()});d.addEvent(a.renderTo,"mousedown",function(){e.isClickingChart=!0});d.addEvent(a.renderTo,"mouseover",function(){e.pointerIsOverChart=!0});d.addEvent(a.renderTo,"mouseout",function(){e.pointerIsOverChart=!1});this.update();this.modules.length&&this.modules[0].init(1)},update:function(a){var b=this.chart.options.accessibility;b=b&&b.keyboardNavigation;var e=this.components;this.updateContainerTabindex();
b&&b.enabled&&a&&a.length?(this.modules=a.reduce(function(b,a){a=e[a].getKeyboardNavigation();return b.concat(a)},[]),this.updateExitAnchor()):(this.modules=[],this.currentModuleIx=0,this.removeExitAnchor())},onFocus:function(a){var b,e=this.chart;a=a.relatedTarget&&e.container.contains(a.relatedTarget);this.isClickingChart||a||(null===(b=this.modules[0])||void 0===b?void 0:b.init(1))},onMouseUp:function(){delete this.isClickingChart;if(!this.keyboardReset&&!this.pointerIsOverChart){var a=this.chart,
b=this.modules&&this.modules[this.currentModuleIx||0];b&&b.terminate&&b.terminate();a.focusElement&&a.focusElement.removeFocusBorder();this.currentModuleIx=0;this.keyboardReset=!0}},onKeydown:function(a){a=a||h.event;var b,e=this.modules&&this.modules.length&&this.modules[this.currentModuleIx];this.keyboardReset=!1;if(e){var d=e.run(a);d===e.response.success?b=!0:d===e.response.prev?b=this.prev():d===e.response.next&&(b=this.next());b&&(a.preventDefault(),a.stopPropagation())}},prev:function(){return this.move(-1)},
next:function(){return this.move(1)},move:function(a){var b=this.modules&&this.modules[this.currentModuleIx];b&&b.terminate&&b.terminate(a);this.chart.focusElement&&this.chart.focusElement.removeFocusBorder();this.currentModuleIx+=a;if(b=this.modules&&this.modules[this.currentModuleIx]){if(b.validate&&!b.validate())return this.move(a);if(b.init)return b.init(a),!0}this.currentModuleIx=0;0<a?(this.exiting=!0,this.exitAnchor.focus()):this.chart.container.focus();return!1},updateExitAnchor:function(){var a=
c("highcharts-end-of-chart-marker-"+this.chart.index);this.removeExitAnchor();a?(this.makeElementAnExitAnchor(a),this.exitAnchor=a):this.createExitAnchor()},updateContainerTabindex:function(){var a=this.chart.options.accessibility;a=a&&a.keyboardNavigation;a=!(a&&!1===a.enabled);var b=this.chart.container,c=b.getAttribute("tabIndex");a&&!c?b.setAttribute("tabindex","0"):a||"0"!==c||b.removeAttribute("tabindex")},makeElementAnExitAnchor:function(a){a.setAttribute("class","highcharts-exit-anchor");
a.setAttribute("tabindex","0");a.setAttribute("aria-hidden",!1);this.addExitAnchorEventsToEl(a)},createExitAnchor:function(){var a=this.chart,b=this.exitAnchor=f.createElement("div");a.renderTo.appendChild(b);this.makeElementAnExitAnchor(b)},removeExitAnchor:function(){this.exitAnchor&&this.exitAnchor.parentNode&&(this.exitAnchor.parentNode.removeChild(this.exitAnchor),delete this.exitAnchor)},addExitAnchorEventsToEl:function(a){var b=this.chart,e=this;this.eventProvider.addEvent(a,"focus",function(a){a=
a||h.event;a.relatedTarget&&b.container.contains(a.relatedTarget)||e.exiting?e.exiting=!1:(b.renderTo.focus(),a.preventDefault(),e.modules&&e.modules.length&&(e.currentModuleIx=e.modules.length-1,(a=e.modules[e.currentModuleIx])&&a.validate&&!a.validate()?e.prev():a&&a.init(-1)))})},destroy:function(){this.removeExitAnchor();this.eventProvider.removeAddedEvents();"0"===this.chart.container.getAttribute("tabindex")&&this.chart.container.removeAttribute("tabindex")}};return l});r(a,"modules/accessibility/components/LegendComponent.js",
[a["parts/Globals.js"],a["parts/Legend.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g,q,n,p,f){function h(b){var a=b.legend&&b.legend.allItems,d=b.options.legend.accessibility||{};return!(!a||!a.length||b.colorAxis&&b.colorAxis.length||!1===d.enabled)}var l=q.addEvent,m=q.extend,c=q.find,e=q.fireEvent,b=f.stripHTMLTagsFromString,k=f.removeElement;
a.Chart.prototype.highlightLegendItem=function(b){var a=this.legend.allItems,d=this.highlightedLegendItemIx;if(a[b]){a[d]&&e(a[d].legendGroup.element,"mouseout");d=this.legend;var c=d.allItems[b].pageIx,k=d.currentPage;"undefined"!==typeof c&&c+1!==k&&d.scroll(1+c-k);this.setFocusToElement(a[b].legendItem,a[b].a11yProxyElement);e(a[b].legendGroup.element,"mouseover");return!0}return!1};l(g,"afterColorizeItem",function(b){var a=b.item;this.chart.options.accessibility.enabled&&a&&a.a11yProxyElement&&
a.a11yProxyElement.setAttribute("aria-pressed",b.visible?"false":"true")});a=function(){};a.prototype=new n;m(a.prototype,{init:function(){var b=this;this.proxyElementsList=[];this.recreateProxies();this.addEvent(g,"afterScroll",function(){this.chart===b.chart&&(b.updateProxiesPositions(),b.updateLegendItemProxyVisibility(),this.chart.highlightLegendItem(b.highlightedLegendItemIx))});this.addEvent(g,"afterPositionItem",function(a){this.chart===b.chart&&this.chart.renderer&&b.updateProxyPositionForItem(a.item)})},
updateLegendItemProxyVisibility:function(){var b=this.chart.legend,a=b.currentPage||1,e=b.clipHeight||0;(b.allItems||[]).forEach(function(d){var c=d.pageIx||0,k=d._legendItemPos?d._legendItemPos[1]:0,u=d.legendItem?Math.round(d.legendItem.getBBox().height):0;c=k+u-b.pages[c]>e||c!==a-1;d.a11yProxyElement&&(d.a11yProxyElement.style.visibility=c?"hidden":"visible")})},onChartRender:function(){h(this.chart)?this.updateProxiesPositions():this.removeProxies()},updateProxiesPositions:function(){for(var b=
0,a=this.proxyElementsList;b<a.length;b++){var e=a[b];this.updateProxyButtonPosition(e.element,e.posElement)}},updateProxyPositionForItem:function(b){var a=c(this.proxyElementsList,function(a){return a.item===b});a&&this.updateProxyButtonPosition(a.element,a.posElement)},recreateProxies:function(){this.removeProxies();h(this.chart)&&(this.addLegendProxyGroup(),this.proxyLegendItems(),this.updateLegendItemProxyVisibility())},removeProxies:function(){k(this.legendProxyGroup);this.proxyElementsList=
[]},addLegendProxyGroup:function(){var b=this.chart.options.accessibility,a=this.chart.langFormat("accessibility.legend.legendLabel",{});this.legendProxyGroup=this.addProxyGroup({"aria-label":a,role:"all"===b.landmarkVerbosity?"region":null})},proxyLegendItems:function(){var b=this;(this.chart.legend&&this.chart.legend.allItems||[]).forEach(function(a){a.legendItem&&a.legendItem.element&&b.proxyLegendItem(a)})},proxyLegendItem:function(a){if(a.legendItem&&a.legendGroup){var d=this.chart.langFormat("accessibility.legend.legendItem",
{chart:this.chart,itemName:b(a.name)}),e=a.legendGroup.div?a.legendItem:a.legendGroup;a.a11yProxyElement=this.createProxyButton(a.legendItem,this.legendProxyGroup,{tabindex:-1,"aria-pressed":!a.visible,"aria-label":d},e);this.proxyElementsList.push({item:a,element:a.a11yProxyElement,posElement:e})}},getKeyboardNavigation:function(){var b=this.keyCodes,a=this;return new p(this.chart,{keyCodeMap:[[[b.left,b.right,b.up,b.down],function(b){return a.onKbdArrowKey(this,b)}],[[b.enter,b.space],function(){return a.onKbdClick(this)}]],
validate:function(){return a.shouldHaveLegendNavigation()},init:function(b){return a.onKbdNavigationInit(b)}})},onKbdArrowKey:function(b,a){var d=this.keyCodes,e=b.response,c=this.chart,k=c.options.accessibility,m=c.legend.allItems.length;a=a===d.left||a===d.up?-1:1;return c.highlightLegendItem(this.highlightedLegendItemIx+a)?(this.highlightedLegendItemIx+=a,e.success):1<m&&k.keyboardNavigation.wrapAround?(b.init(a),e.success):e[0<a?"next":"prev"]},onKbdClick:function(b){var a=this.chart.legend.allItems[this.highlightedLegendItemIx];
a&&a.a11yProxyElement&&e(a.a11yProxyElement,"click");return b.response.success},shouldHaveLegendNavigation:function(){var b=this.chart,a=b.colorAxis&&b.colorAxis.length,e=(b.options.legend||{}).accessibility||{};return!!(b.legend&&b.legend.allItems&&b.legend.display&&!a&&e.enabled&&e.keyboardNavigation&&e.keyboardNavigation.enabled)},onKbdNavigationInit:function(b){var a=this.chart,d=a.legend.allItems.length-1;b=0<b?0:d;a.highlightLegendItem(b);this.highlightedLegendItemIx=b}});return a});r(a,"modules/accessibility/components/MenuComponent.js",
[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g,q,n,p,f){function h(a){return a.exportSVGElements&&a.exportSVGElements[0]}g=g.extend;var l=p.unhideChartElementFromAT,m=f.removeElement,c=f.getFakeMouseEvent;a.Chart.prototype.showExportMenu=function(){var a=h(this);if(a&&(a=a.element,
a.onclick))a.onclick(c("click"))};a.Chart.prototype.hideExportMenu=function(){var a=this.exportDivElements;a&&this.exportContextMenu&&(a.forEach(function(b){if("highcharts-menu-item"===b.className&&b.onmouseout)b.onmouseout(c("mouseout"))}),this.highlightedExportItemIx=0,this.exportContextMenu.hideMenu(),this.container.focus())};a.Chart.prototype.highlightExportItem=function(a){var b=this.exportDivElements&&this.exportDivElements[a],e=this.exportDivElements&&this.exportDivElements[this.highlightedExportItemIx];
if(b&&"LI"===b.tagName&&(!b.children||!b.children.length)){var d=!!(this.renderTo.getElementsByTagName("g")[0]||{}).focus;b.focus&&d&&b.focus();if(e&&e.onmouseout)e.onmouseout(c("mouseout"));if(b.onmouseover)b.onmouseover(c("mouseover"));this.highlightedExportItemIx=a;return!0}return!1};a.Chart.prototype.highlightLastExportItem=function(){var a;if(this.exportDivElements)for(a=this.exportDivElements.length;a--;)if(this.highlightExportItem(a))return!0;return!1};a=function(){};a.prototype=new q;g(a.prototype,
{init:function(){var a=this.chart,b=this;this.addEvent(a,"exportMenuShown",function(){b.onMenuShown()});this.addEvent(a,"exportMenuHidden",function(){b.onMenuHidden()})},onMenuHidden:function(){var a=this.chart.exportContextMenu;a&&a.setAttribute("aria-hidden","true");this.isExportMenuShown=!1;this.setExportButtonExpandedState("false")},onMenuShown:function(){var a=this.chart,b=a.exportContextMenu;b&&(this.addAccessibleContextMenuAttribs(),l(a,b));this.isExportMenuShown=!0;this.setExportButtonExpandedState("true")},
setExportButtonExpandedState:function(a){var b=this.exportButtonProxy;b&&b.setAttribute("aria-expanded",a)},onChartRender:function(){var a=this.chart,b=a.options.accessibility;m(this.exportProxyGroup);var c=a.options.exporting,d=h(a);c&&!1!==c.enabled&&c.accessibility&&c.accessibility.enabled&&d&&d.element&&(this.exportProxyGroup=this.addProxyGroup("all"===b.landmarkVerbosity?{"aria-label":a.langFormat("accessibility.exporting.exportRegionLabel",{chart:a}),role:"region"}:{}),b=h(this.chart),this.exportButtonProxy=
this.createProxyButton(b,this.exportProxyGroup,{"aria-label":a.langFormat("accessibility.exporting.menuButtonLabel",{chart:a}),"aria-expanded":"false"}))},addAccessibleContextMenuAttribs:function(){var a=this.chart,b=a.exportDivElements;b&&b.length&&(b.forEach(function(a){"LI"!==a.tagName||a.children&&a.children.length?a.setAttribute("aria-hidden","true"):a.setAttribute("tabindex",-1)}),b=b[0].parentNode,b.removeAttribute("aria-hidden"),b.setAttribute("aria-label",a.langFormat("accessibility.exporting.chartMenuLabel",
{chart:a})))},getKeyboardNavigation:function(){var a=this.keyCodes,b=this.chart,c=this;return new n(b,{keyCodeMap:[[[a.left,a.up],function(){return c.onKbdPrevious(this)}],[[a.right,a.down],function(){return c.onKbdNext(this)}],[[a.enter,a.space],function(){return c.onKbdClick(this)}]],validate:function(){return b.exportChart&&!1!==b.options.exporting.enabled&&!1!==b.options.exporting.accessibility.enabled},init:function(){var a=c.exportButtonProxy,e=b.exportingGroup;e&&a&&b.setFocusToElement(e,a)},
terminate:function(){b.hideExportMenu()}})},onKbdPrevious:function(a){var b=this.chart,c=b.options.accessibility;a=a.response;for(var d=b.highlightedExportItemIx||0;d--;)if(b.highlightExportItem(d))return a.success;return c.keyboardNavigation.wrapAround?(b.highlightLastExportItem(),a.success):a.prev},onKbdNext:function(a){var b=this.chart,c=b.options.accessibility;a=a.response;for(var d=(b.highlightedExportItemIx||0)+1;d<b.exportDivElements.length;++d)if(b.highlightExportItem(d))return a.success;
return c.keyboardNavigation.wrapAround?(b.highlightExportItem(0),a.success):a.next},onKbdClick:function(a){var b=this.chart,c=b.exportDivElements[b.highlightedExportItemIx],d=h(b).element;this.isExportMenuShown?this.fakeClickEvent(c):(this.fakeClickEvent(d),b.highlightExportItem(0));return a.response.success}});return a});r(a,"modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js",[a["parts/Chart.js"],a["parts/Globals.js"],a["parts/Point.js"],a["parts/Utilities.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],
a["modules/accessibility/utils/EventProvider.js"],a["modules/accessibility/utils/chartUtilities.js"]],function(a,g,q,n,p,f,h){function l(a){var b=a.index,d=a.series.points,c=d.length;if(d[b]!==a)for(;c--;){if(d[c]===a)return c}else return b}function m(a){var b=a.chart.options.accessibility.keyboardNavigation.seriesNavigation,d=a.options.accessibility||{},c=d.keyboardNavigation;return c&&!1===c.enabled||!1===d.enabled||!1===a.options.enableMouseTracking||!a.visible||b.pointNavigationEnabledThreshold&&
b.pointNavigationEnabledThreshold<=a.points.length}function c(a){var b=a.series.chart.options.accessibility;return a.isNull&&b.keyboardNavigation.seriesNavigation.skipNullPoints||!1===a.visible||m(a.series)}function e(a,b,c,e){var k=Infinity,t=b.points.length,m=function(a){return!(d(a.plotX)&&d(a.plotY))};if(!m(a)){for(;t--;){var f=b.points[t];if(!m(f)&&(f=(a.plotX-f.plotX)*(a.plotX-f.plotX)*(c||1)+(a.plotY-f.plotY)*(a.plotY-f.plotY)*(e||1),f<k)){k=f;var v=t}}return d(v)?b.points[v]:void 0}}function b(a){var b=
!1;delete a.highlightedPoint;return b=a.series.reduce(function(a,b){return a||b.highlightFirstValidPoint()},!1)}function k(a,b){this.keyCodes=b;this.chart=a}var d=n.defined;n=n.extend;var u=h.getPointFromXY,D=h.getSeriesFromName,A=h.scrollToPoint;g.Series.prototype.keyboardMoveVertical=!0;["column","pie"].forEach(function(a){g.seriesTypes[a]&&(g.seriesTypes[a].prototype.keyboardMoveVertical=!1)});q.prototype.highlight=function(){var a=this.series.chart;if(this.isNull)a.tooltip&&a.tooltip.hide(0);
else this.onMouseOver();A(this);this.graphic&&a.setFocusToElement(this.graphic);a.highlightedPoint=this;return this};a.prototype.highlightAdjacentPoint=function(a){var b=this.series,d=this.highlightedPoint,e=d&&l(d)||0,k=d&&d.series.points,t=this.series&&this.series[this.series.length-1];t=t&&t.points&&t.points[t.points.length-1];if(!b[0]||!b[0].points)return!1;if(d){if(b=b[d.series.index+(a?1:-1)],e=k[e+(a?1:-1)],!e&&b&&(e=b.points[a?0:b.points.length-1]),!e)return!1}else e=a?b[0].points[0]:t;return c(e)?
(b=e.series,m(b)?this.highlightedPoint=a?b.points[b.points.length-1]:b.points[0]:this.highlightedPoint=e,this.highlightAdjacentPoint(a)):e.highlight()};g.Series.prototype.highlightFirstValidPoint=function(){var a=this.chart.highlightedPoint,b=(a&&a.series)===this?l(a):0;a=this.points;var d=a.length;if(a&&d){for(var e=b;e<d;++e)if(!c(a[e]))return a[e].highlight();for(;0<=b;--b)if(!c(a[b]))return a[b].highlight()}return!1};a.prototype.highlightAdjacentSeries=function(a){var b,d=this.highlightedPoint;
var c=(b=this.series&&this.series[this.series.length-1])&&b.points&&b.points[b.points.length-1];if(!this.highlightedPoint)return b=a?this.series&&this.series[0]:b,(c=a?b&&b.points&&b.points[0]:c)?c.highlight():!1;b=this.series[d.series.index+(a?-1:1)];if(!b)return!1;c=e(d,b,4);if(!c)return!1;if(m(b))return c.highlight(),a=this.highlightAdjacentSeries(a),a?a:(d.highlight(),!1);c.highlight();return c.series.highlightFirstValidPoint()};a.prototype.highlightAdjacentPointVertical=function(a){var b=this.highlightedPoint,
e=Infinity,k;if(!d(b.plotX)||!d(b.plotY))return!1;this.series.forEach(function(f){m(f)||f.points.forEach(function(t){if(d(t.plotY)&&d(t.plotX)&&t!==b){var m=t.plotY-b.plotY,u=Math.abs(t.plotX-b.plotX);u=Math.abs(m)*Math.abs(m)+u*u*4;f.yAxis&&f.yAxis.reversed&&(m*=-1);!(0>=m&&a||0<=m&&!a||5>u||c(t))&&u<e&&(e=u,k=t)}})});return k?k.highlight():!1};n(k.prototype,{init:function(){var a=this,d=this.chart,c=this.eventProvider=new f;c.addEvent(g.Series,"destroy",function(){return a.onSeriesDestroy(this)});
c.addEvent(d,"afterDrilldown",function(){b(this);this.focusElement&&this.focusElement.removeFocusBorder()});c.addEvent(d,"drilldown",function(b){b=b.point;var d=b.series;a.lastDrilledDownPoint={x:b.x,y:b.y,seriesName:d?d.name:""}});c.addEvent(d,"drillupall",function(){setTimeout(function(){a.onDrillupAll()},10)})},onDrillupAll:function(){var a=this.lastDrilledDownPoint,b=this.chart,c=a&&D(b,a.seriesName),e;a&&c&&d(a.x)&&d(a.y)&&(e=u(c,a.x,a.y));b.container&&b.container.focus();e&&e.highlight&&e.highlight();
b.focusElement&&b.focusElement.removeFocusBorder()},getKeyboardNavigationHandler:function(){var a=this,b=this.keyCodes,d=this.chart,c=d.inverted;return new p(d,{keyCodeMap:[[c?[b.up,b.down]:[b.left,b.right],function(b){return a.onKbdSideways(this,b)}],[c?[b.left,b.right]:[b.up,b.down],function(b){return a.onKbdVertical(this,b)}],[[b.enter,b.space],function(){d.highlightedPoint&&d.highlightedPoint.firePointEvent("click");return this.response.success}]],init:function(b){return a.onHandlerInit(this,
b)},terminate:function(){return a.onHandlerTerminate()}})},onKbdSideways:function(a,b){var d=this.keyCodes;return this.attemptHighlightAdjacentPoint(a,b===d.right||b===d.down)},onKbdVertical:function(a,b){var d=this.chart,c=this.keyCodes;b=b===c.down||b===c.right;c=d.options.accessibility.keyboardNavigation.seriesNavigation;if(c.mode&&"serialize"===c.mode)return this.attemptHighlightAdjacentPoint(a,b);d[d.highlightedPoint&&d.highlightedPoint.series.keyboardMoveVertical?"highlightAdjacentPointVertical":
"highlightAdjacentSeries"](b);return a.response.success},onHandlerInit:function(a,d){var c=this.chart;if(0<d)b(c);else{d=c.series.length;for(var e;d--&&!(c.highlightedPoint=c.series[d].points[c.series[d].points.length-1],e=c.series[d].highlightFirstValidPoint()););}return a.response.success},onHandlerTerminate:function(){var a,b,d=this.chart,c=d.highlightedPoint;null===(a=d.tooltip)||void 0===a?void 0:a.hide(0);null===(b=null===c||void 0===c?void 0:c.onMouseOut)||void 0===b?void 0:b.call(c);delete d.highlightedPoint},
attemptHighlightAdjacentPoint:function(a,b){var d=this.chart,c=d.options.accessibility.keyboardNavigation.wrapAround;return d.highlightAdjacentPoint(b)?a.response.success:c?a.init(b?1:-1):a.response[b?"next":"prev"]},onSeriesDestroy:function(a){var b=this.chart;b.highlightedPoint&&b.highlightedPoint.series===a&&(delete b.highlightedPoint,b.focusElement&&b.focusElement.removeFocusBorder())},destroy:function(){this.eventProvider.removeAddedEvents()}});return k});r(a,"modules/accessibility/components/AnnotationsA11y.js",
[a["parts/Utilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g){function l(a){return(a.annotations||[]).reduce(function(a,b){var c;!1!==(null===(c=b.options)||void 0===c?void 0:c.visible)&&(a=a.concat(b.labels));return a},[])}function n(a){var c,b,k,d,f=null===(b=null===(c=a.options)||void 0===c?void 0:c.accessibility)||void 0===b?void 0:b.description;return f?f:(null===(d=null===(k=a.graphic)||void 0===k?void 0:k.text)||void 0===d?void 0:d.textStr)||""}function p(a){var c,
b,k=null===(b=null===(c=a.options)||void 0===c?void 0:c.accessibility)||void 0===b?void 0:b.description;if(k)return k;c=a.chart;b=n(a);k=a.points.filter(function(a){return!!a.graphic}).map(function(a){var b,d;if(!(d=null===(b=null===a||void 0===a?void 0:a.accessibility)||void 0===b?void 0:b.valueDescription)){var c,e;d=(null===(e=null===(c=null===a||void 0===a?void 0:a.graphic)||void 0===c?void 0:c.element)||void 0===e?void 0:e.getAttribute("aria-label"))||""}a=(null===a||void 0===a?void 0:a.series.name)||
"";return(a?a+", ":"")+"data point "+d}).filter(function(a){return!!a});var d=k.length;a="accessibility.screenReaderSection.annotations.description"+(1<d?"MultiplePoints":d?"SinglePoint":"NoPoints");b={annotationText:b,numPoints:d,annotationPoint:k[0],additionalAnnotationPoints:k.slice(1)};return c.langFormat(a,b)}function f(a){return l(a).map(function(a){return(a=y(m(p(a))))?"<li>"+a+"</li>":""})}var h=a.inArray,y=g.escapeStringForHTML,m=g.stripHTMLTagsFromString;return{getAnnotationsInfoHTML:function(a){var c=
a.annotations;return c&&c.length?"<ul>"+f(a).join(" ")+"</ul>":""},getAnnotationLabelDescription:p,getAnnotationListItems:f,getPointAnnotationTexts:function(a){var c=l(a.series.chart).filter(function(b){return-1<h(a,b.points)});return c.length?c.map(function(a){return""+n(a)}):[]}}});r(a,"modules/accessibility/components/SeriesComponent/SeriesDescriber.js",[a["parts/Utilities.js"],a["modules/accessibility/components/AnnotationsA11y.js"],a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],
a["parts/Tooltip.js"]],function(a,g,q,n,p){function f(a){var b=a.index;return a.series&&a.series.data&&C(b)?x(a.series.data,function(a){return!!(a&&"undefined"!==typeof a.index&&a.index>b&&a.graphic&&a.graphic.element)})||null:null}function h(a){var b=a.chart.options.accessibility.series.pointDescriptionEnabledThreshold;return!!(!1!==b&&a.points&&a.points.length>=b)}function l(a){var b=a.options.accessibility||{};return!h(a)&&!b.exposeAsGroupOnly}function m(a){var b=a.chart.options.accessibility.keyboardNavigation.seriesNavigation;
return!(!a.points||!(a.points.length<b.pointNavigationEnabledThreshold||!1===b.pointNavigationEnabledThreshold))}function c(a,b){var d=a.series.chart,c=d.options.accessibility.point||{};a=a.series.tooltipOptions||{};d=d.options.lang;return t(b)?J(b,c.valueDecimals||a.valueDecimals||-1,d.decimalPoint,d.accessibility.thousandsSep||d.thousandsSep):b}function e(a){var b=(a.options.accessibility||{}).description;return b&&a.chart.langFormat("accessibility.series.description",{description:b,series:a})||
""}function b(a,b){return a.chart.langFormat("accessibility.series."+b+"Description",{name:K(a[b]),series:a})}function k(a){var b=a.series,d=b.chart,c=d.options.accessibility.point||{};if(b.xAxis&&b.xAxis.dateTime)return b=p.prototype.getXDateFormat.call({getDateFormat:p.prototype.getDateFormat,chart:d},a,d.options.tooltip,b.xAxis),c=c.dateFormatter&&c.dateFormatter(a)||c.dateFormat||b,d.time.dateFormat(c,a.x,void 0)}function d(a){var b=k(a),d=(a.series.xAxis||{}).categories&&C(a.category)&&(""+a.category).replace("<br/>",
" "),c=a.id&&0>a.id.indexOf("highcharts-"),e="x, "+a.x;return a.name||b||d||(c?a.id:e)}function u(a,b,d){var e=b||"",k=d||"";return a.series.pointArrayMap.reduce(function(b,d){b+=b.length?", ":"";var f=c(a,z(a[d],a.options[d]));return b+(d+": "+e+f+k)},"")}function D(a){var b=a.series,d=b.chart.options.accessibility.point||{},e=b.tooltipOptions||{},k=d.valuePrefix||e.valuePrefix||"";d=d.valueSuffix||e.valueSuffix||"";e=c(a,a["undefined"!==typeof a.value?"value":"y"]);return a.isNull?b.chart.langFormat("accessibility.series.nullPointValue",
{point:a}):b.pointArrayMap?u(a,k,d):k+e+d}function A(a){var b=a.series,c=b.chart,e=c.options.accessibility.point.valueDescriptionFormat,k=(b=z(b.xAxis&&b.xAxis.options.accessibility&&b.xAxis.options.accessibility.enabled,!c.angular))?d(a):"";a={point:a,index:C(a.index)?a.index+1:"",xDescription:k,value:D(a),separator:b?", ":""};return w(e,a,c)}function v(a){var b=a.series,d=b.chart,c=A(a),e=a.options&&a.options.accessibility&&a.options.accessibility.description;e=e?" "+e:"";b=1<d.series.length&&b.name?
" "+b.name+".":"";d=a.series.chart;var k=I(a),f={point:a,annotations:k};d=k.length?d.langFormat("accessibility.series.pointAnnotationsDescription",f):"";a.accessibility=a.accessibility||{};a.accessibility.valueDescription=c;return c+e+b+(d?" "+d:"")}function r(a){var b=l(a),d=m(a);(b||d)&&a.points.forEach(function(a){var d;if(!(d=a.graphic&&a.graphic.element)&&(d=a.series&&a.series.is("sunburst"),d=a.isNull&&!d)){var c=a.series,e=f(a);c=(d=e&&e.graphic)?d.parentGroup:c.graph||c.group;e=e?{x:z(a.plotX,
e.plotX,0),y:z(a.plotY,e.plotY,0)}:{x:z(a.plotX,0),y:z(a.plotY,0)};e=a.series.chart.renderer.rect(e.x,e.y,1,1);e.attr({"class":"highcharts-a11y-dummy-point",fill:"none",opacity:0,"fill-opacity":0,"stroke-opacity":0});c&&c.element?(a.graphic=e,a.hasDummyGraphic=!0,e.add(c),c.element.insertBefore(e.element,d?d.element:null),d=e.element):d=void 0}d&&(d.setAttribute("tabindex","-1"),d.style.outline="0",b?(e=a.series,c=e.chart.options.accessibility.point||{},e=e.options.accessibility||{},a=F(G(e.pointDescriptionFormatter&&
e.pointDescriptionFormatter(a)||c.descriptionFormatter&&c.descriptionFormatter(a)||v(a))),d.setAttribute("role","img"),d.setAttribute("aria-label",a)):d.setAttribute("aria-hidden",!0))})}function B(a){var d=a.chart,c=d.types||[],k=e(a),f=function(b){return d[b]&&1<d[b].length&&a[b]},m=b(a,"xAxis"),t=b(a,"yAxis"),h={name:a.name||"",ix:a.index+1,numSeries:d.series&&d.series.length,numPoints:a.points&&a.points.length,series:a};c=1<c.length?"Combination":"";return(d.langFormat("accessibility.series.summary."+
a.type+c,h)||d.langFormat("accessibility.series.summary.default"+c,h))+(k?" "+k:"")+(f("yAxis")?" "+t:"")+(f("xAxis")?" "+m:"")}var x=a.find,w=a.format,t=a.isNumber,J=a.numberFormat,z=a.pick,C=a.defined,I=g.getPointAnnotationTexts,F=q.escapeStringForHTML,L=q.reverseChildNodes,G=q.stripHTMLTagsFromString,K=n.getAxisDescription,M=n.getSeriesFirstPointElement,N=n.getSeriesA11yElement,O=n.unhideChartElementFromAT;return{describeSeries:function(a){var b=a.chart,d=M(a),c=N(a),e=b.is3d&&b.is3d();if(c){c.lastChild!==
d||e||L(c);r(a);O(b,c);e=a.chart;b=e.options.chart||{};d=1<e.series.length;e=e.options.accessibility.series.describeSingleSeries;var k=(a.options.accessibility||{}).exposeAsGroupOnly;b.options3d&&b.options3d.enabled&&d||!(d||e||k||h(a))?c.setAttribute("aria-label",""):(b=a.chart.options.accessibility,d=b.landmarkVerbosity,(a.options.accessibility||{}).exposeAsGroupOnly?c.setAttribute("role","img"):"all"===d&&c.setAttribute("role","region"),c.setAttribute("tabindex","-1"),c.style.outline="0",c.setAttribute("aria-label",
F(G(b.series.descriptionFormatter&&b.series.descriptionFormatter(a)||B(a)))))}},defaultPointDescriptionFormatter:v,defaultSeriesDescriptionFormatter:B,getPointA11yTimeDescription:k,getPointXDescription:d,getPointValue:D,getPointValueDescription:A}});r(a,"modules/accessibility/utils/Announcer.js",[a["parts/Globals.js"],a["modules/accessibility/utils/DOMElementProvider.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g,q){var l=q.visuallyHideElement;q=function(){function a(a,h){this.chart=
a;this.domElementProvider=new g;this.announceRegion=this.addAnnounceRegion(h)}a.prototype.destroy=function(){this.domElementProvider.destroyCreatedElements()};a.prototype.announce=function(a){var f=this;this.announceRegion.innerHTML=a;this.clearAnnouncementRegionTimer&&clearTimeout(this.clearAnnouncementRegionTimer);this.clearAnnouncementRegionTimer=setTimeout(function(){f.announceRegion.innerHTML="";delete f.clearAnnouncementRegionTimer},1E3)};a.prototype.addAnnounceRegion=function(a){var f=this.chart.renderTo,
g=this.domElementProvider.createElement("div");g.setAttribute("aria-hidden",!1);g.setAttribute("aria-live",a);l(g);f.insertBefore(g,f.firstChild);return g};return a}();return a.Announcer=q});r(a,"modules/accessibility/components/SeriesComponent/NewDataAnnouncer.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/components/SeriesComponent/SeriesDescriber.js"],a["modules/accessibility/utils/Announcer.js"],a["modules/accessibility/utils/EventProvider.js"]],
function(a,g,q,n,p,f){function h(a){var b=a.series.data.filter(function(b){return a.x===b.x&&a.y===b.y});return 1===b.length?b[0]:a}function l(a,b){var d=(a||[]).concat(b||[]).reduce(function(a,b){a[b.name+b.index]=b;return a},{});return Object.keys(d).map(function(a){return d[a]})}var m=g.extend,c=g.defined,e=q.getChartTitle,b=n.defaultPointDescriptionFormatter,k=n.defaultSeriesDescriptionFormatter;g=function(a){this.chart=a};m(g.prototype,{init:function(){var a=this.chart,b=a.options.accessibility.announceNewData.interruptUser?
"assertive":"polite";this.lastAnnouncementTime=0;this.dirty={allSeries:{}};this.eventProvider=new f;this.announcer=new p(a,b);this.addEventListeners()},destroy:function(){this.eventProvider.removeAddedEvents();this.announcer.destroy()},addEventListeners:function(){var b=this,c=this.chart,e=this.eventProvider;e.addEvent(c,"afterDrilldown",function(){b.lastAnnouncementTime=0});e.addEvent(a.Series,"updatedData",function(){b.onSeriesUpdatedData(this)});e.addEvent(c,"afterAddSeries",function(a){b.onSeriesAdded(a.series)});
e.addEvent(a.Series,"addPoint",function(a){b.onPointAdded(a.point)});e.addEvent(c,"redraw",function(){b.announceDirtyData()})},onSeriesUpdatedData:function(a){var b=this.chart;a.chart===b&&b.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=!0,this.dirty.allSeries[a.name+a.index]=a)},onSeriesAdded:function(a){this.chart.options.accessibility.announceNewData.enabled&&(this.dirty.hasDirty=!0,this.dirty.allSeries[a.name+a.index]=a,this.dirty.newSeries=c(this.dirty.newSeries)?void 0:
a)},onPointAdded:function(a){var b=a.series.chart;this.chart===b&&b.options.accessibility.announceNewData.enabled&&(this.dirty.newPoint=c(this.dirty.newPoint)?void 0:a)},announceDirtyData:function(){var a=this;if(this.chart.options.accessibility.announceNewData&&this.dirty.hasDirty){var b=this.dirty.newPoint;b&&(b=h(b));this.queueAnnouncement(Object.keys(this.dirty.allSeries).map(function(b){return a.dirty.allSeries[b]}),this.dirty.newSeries,b);this.dirty={allSeries:{}}}},queueAnnouncement:function(a,
b,c){var d=this,e=this.chart.options.accessibility.announceNewData;if(e.enabled){var k=+new Date;e=Math.max(0,e.minAnnounceInterval-(k-this.lastAnnouncementTime));a=l(this.queuedAnnouncement&&this.queuedAnnouncement.series,a);if(b=this.buildAnnouncementMessage(a,b,c))this.queuedAnnouncement&&clearTimeout(this.queuedAnnouncementTimer),this.queuedAnnouncement={time:k,message:b,series:a},this.queuedAnnouncementTimer=setTimeout(function(){d&&d.announcer&&(d.lastAnnouncementTime=+new Date,d.announcer.announce(d.queuedAnnouncement.message),
delete d.queuedAnnouncement,delete d.queuedAnnouncementTimer)},e)}},buildAnnouncementMessage:function(d,c,f){var m=this.chart,h=m.options.accessibility.announceNewData;if(h.announcementFormatter&&(d=h.announcementFormatter(d,c,f),!1!==d))return d.length?d:null;d=a.charts&&1<a.charts.length?"Multiple":"Single";d=c?"newSeriesAnnounce"+d:f?"newPointAnnounce"+d:"newDataAnnounce";h=e(m);return m.langFormat("accessibility.announceNewData."+d,{chartTitle:h,seriesDesc:c?k(c):null,pointDesc:f?b(f):null,point:f,
series:c})}});return g});r(a,"modules/accessibility/components/SeriesComponent/forcedMarkers.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function l(a){p(!0,a,{marker:{enabled:!0,states:{normal:{opacity:0}}}})}var n=g.addEvent,p=g.merge;return function(){n(a.Series,"render",function(){var a=this.options,h=!1!==(this.options.accessibility&&this.options.accessibility.enabled);if(h=this.chart.options.accessibility.enabled&&h)h=this.chart.options.accessibility,h=this.points.length<
h.series.pointDescriptionEnabledThreshold||!1===h.series.pointDescriptionEnabledThreshold;if(h){if(a.marker&&!1===a.marker.enabled&&(this.a11yMarkersForced=!0,l(this.options)),this._hasPointMarkers&&this.points&&this.points.length)for(a=this.points.length;a--;){h=this.points[a];var g=h.options;delete h.hasForcedA11yMarker;g.marker&&(g.marker.enabled?(p(!0,g.marker,{states:{normal:{opacity:g.marker.states&&g.marker.states.normal&&g.marker.states.normal.opacity||1}}}),h.hasForcedA11yMarker=!1):(l(g),
h.hasForcedA11yMarker=!0))}}else this.a11yMarkersForced&&(delete this.a11yMarkersForced,(a=this.resetA11yMarkerOptions)&&p(!0,this.options,{marker:{enabled:a.enabled,states:{normal:{opacity:a.states&&a.states.normal&&a.states.normal.opacity}}}}))});n(a.Series,"afterSetOptions",function(a){this.resetA11yMarkerOptions=p(a.options.marker||{},this.userOptions.marker||{})});n(a.Series,"afterRender",function(){if(this.chart.styledMode){if(this.markerGroup)this.markerGroup[this.a11yMarkersForced?"addClass":
"removeClass"]("highcharts-a11y-markers-hidden");this._hasPointMarkers&&this.points&&this.points.length&&this.points.forEach(function(a){a.graphic&&(a.graphic[a.hasForcedA11yMarker?"addClass":"removeClass"]("highcharts-a11y-marker-hidden"),a.graphic[!1===a.hasForcedA11yMarker?"addClass":"removeClass"]("highcharts-a11y-marker-visible"))})}})}});r(a,"modules/accessibility/components/SeriesComponent/SeriesComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],
a["modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js"],a["modules/accessibility/components/SeriesComponent/NewDataAnnouncer.js"],a["modules/accessibility/components/SeriesComponent/forcedMarkers.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/components/SeriesComponent/SeriesDescriber.js"],a["parts/Tooltip.js"]],function(a,g,q,n,p,f,h,y,m){g=g.extend;var c=h.hideSeriesFromAT,e=y.describeSeries;a.SeriesAccessibilityDescriber=y;f();a=function(){};
a.prototype=new q;g(a.prototype,{init:function(){this.newDataAnnouncer=new p(this.chart);this.newDataAnnouncer.init();this.keyboardNavigation=new n(this.chart,this.keyCodes);this.keyboardNavigation.init();this.hideTooltipFromATWhenShown();this.hideSeriesLabelsFromATWhenShown()},hideTooltipFromATWhenShown:function(){var a=this;this.addEvent(m,"refresh",function(){this.chart===a.chart&&this.label&&this.label.element&&this.label.element.setAttribute("aria-hidden",!0)})},hideSeriesLabelsFromATWhenShown:function(){this.addEvent(this.chart,
"afterDrawSeriesLabels",function(){this.series.forEach(function(a){a.labelBySeries&&a.labelBySeries.attr("aria-hidden",!0)})})},onChartRender:function(){this.chart.series.forEach(function(a){!1!==(a.options.accessibility&&a.options.accessibility.enabled)&&a.visible?e(a):c(a)})},getKeyboardNavigation:function(){return this.keyboardNavigation.getKeyboardNavigationHandler()},destroy:function(){this.newDataAnnouncer.destroy();this.keyboardNavigation.destroy()}});return a});r(a,"modules/accessibility/components/ZoomComponent.js",
[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g,q,n,p,f){var h=g.extend,l=g.pick,m=p.unhideChartElementFromAT,c=f.setElAttrs,e=f.removeElement;a.Axis.prototype.panStep=function(a,c){var b=c||3;c=this.getExtremes();var e=(c.max-c.min)/b*a;b=c.max+e;e=c.min+e;var k=b-e;0>a&&e<c.dataMin?
(e=c.dataMin,b=e+k):0<a&&b>c.dataMax&&(b=c.dataMax,e=b-k);this.setExtremes(e,b)};a=function(){};a.prototype=new q;h(a.prototype,{init:function(){var a=this,c=this.chart;["afterShowResetZoom","afterDrilldown","drillupall"].forEach(function(b){a.addEvent(c,b,function(){a.updateProxyOverlays()})})},onChartUpdate:function(){var a=this.chart,c=this;a.mapNavButtons&&a.mapNavButtons.forEach(function(b,e){m(a,b.element);c.setMapNavButtonAttrs(b.element,"accessibility.zoom.mapZoom"+(e?"Out":"In"))})},setMapNavButtonAttrs:function(a,
e){var b=this.chart;e=b.langFormat(e,{chart:b});c(a,{tabindex:-1,role:"button","aria-label":e})},onChartRender:function(){this.updateProxyOverlays()},updateProxyOverlays:function(){var a=this.chart;e(this.drillUpProxyGroup);e(this.resetZoomProxyGroup);a.resetZoomButton&&this.recreateProxyButtonAndGroup(a.resetZoomButton,"resetZoomProxyButton","resetZoomProxyGroup",a.langFormat("accessibility.zoom.resetZoomButton",{chart:a}));a.drillUpButton&&this.recreateProxyButtonAndGroup(a.drillUpButton,"drillUpProxyButton",
"drillUpProxyGroup",a.langFormat("accessibility.drillUpButton",{chart:a,buttonText:a.getDrilldownBackText()}))},recreateProxyButtonAndGroup:function(a,c,d,m){e(this[d]);this[d]=this.addProxyGroup();this[c]=this.createProxyButton(a,this[d],{"aria-label":m,tabindex:-1})},getMapZoomNavigation:function(){var a=this.keyCodes,c=this.chart,d=this;return new n(c,{keyCodeMap:[[[a.up,a.down,a.left,a.right],function(a){return d.onMapKbdArrow(this,a)}],[[a.tab],function(a,b){return d.onMapKbdTab(this,b)}],[[a.space,
a.enter],function(){return d.onMapKbdClick(this)}]],validate:function(){return!!(c.mapZoom&&c.mapNavButtons&&c.mapNavButtons.length)},init:function(a){return d.onMapNavInit(a)}})},onMapKbdArrow:function(a,c){var b=this.keyCodes;this.chart[c===b.up||c===b.down?"yAxis":"xAxis"][0].panStep(c===b.left||c===b.up?-1:1);return a.response.success},onMapKbdTab:function(a,c){var b=this.chart;a=a.response;var e=(c=c.shiftKey)&&!this.focusedMapNavButtonIx||!c&&this.focusedMapNavButtonIx;b.mapNavButtons[this.focusedMapNavButtonIx].setState(0);
if(e)return b.mapZoom(),a[c?"prev":"next"];this.focusedMapNavButtonIx+=c?-1:1;c=b.mapNavButtons[this.focusedMapNavButtonIx];b.setFocusToElement(c.box,c.element);c.setState(2);return a.success},onMapKbdClick:function(a){this.fakeClickEvent(this.chart.mapNavButtons[this.focusedMapNavButtonIx].element);return a.response.success},onMapNavInit:function(a){var b=this.chart,c=b.mapNavButtons[0],e=b.mapNavButtons[1];c=0<a?c:e;b.setFocusToElement(c.box,c.element);c.setState(2);this.focusedMapNavButtonIx=0<
a?0:1},simpleButtonNavigation:function(a,c,d){var b=this.keyCodes,e=this,m=this.chart;return new n(m,{keyCodeMap:[[[b.tab,b.up,b.down,b.left,b.right],function(a,c){return this.response[a===b.tab&&c.shiftKey||a===b.left||a===b.up?"prev":"next"]}],[[b.space,b.enter],function(){var a=d(this,m);return l(a,this.response.success)}]],validate:function(){return m[a]&&m[a].box&&e[c]},init:function(){m.setFocusToElement(m[a].box,e[c])}})},getKeyboardNavigation:function(){return[this.simpleButtonNavigation("resetZoomButton",
"resetZoomProxyButton",function(a,c){c.zoomOut()}),this.simpleButtonNavigation("drillUpButton","drillUpProxyButton",function(a,c){c.drillUp();return a.response.prev}),this.getMapZoomNavigation()]}});return a});r(a,"modules/accessibility/components/RangeSelectorComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/utils/htmlUtilities.js"]],
function(a,g,q,n,p,f){g=g.extend;var h=p.unhideChartElementFromAT,l=f.setElAttrs;a.Chart.prototype.highlightRangeSelectorButton=function(a){var c=this.rangeSelector.buttons,e=this.highlightedRangeSelectorItemIx;"undefined"!==typeof e&&c[e]&&c[e].setState(this.oldRangeSelectorItemState||0);this.highlightedRangeSelectorItemIx=a;return c[a]?(this.setFocusToElement(c[a].box,c[a].element),this.oldRangeSelectorItemState=c[a].state,c[a].setState(2),!0):!1};a=function(){};a.prototype=new q;g(a.prototype,
{onChartUpdate:function(){var a=this.chart,c=this,e=a.rangeSelector;e&&(e.buttons&&e.buttons.length&&e.buttons.forEach(function(b){h(a,b.element);c.setRangeButtonAttrs(b)}),e.maxInput&&e.minInput&&["minInput","maxInput"].forEach(function(b,m){if(b=e[b])h(a,b),c.setRangeInputAttrs(b,"accessibility.rangeSelector."+(m?"max":"min")+"InputLabel")}))},setRangeButtonAttrs:function(a){var c=this.chart;c=c.langFormat("accessibility.rangeSelector.buttonText",{chart:c,buttonText:a.text&&a.text.textStr});l(a.element,
{tabindex:-1,role:"button","aria-label":c})},setRangeInputAttrs:function(a,c){var e=this.chart;l(a,{tabindex:-1,role:"textbox","aria-label":e.langFormat(c,{chart:e})})},getRangeSelectorButtonNavigation:function(){var a=this.chart,c=this.keyCodes,e=this;return new n(a,{keyCodeMap:[[[c.left,c.right,c.up,c.down],function(a){return e.onButtonNavKbdArrowKey(this,a)}],[[c.enter,c.space],function(){return e.onButtonNavKbdClick(this)}]],validate:function(){return a.rangeSelector&&a.rangeSelector.buttons&&
a.rangeSelector.buttons.length},init:function(b){var c=a.rangeSelector.buttons.length-1;a.highlightRangeSelectorButton(0<b?0:c)}})},onButtonNavKbdArrowKey:function(a,c){var e=a.response,b=this.keyCodes,f=this.chart,d=f.options.accessibility.keyboardNavigation.wrapAround;c=c===b.left||c===b.up?-1:1;return f.highlightRangeSelectorButton(f.highlightedRangeSelectorItemIx+c)?e.success:d?(a.init(c),e.success):e[0<c?"next":"prev"]},onButtonNavKbdClick:function(a){a=a.response;var c=this.chart;3!==c.oldRangeSelectorItemState&&
this.fakeClickEvent(c.rangeSelector.buttons[c.highlightedRangeSelectorItemIx].element);return a.success},getRangeSelectorInputNavigation:function(){var a=this.chart,c=this.keyCodes,e=this;return new n(a,{keyCodeMap:[[[c.tab,c.up,c.down],function(a,f){return e.onInputKbdMove(this,a===c.tab&&f.shiftKey||a===c.up?-1:1)}]],validate:function(){return a.rangeSelector&&a.rangeSelector.inputGroup&&"hidden"!==a.rangeSelector.inputGroup.element.getAttribute("visibility")&&!1!==a.options.rangeSelector.inputEnabled&&
a.rangeSelector.minInput&&a.rangeSelector.maxInput},init:function(a){e.onInputNavInit(a)},terminate:function(){e.onInputNavTerminate()}})},onInputKbdMove:function(a,c){var e=this.chart;a=a.response;var b=e.highlightedInputRangeIx+=c;if(1<b||0>b)return a[0<c?"next":"prev"];e.rangeSelector[b?"maxInput":"minInput"].focus();return a.success},onInputNavInit:function(a){var c=this.chart;a=0<a?0:1;c.highlightedInputRangeIx=a;c.rangeSelector[a?"maxInput":"minInput"].focus()},onInputNavTerminate:function(){var a=
this.chart.rangeSelector||{};a.maxInput&&a.hideInput("max");a.minInput&&a.hideInput("min")},getKeyboardNavigation:function(){return[this.getRangeSelectorButtonNavigation(),this.getRangeSelectorInputNavigation()]}});return a});r(a,"modules/accessibility/components/InfoRegionsComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/utils/Announcer.js"],a["modules/accessibility/components/AnnotationsA11y.js"],a["modules/accessibility/utils/chartUtilities.js"],
a["modules/accessibility/utils/htmlUtilities.js"]],function(a,g,q,n,p,f,h){function l(a){return a.replace(/&lt;(h[1-7]|p|div|ul|ol|li)&gt;/g,"<$1>").replace(/&lt;&#x2F;(h[1-7]|p|div|ul|ol|li|a|button)&gt;/g,"</$1>").replace(/&lt;(div|a|button) id=&quot;([a-zA-Z\-0-9#]*?)&quot;&gt;/g,'<$1 id="$2">')}var m=a.doc,c=g.extend,e=g.format,b=g.pick,k=p.getAnnotationsInfoHTML,d=f.unhideChartElementFromAT,u=f.getChartTitle,r=f.getAxisDescription,A=h.addClass,v=h.setElAttrs,x=h.escapeStringForHTML,B=h.stripHTMLTagsFromString,
E=h.getElement,w=h.visuallyHideElement;a.Chart.prototype.getTypeDescription=function(a){var b=a[0],c=this.series&&this.series[0]||{};c={numSeries:this.series.length,numPoints:c.points&&c.points.length,chart:this,mapTitle:c.mapTitle};if(!b)return this.langFormat("accessibility.chartTypes.emptyChart",c);if("map"===b)return c.mapTitle?this.langFormat("accessibility.chartTypes.mapTypeDescription",c):this.langFormat("accessibility.chartTypes.unknownMap",c);if(1<this.types.length)return this.langFormat("accessibility.chartTypes.combinationChart",
c);a=a[0];b=this.langFormat("accessibility.seriesTypeDescriptions."+a,c);var d=this.series&&2>this.series.length?"Single":"Multiple";return(this.langFormat("accessibility.chartTypes."+a+d,c)||this.langFormat("accessibility.chartTypes.default"+d,c))+(b?" "+b:"")};g=function(){};g.prototype=new q;c(g.prototype,{init:function(){var a=this.chart,b=this;this.initRegionsDefinitions();this.addEvent(a,"afterGetTable",function(a){b.onDataTableCreated(a)});this.addEvent(a,"afterViewData",function(a){b.dataTableDiv=
a;setTimeout(function(){b.focusDataTable()},300)});this.announcer=new n(a,"assertive")},initRegionsDefinitions:function(){var a=this;this.screenReaderSections={before:{element:null,buildContent:function(b){var c=b.options.accessibility.screenReaderSection.beforeChartFormatter;return c?c(b):a.defaultBeforeChartFormatter(b)},insertIntoDOM:function(a,b){b.renderTo.insertBefore(a,b.renderTo.firstChild)},afterInserted:function(){"undefined"!==typeof a.sonifyButtonId&&a.initSonifyButton(a.sonifyButtonId);
"undefined"!==typeof a.dataTableButtonId&&a.initDataTableButton(a.dataTableButtonId)}},after:{element:null,buildContent:function(b){var c=b.options.accessibility.screenReaderSection.afterChartFormatter;return c?c(b):a.defaultAfterChartFormatter()},insertIntoDOM:function(a,b){b.renderTo.insertBefore(a,b.container.nextSibling)}}}},onChartRender:function(){var a=this;this.linkedDescriptionElement=this.getLinkedDescriptionElement();this.setLinkedDescriptionAttrs();Object.keys(this.screenReaderSections).forEach(function(b){a.updateScreenReaderSection(b)})},
getLinkedDescriptionElement:function(){var a=this.chart.options.accessibility.linkedDescription;if(a){if("string"!==typeof a)return a;a=e(a,this.chart);a=m.querySelectorAll(a);if(1===a.length)return a[0]}},setLinkedDescriptionAttrs:function(){var a=this.linkedDescriptionElement;a&&(a.setAttribute("aria-hidden","true"),A(a,"highcharts-linked-description"))},updateScreenReaderSection:function(a){var b=this.chart,c=this.screenReaderSections[a],e=c.buildContent(b),f=c.element=c.element||this.createElement("div"),
k=f.firstChild||this.createElement("div");this.setScreenReaderSectionAttribs(f,a);k.innerHTML=e;f.appendChild(k);c.insertIntoDOM(f,b);w(k);d(b,k);c.afterInserted&&c.afterInserted()},setScreenReaderSectionAttribs:function(a,b){var c=this.chart,d=c.langFormat("accessibility.screenReaderSection."+b+"RegionLabel",{chart:c});v(a,{id:"highcharts-screen-reader-region-"+b+"-"+c.index,"aria-label":d});a.style.position="relative";"all"===c.options.accessibility.landmarkVerbosity&&d&&a.setAttribute("role","region")},
defaultBeforeChartFormatter:function(){var b,c=this.chart,d=c.options.accessibility.screenReaderSection.beforeChartFormat,e=this.getAxesDescription(),f=c.sonify&&(null===(b=c.options.sonification)||void 0===b?void 0:b.enabled);b="highcharts-a11y-sonify-data-btn-"+c.index;var h="hc-linkto-highcharts-data-table-"+c.index,m=k(c),g=c.langFormat("accessibility.screenReaderSection.annotations.heading",{chart:c});e={chartTitle:u(c),typeDescription:this.getTypeDescriptionText(),chartSubtitle:this.getSubtitleText(),
chartLongdesc:this.getLongdescText(),xAxisDescription:e.xAxis,yAxisDescription:e.yAxis,playAsSoundButton:f?this.getSonifyButtonText(b):"",viewTableButton:c.getCSV?this.getDataTableButtonText(h):"",annotationsTitle:m?g:"",annotationsList:m};c=a.i18nFormat(d,e,c);this.dataTableButtonId=h;this.sonifyButtonId=b;return l(x(c)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},defaultAfterChartFormatter:function(){var b=this.chart,c=b.options.accessibility.screenReaderSection.afterChartFormat,d={endOfChartMarker:this.getEndOfChartMarkerText()};
b=a.i18nFormat(c,d,b);return l(x(b)).replace(/<(\w+)[^>]*?>\s*<\/\1>/g,"")},getLinkedDescription:function(){var a=this.linkedDescriptionElement;return B(a&&a.innerHTML||"")},getLongdescText:function(){var a=this.chart.options,b=a.caption;b=b&&b.text;var c=this.getLinkedDescription();return a.accessibility.description||c||b||""},getTypeDescriptionText:function(){var a=this.chart;return a.types?a.options.accessibility.typeDescription||a.getTypeDescription(a.types):""},getDataTableButtonText:function(a){var b=
this.chart;b=b.langFormat("accessibility.table.viewAsDataTableButtonText",{chart:b,chartTitle:u(b)});return'<a id="'+a+'">'+b+"</a>"},getSonifyButtonText:function(a){var b,c=this.chart;if(!1===(null===(b=c.options.sonification)||void 0===b?void 0:b.enabled))return"";b=c.langFormat("accessibility.sonification.playAsSoundButtonText",{chart:c,chartTitle:u(c)});return'<button id="'+a+'">'+b+"</button>"},getSubtitleText:function(){var a=this.chart.options.subtitle;return B(a&&a.text||"")},getEndOfChartMarkerText:function(){var a=
this.chart,b=a.langFormat("accessibility.screenReaderSection.endOfChartMarker",{chart:a});return'<div id="highcharts-end-of-chart-marker-'+a.index+'">'+b+"</div>"},onDataTableCreated:function(a){var b=this.chart;b.options.accessibility.enabled&&(this.viewDataTableButton&&this.viewDataTableButton.setAttribute("aria-expanded","true"),a.html=a.html.replace("<table ",'<table tabindex="0" summary="'+b.langFormat("accessibility.table.tableSummary",{chart:b})+'"'))},focusDataTable:function(){var a=this.dataTableDiv;
(a=a&&a.getElementsByTagName("table")[0])&&a.focus&&a.focus()},initSonifyButton:function(a){var b=this,c=this.sonifyButton=E(a),d=this.chart,e=function(a){null===c||void 0===c?void 0:c.setAttribute("aria-hidden","true");null===c||void 0===c?void 0:c.setAttribute("aria-label","");a.preventDefault();a.stopPropagation();a=d.langFormat("accessibility.sonification.playAsSoundClickAnnouncement",{chart:d});b.announcer.announce(a);setTimeout(function(){null===c||void 0===c?void 0:c.removeAttribute("aria-hidden");
null===c||void 0===c?void 0:c.removeAttribute("aria-label");d.sonify&&d.sonify()},1E3)};c&&d&&(v(c,{tabindex:"-1"}),c.onclick=function(a){var b;((null===(b=d.options.accessibility)||void 0===b?void 0:b.screenReaderSection.onPlayAsSoundClick)||e).call(this,a,d)})},initDataTableButton:function(a){var b=this.viewDataTableButton=E(a),c=this.chart;a=a.replace("hc-linkto-","");b&&(v(b,{role:"button",tabindex:"-1","aria-expanded":!!E(a),href:"#"+a}),b.onclick=c.options.accessibility.screenReaderSection.onViewDataTableClick||
function(){c.viewData()})},getAxesDescription:function(){var a=this.chart,c=function(c,d){c=a[c];return 1<c.length||c[0]&&b(c[0].options.accessibility&&c[0].options.accessibility.enabled,d)},d=!!a.types&&0>a.types.indexOf("map"),e=!!a.hasCartesianSeries,f=c("xAxis",!a.angular&&e&&d);c=c("yAxis",e&&d);d={};f&&(d.xAxis=this.getAxisDescriptionText("xAxis"));c&&(d.yAxis=this.getAxisDescriptionText("yAxis"));return d},getAxisDescriptionText:function(a){var b=this,c=this.chart,d=c[a];return c.langFormat("accessibility.axis."+
a+"Description"+(1<d.length?"Plural":"Singular"),{chart:c,names:d.map(function(a){return r(a)}),ranges:d.map(function(a){return b.getAxisRangeDescription(a)}),numAxes:d.length})},getAxisRangeDescription:function(a){var b=a.options||{};return b.accessibility&&"undefined"!==typeof b.accessibility.rangeDescription?b.accessibility.rangeDescription:a.categories?this.getCategoryAxisRangeDesc(a):!a.dateTime||0!==a.min&&0!==a.dataMin?this.getAxisFromToDescription(a):this.getAxisTimeLengthDesc(a)},getCategoryAxisRangeDesc:function(a){var b=
this.chart;return a.dataMax&&a.dataMin?b.langFormat("accessibility.axis.rangeCategories",{chart:b,axis:a,numCategories:a.dataMax-a.dataMin+1}):""},getAxisTimeLengthDesc:function(a){var b=this.chart,c={},d="Seconds";c.Seconds=((a.max||0)-(a.min||0))/1E3;c.Minutes=c.Seconds/60;c.Hours=c.Minutes/60;c.Days=c.Hours/24;["Minutes","Hours","Days"].forEach(function(a){2<c[a]&&(d=a)});var e=c[d].toFixed("Seconds"!==d&&"Minutes"!==d?1:0);return b.langFormat("accessibility.axis.timeRange"+d,{chart:b,axis:a,range:e.replace(".0",
"")})},getAxisFromToDescription:function(a){var b=this.chart,c=b.options.accessibility.screenReaderSection.axisRangeDateFormat,d=function(d){return a.dateTime?b.time.dateFormat(c,a[d]):a[d]};return b.langFormat("accessibility.axis.rangeFromTo",{chart:b,axis:a,rangeFrom:d("min"),rangeTo:d("max")})},destroy:function(){var a;null===(a=this.announcer)||void 0===a?void 0:a.destroy()}});return g});r(a,"modules/accessibility/components/ContainerComponent.js",[a["parts/Globals.js"],a["parts/Utilities.js"],
a["modules/accessibility/utils/htmlUtilities.js"],a["modules/accessibility/utils/chartUtilities.js"],a["modules/accessibility/AccessibilityComponent.js"]],function(a,g,q,n,p){var f=a.win.document;a=g.extend;var h=q.stripHTMLTagsFromString,l=n.unhideChartElementFromAT,m=n.getChartTitle;q=function(){};q.prototype=new p;a(q.prototype,{onChartUpdate:function(){this.handleSVGTitleElement();this.setSVGContainerLabel();this.setGraphicContainerAttrs();this.setRenderToAttrs();this.makeCreditsAccessible()},
handleSVGTitleElement:function(){var a=this.chart,e="highcharts-title-"+a.index,b=h(a.langFormat("accessibility.svgContainerTitle",{chartTitle:m(a)}));if(b.length){var k=this.svgTitleElement=this.svgTitleElement||f.createElementNS("http://www.w3.org/2000/svg","title");k.textContent=b;k.id=e;a.renderTo.insertBefore(k,a.renderTo.firstChild)}},setSVGContainerLabel:function(){var a=this.chart,e=h(a.langFormat("accessibility.svgContainerLabel",{chartTitle:m(a)}));a.renderer.box&&e.length&&a.renderer.box.setAttribute("aria-label",
e)},setGraphicContainerAttrs:function(){var a=this.chart,e=a.langFormat("accessibility.graphicContainerLabel",{chartTitle:m(a)});e.length&&a.container.setAttribute("aria-label",e)},setRenderToAttrs:function(){var a=this.chart;"disabled"!==a.options.accessibility.landmarkVerbosity?a.renderTo.setAttribute("role","region"):a.renderTo.removeAttribute("role");a.renderTo.setAttribute("aria-label",a.langFormat("accessibility.chartContainerLabel",{title:m(a),chart:a}))},makeCreditsAccessible:function(){var a=
this.chart,e=a.credits;e&&(e.textStr&&e.element.setAttribute("aria-label",h(a.langFormat("accessibility.credits",{creditsStr:e.textStr}))),l(a,e.element))},destroy:function(){this.chart.renderTo.setAttribute("aria-hidden",!0)}});return q});r(a,"modules/accessibility/high-contrast-mode.js",[a["parts/Globals.js"]],function(a){var g=a.isMS,l=a.win,n=l.document;return{isHighContrastModeActive:function(){var a=/(Edg)/.test(l.navigator.userAgent);if(l.matchMedia&&a)return l.matchMedia("(-ms-high-contrast: active)").matches;
if(g&&l.getComputedStyle){a=n.createElement("div");a.style.backgroundImage="url(data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==)";n.body.appendChild(a);var f=(a.currentStyle||l.getComputedStyle(a)).backgroundImage;n.body.removeChild(a);return"none"===f}return!1},setHighContrastTheme:function(a){a.highContrastModeActive=!0;var f=a.options.accessibility.highContrastTheme;a.update(f,!1);a.series.forEach(function(a){var h=f.plotOptions[a.type]||{};a.update({color:h.color||"windowText",
colors:[h.color||"windowText"],borderColor:h.borderColor||"window"});a.points.forEach(function(a){a.options&&a.options.color&&a.update({color:h.color||"windowText",borderColor:h.borderColor||"window"},!1)})});a.redraw()}}});r(a,"modules/accessibility/high-contrast-theme.js",[],function(){return{chart:{backgroundColor:"window"},title:{style:{color:"windowText"}},subtitle:{style:{color:"windowText"}},colorAxis:{minColor:"windowText",maxColor:"windowText",stops:[]},colors:["windowText"],xAxis:{gridLineColor:"windowText",
labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},yAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},tooltip:{backgroundColor:"window",borderColor:"windowText",style:{color:"windowText"}},plotOptions:{series:{lineColor:"windowText",fillColor:"window",borderColor:"windowText",
edgeColor:"windowText",borderWidth:1,dataLabels:{connectorColor:"windowText",color:"windowText",style:{color:"windowText",textOutline:"none"}},marker:{lineColor:"windowText",fillColor:"windowText"}},pie:{color:"window",colors:["window"],borderColor:"windowText",borderWidth:1},boxplot:{fillColor:"window"},candlestick:{lineColor:"windowText",fillColor:"window"},errorbar:{fillColor:"window"}},legend:{backgroundColor:"window",itemStyle:{color:"windowText"},itemHoverStyle:{color:"windowText"},itemHiddenStyle:{color:"#555"},
title:{style:{color:"windowText"}}},credits:{style:{color:"windowText"}},labels:{style:{color:"windowText"}},drilldown:{activeAxisLabelStyle:{color:"windowText"},activeDataLabelStyle:{color:"windowText"}},navigation:{buttonOptions:{symbolStroke:"windowText",theme:{fill:"window"}}},rangeSelector:{buttonTheme:{fill:"window",stroke:"windowText",style:{color:"windowText"},states:{hover:{fill:"window",stroke:"windowText",style:{color:"windowText"}},select:{fill:"#444",stroke:"windowText",style:{color:"windowText"}}}},
inputBoxBorderColor:"windowText",inputStyle:{backgroundColor:"window",color:"windowText"},labelStyle:{color:"windowText"}},navigator:{handles:{backgroundColor:"window",borderColor:"windowText"},outlineColor:"windowText",maskFill:"transparent",series:{color:"windowText",lineColor:"windowText"},xAxis:{gridLineColor:"windowText"}},scrollbar:{barBackgroundColor:"#444",barBorderColor:"windowText",buttonArrowColor:"windowText",buttonBackgroundColor:"window",buttonBorderColor:"windowText",rifleColor:"windowText",
trackBackgroundColor:"window",trackBorderColor:"windowText"}}});r(a,"modules/accessibility/options/options.js",[],function(){return{accessibility:{enabled:!0,screenReaderSection:{beforeChartFormat:"<h5>{chartTitle}</h5><div>{typeDescription}</div><div>{chartSubtitle}</div><div>{chartLongdesc}</div><div>{playAsSoundButton}</div><div>{viewTableButton}</div><div>{xAxisDescription}</div><div>{yAxisDescription}</div><div>{annotationsTitle}{annotationsList}</div>",afterChartFormat:"{endOfChartMarker}",
axisRangeDateFormat:"%Y-%m-%d %H:%M:%S"},series:{describeSingleSeries:!1,pointDescriptionEnabledThreshold:200},point:{valueDescriptionFormat:"{index}. {xDescription}{separator}{value}."},landmarkVerbosity:"all",linkedDescription:'*[data-highcharts-chart="{index}"] + .highcharts-description',keyboardNavigation:{enabled:!0,focusBorder:{enabled:!0,hideBrowserFocusOutline:!0,style:{color:"#335cad",lineWidth:2,borderRadius:3},margin:2},order:["series","zoom","rangeSelector","legend","chartMenu"],wrapAround:!0,
seriesNavigation:{skipNullPoints:!0,pointNavigationEnabledThreshold:!1}},announceNewData:{enabled:!1,minAnnounceInterval:5E3,interruptUser:!1}},legend:{accessibility:{enabled:!0,keyboardNavigation:{enabled:!0}}},exporting:{accessibility:{enabled:!0}}}});r(a,"modules/accessibility/options/langOptions.js",[],function(){return{accessibility:{defaultChartTitle:"Chart",chartContainerLabel:"{title}. Highcharts interactive chart.",svgContainerLabel:"Interactive chart",drillUpButton:"{buttonText}",credits:"Chart credits: {creditsStr}",
thousandsSep:",",svgContainerTitle:"",graphicContainerLabel:"",screenReaderSection:{beforeRegionLabel:"Chart screen reader information.",afterRegionLabel:"",annotations:{heading:"Chart annotations summary",descriptionSinglePoint:"{annotationText}. Related to {annotationPoint}",descriptionMultiplePoints:"{annotationText}. Related to {annotationPoint}{ Also related to, #each(additionalAnnotationPoints)}",descriptionNoPoints:"{annotationText}"},endOfChartMarker:"End of interactive chart."},sonification:{playAsSoundButtonText:"Play as sound, {chartTitle}",
playAsSoundClickAnnouncement:"Play"},legend:{legendLabel:"Toggle series visibility",legendItem:"Toggle visibility of {itemName}"},zoom:{mapZoomIn:"Zoom chart",mapZoomOut:"Zoom out chart",resetZoomButton:"Reset zoom"},rangeSelector:{minInputLabel:"Select start date.",maxInputLabel:"Select end date.",buttonText:"Select range {buttonText}"},table:{viewAsDataTableButtonText:"View as data table, {chartTitle}",tableSummary:"Table representation of chart."},announceNewData:{newDataAnnounce:"Updated data for chart {chartTitle}",
newSeriesAnnounceSingle:"New data series: {seriesDesc}",newPointAnnounceSingle:"New data point: {pointDesc}",newSeriesAnnounceMultiple:"New data series in chart {chartTitle}: {seriesDesc}",newPointAnnounceMultiple:"New data point in chart {chartTitle}: {pointDesc}"},seriesTypeDescriptions:{boxplot:"Box plot charts are typically used to display groups of statistical data. Each data point in the chart can have up to 5 values: minimum, lower quartile, median, upper quartile, and maximum.",arearange:"Arearange charts are line charts displaying a range between a lower and higher value for each point.",
areasplinerange:"These charts are line charts displaying a range between a lower and higher value for each point.",bubble:"Bubble charts are scatter charts where each data point also has a size value.",columnrange:"Columnrange charts are column charts displaying a range between a lower and higher value for each point.",errorbar:"Errorbar series are used to display the variability of the data.",funnel:"Funnel charts are used to display reduction of data in stages.",pyramid:"Pyramid charts consist of a single pyramid with item heights corresponding to each point value.",
waterfall:"A waterfall chart is a column chart where each column contributes towards a total end value."},chartTypes:{emptyChart:"Empty chart",mapTypeDescription:"Map of {mapTitle} with {numSeries} data series.",unknownMap:"Map of unspecified region with {numSeries} data series.",combinationChart:"Combination chart with {numSeries} data series.",defaultSingle:"Chart with {numPoints} data {#plural(numPoints, points, point)}.",defaultMultiple:"Chart with {numSeries} data series.",splineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",
splineMultiple:"Line chart with {numSeries} lines.",lineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",lineMultiple:"Line chart with {numSeries} lines.",columnSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",columnMultiple:"Bar chart with {numSeries} data series.",barSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",barMultiple:"Bar chart with {numSeries} data series.",pieSingle:"Pie chart with {numPoints} {#plural(numPoints, slices, slice)}.",
pieMultiple:"Pie chart with {numSeries} pies.",scatterSingle:"Scatter chart with {numPoints} {#plural(numPoints, points, point)}.",scatterMultiple:"Scatter chart with {numSeries} data series.",boxplotSingle:"Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotMultiple:"Boxplot with {numSeries} data series.",bubbleSingle:"Bubble chart with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleMultiple:"Bubble chart with {numSeries} data series."},axis:{xAxisDescriptionSingular:"The chart has 1 X axis displaying {names[0]}. {ranges[0]}",
xAxisDescriptionPlural:"The chart has {numAxes} X axes displaying {#each(names, -1) }and {names[-1]}.",yAxisDescriptionSingular:"The chart has 1 Y axis displaying {names[0]}. {ranges[0]}",yAxisDescriptionPlural:"The chart has {numAxes} Y axes displaying {#each(names, -1) }and {names[-1]}.",timeRangeDays:"Range: {range} days.",timeRangeHours:"Range: {range} hours.",timeRangeMinutes:"Range: {range} minutes.",timeRangeSeconds:"Range: {range} seconds.",rangeFromTo:"Range: {rangeFrom} to {rangeTo}.",rangeCategories:"Range: {numCategories} categories."},
exporting:{chartMenuLabel:"Chart menu",menuButtonLabel:"View chart menu",exportRegionLabel:"Chart menu"},series:{summary:{"default":"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",defaultCombination:"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",line:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",lineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",
spline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",splineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",column:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",columnCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",bar:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",
barCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",pie:"{name}, pie {ix} of {numSeries} with {numPoints} {#plural(numPoints, slices, slice)}.",pieCombination:"{name}, series {ix} of {numSeries}. Pie with {numPoints} {#plural(numPoints, slices, slice)}.",scatter:"{name}, scatter plot {ix} of {numSeries} with {numPoints} {#plural(numPoints, points, point)}.",scatterCombination:"{name}, series {ix} of {numSeries}, scatter plot with {numPoints} {#plural(numPoints, points, point)}.",
boxplot:"{name}, boxplot {ix} of {numSeries} with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotCombination:"{name}, series {ix} of {numSeries}. Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",bubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.",map:"{name}, map {ix} of {numSeries} with {numPoints} {#plural(numPoints, areas, area)}.",
mapCombination:"{name}, series {ix} of {numSeries}. Map with {numPoints} {#plural(numPoints, areas, area)}.",mapline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",maplineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",mapbubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",mapbubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}."},
description:"{description}",xAxisDescription:"X axis, {name}",yAxisDescription:"Y axis, {name}",nullPointValue:"No value",pointAnnotationsDescription:"{Annotation: #each(annotations). }"}}}});r(a,"modules/accessibility/options/deprecatedOptions.js",[a["parts/Utilities.js"]],function(a){function g(a,c,e){for(var b,f=0;f<c.length-1;++f)b=c[f],a=a[b]=y(a[b],{});a[c[c.length-1]]=e}function l(a,c,e,b){function f(a,b){return b.reduce(function(a,b){return a[b]},a)}var d=f(a.options,c),m=f(a.options,e);Object.keys(b).forEach(function(f){var k,
l=d[f];"undefined"!==typeof l&&(g(m,b[f],l),h(32,!1,a,(k={},k[c.join(".")+"."+f]=e.join(".")+"."+b[f].join("."),k)))})}function n(a){var c=a.options.chart||{},e=a.options.accessibility||{};["description","typeDescription"].forEach(function(b){var f;c[b]&&(e[b]=c[b],h(32,!1,a,(f={},f["chart."+b]="accessibility."+b,f)))})}function p(a){a.axes.forEach(function(c){(c=c.options)&&c.description&&(c.accessibility=c.accessibility||{},c.accessibility.description=c.description,h(32,!1,a,{"axis.description":"axis.accessibility.description"}))})}
function f(a){var c={description:["accessibility","description"],exposeElementToA11y:["accessibility","exposeAsGroupOnly"],pointDescriptionFormatter:["accessibility","pointDescriptionFormatter"],skipKeyboardNavigation:["accessibility","keyboardNavigation","enabled"]};a.series.forEach(function(e){Object.keys(c).forEach(function(b){var f,d=e.options[b];"undefined"!==typeof d&&(g(e.options,c[b],"skipKeyboardNavigation"===b?!d:d),h(32,!1,a,(f={},f["series."+b]="series."+c[b].join("."),f)))})})}var h=
a.error,y=a.pick;return function(a){n(a);p(a);a.series&&f(a);l(a,["accessibility"],["accessibility"],{pointDateFormat:["point","dateFormat"],pointDateFormatter:["point","dateFormatter"],pointDescriptionFormatter:["point","descriptionFormatter"],pointDescriptionThreshold:["series","pointDescriptionEnabledThreshold"],pointNavigationThreshold:["keyboardNavigation","seriesNavigation","pointNavigationEnabledThreshold"],pointValueDecimals:["point","valueDecimals"],pointValuePrefix:["point","valuePrefix"],
pointValueSuffix:["point","valueSuffix"],screenReaderSectionFormatter:["screenReaderSection","beforeChartFormatter"],describeSingleSeries:["series","describeSingleSeries"],seriesDescriptionFormatter:["series","descriptionFormatter"],onTableAnchorClick:["screenReaderSection","onViewDataTableClick"],axisRangeDateFormat:["screenReaderSection","axisRangeDateFormat"]});l(a,["accessibility","keyboardNavigation"],["accessibility","keyboardNavigation","seriesNavigation"],{skipNullPoints:["skipNullPoints"],
mode:["mode"]});l(a,["lang","accessibility"],["lang","accessibility"],{legendItem:["legend","legendItem"],legendLabel:["legend","legendLabel"],mapZoomIn:["zoom","mapZoomIn"],mapZoomOut:["zoom","mapZoomOut"],resetZoomButton:["zoom","resetZoomButton"],screenReaderRegionLabel:["screenReaderSection","beforeRegionLabel"],rangeSelectorButton:["rangeSelector","buttonText"],rangeSelectorMaxInput:["rangeSelector","maxInputLabel"],rangeSelectorMinInput:["rangeSelector","minInputLabel"],svgContainerEnd:["screenReaderSection",
"endOfChartMarker"],viewAsDataTable:["table","viewAsDataTableButtonText"],tableSummary:["table","tableSummary"]})}});r(a,"modules/accessibility/a11y-i18n.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){function l(a,h){var f=a.indexOf("#each("),g=a.indexOf("#plural("),c=a.indexOf("["),e=a.indexOf("]");if(-1<f){c=a.slice(f).indexOf(")")+f;var b=a.substring(0,f);g=a.substring(c+1);c=a.substring(f+6,c).split(",");f=Number(c[1]);a="";if(h=h[c[0]])for(f=isNaN(f)?h.length:f,f=0>f?h.length+
f:Math.min(f,h.length),c=0;c<f;++c)a+=b+h[c]+g;return a.length?a:""}if(-1<g){b=a.slice(g).indexOf(")")+g;a=a.substring(g+8,b).split(",");switch(Number(h[a[0]])){case 0:a=p(a[4],a[1]);break;case 1:a=p(a[2],a[1]);break;case 2:a=p(a[3],a[1]);break;default:a=a[1]}a?(h=a,h=h.trim&&h.trim()||h.replace(/^\s+|\s+$/g,"")):h="";return h}return-1<c?(g=a.substring(0,c),a=Number(a.substring(c+1,e)),h=h[g],!isNaN(a)&&h&&(0>a?(b=h[h.length+a],"undefined"===typeof b&&(b=h[0])):(b=h[a],"undefined"===typeof b&&(b=
h[h.length-1]))),"undefined"!==typeof b?b:""):"{"+a+"}"}var n=g.format,p=g.pick;a.i18nFormat=function(a,h,g){var f=function(a,b){a=a.slice(b||0);var c=a.indexOf("{"),d=a.indexOf("}");if(-1<c&&d>c)return{statement:a.substring(c+1,d),begin:b+c+1,end:b+d}},c=[],e=0;do{var b=f(a,e);var k=a.substring(e,b&&b.begin-1);k.length&&c.push({value:k,type:"constant"});b&&c.push({value:b.statement,type:"statement"});e=b?b.end+1:e+1}while(b);c.forEach(function(a){"statement"===a.type&&(a.value=l(a.value,h))});return n(c.reduce(function(a,
b){return a+b.value},""),h,g)};a.Chart.prototype.langFormat=function(f,h){f=f.split(".");for(var g=this.options.lang,l=0;l<f.length;++l)g=g&&g[f[l]];return"string"===typeof g?a.i18nFormat(g,h,this):""}});r(a,"modules/accessibility/focusBorder.js",[a["parts/Globals.js"],a["parts/SVGElement.js"],a["parts/SVGLabel.js"],a["parts/Utilities.js"]],function(a,g,q,n){function l(a){if(!a.focusBorderDestroyHook){var b=a.destroy;a.destroy=function(){var c,e;null===(e=null===(c=a.focusBorder)||void 0===c?void 0:
c.destroy)||void 0===e?void 0:e.call(c);return b.apply(a,arguments)};a.focusBorderDestroyHook=b}}function f(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];a.focusBorderUpdateHooks||(a.focusBorderUpdateHooks={},e.forEach(function(c){c+="Setter";var d=a[c]||a._defaultSetter;a.focusBorderUpdateHooks[c]=d;a[c]=function(){var c=d.apply(a,arguments);a.addFocusBorder.apply(a,b);return c}}))}function h(a){a.focusBorderUpdateHooks&&(Object.keys(a.focusBorderUpdateHooks).forEach(function(b){var c=
a.focusBorderUpdateHooks[b];c===a._defaultSetter?delete a[b]:a[b]=c}),delete a.focusBorderUpdateHooks)}var r=n.addEvent,m=n.extend,c=n.pick,e="x y transform width height r d stroke-width".split(" ");m(g.prototype,{addFocusBorder:function(b,e){this.focusBorder&&this.removeFocusBorder();var d=this.getBBox(),g=c(b,3);d.x+=this.translateX?this.translateX:0;d.y+=this.translateY?this.translateY:0;var h=d.x-g,k=d.y-g,m=d.width+2*g,n=d.height+2*g,p=this instanceof q;if("text"===this.element.nodeName||p){var r=
!!this.rotation;if(p)var w={x:r?1:0,y:0};else h=w=0,"middle"===this.attr("text-anchor")?(w=a.isFirefox&&this.rotation?.25:.5,h=a.isFirefox&&!this.rotation?.75:.5):this.rotation?w=.25:h=.75,w={x:w,y:h};h=+this.attr("x")-d.width*w.x-g;k=+this.attr("y")-d.height*w.y-g;p&&r&&(p=m,m=n,n=p,h=+this.attr("x")-d.height*w.x-g,k=+this.attr("y")-d.width*w.y-g)}this.focusBorder=this.renderer.rect(h,k,m,n,parseInt((e&&e.borderRadius||0).toString(),10)).addClass("highcharts-focus-border").attr({zIndex:99}).add(this.parentGroup);
this.renderer.styledMode||this.focusBorder.attr({stroke:e&&e.stroke,"stroke-width":e&&e.strokeWidth});f(this,b,e);l(this)},removeFocusBorder:function(){h(this);this.focusBorderDestroyHook&&(this.destroy=this.focusBorderDestroyHook,delete this.focusBorderDestroyHook);this.focusBorder&&(this.focusBorder.destroy(),delete this.focusBorder)}});a.Chart.prototype.renderFocusBorder=function(){var a=this.focusElement,c=this.options.accessibility.keyboardNavigation.focusBorder;a&&(a.removeFocusBorder(),c.enabled&&
a.addFocusBorder(c.margin,{stroke:c.style.color,strokeWidth:c.style.lineWidth,borderRadius:c.style.borderRadius}))};a.Chart.prototype.setFocusToElement=function(a,c){var b=this.options.accessibility.keyboardNavigation.focusBorder;(c=c||a.element)&&c.focus&&(c.hcEvents&&c.hcEvents.focusin||r(c,"focusin",function(){}),c.focus(),b.hideBrowserFocusOutline&&(c.style.outline="none"));this.focusElement&&this.focusElement.removeFocusBorder();this.focusElement=a;this.renderFocusBorder()}});r(a,"modules/accessibility/accessibility.js",
[a["modules/accessibility/utils/chartUtilities.js"],a["parts/Globals.js"],a["modules/accessibility/KeyboardNavigationHandler.js"],a["parts/Options.js"],a["parts/Point.js"],a["parts/Utilities.js"],a["modules/accessibility/AccessibilityComponent.js"],a["modules/accessibility/KeyboardNavigation.js"],a["modules/accessibility/components/LegendComponent.js"],a["modules/accessibility/components/MenuComponent.js"],a["modules/accessibility/components/SeriesComponent/SeriesComponent.js"],a["modules/accessibility/components/ZoomComponent.js"],
a["modules/accessibility/components/RangeSelectorComponent.js"],a["modules/accessibility/components/InfoRegionsComponent.js"],a["modules/accessibility/components/ContainerComponent.js"],a["modules/accessibility/high-contrast-mode.js"],a["modules/accessibility/high-contrast-theme.js"],a["modules/accessibility/options/options.js"],a["modules/accessibility/options/langOptions.js"],a["modules/accessibility/options/deprecatedOptions.js"]],function(a,g,q,n,p,f,h,r,m,c,e,b,k,d,u,x,A,v,H,B){function l(a){this.init(a)}
var w=f.addEvent,t=f.extend,y=f.fireEvent,z=f.merge,C=g.win.document;z(!0,n.defaultOptions,v,{accessibility:{highContrastTheme:A},lang:H});g.A11yChartUtilities=a;g.KeyboardNavigationHandler=q;g.AccessibilityComponent=h;l.prototype={init:function(a){this.chart=a;C.addEventListener&&a.renderer.isSVG?(B(a),this.initComponents(),this.keyboardNavigation=new r(a,this.components),this.update()):a.renderTo.setAttribute("aria-hidden",!0)},initComponents:function(){var a=this.chart,f=a.options.accessibility;
this.components={container:new u,infoRegions:new d,legend:new m,chartMenu:new c,rangeSelector:new k,series:new e,zoom:new b};f.customComponents&&t(this.components,f.customComponents);var g=this.components;this.getComponentOrder().forEach(function(b){g[b].initBase(a);g[b].init()})},getComponentOrder:function(){if(!this.components)return[];if(!this.components.series)return Object.keys(this.components);var a=Object.keys(this.components).filter(function(a){return"series"!==a});return["series"].concat(a)},
update:function(){var a=this.components,b=this.chart,c=b.options.accessibility;y(b,"beforeA11yUpdate");b.types=this.getChartTypes();this.getComponentOrder().forEach(function(c){a[c].onChartUpdate();y(b,"afterA11yComponentUpdate",{name:c,component:a[c]})});this.keyboardNavigation.update(c.keyboardNavigation.order);!b.highContrastModeActive&&x.isHighContrastModeActive()&&x.setHighContrastTheme(b);y(b,"afterA11yUpdate",{accessibility:this})},destroy:function(){var a=this.chart||{},b=this.components;
Object.keys(b).forEach(function(a){b[a].destroy();b[a].destroyBase()});this.keyboardNavigation&&this.keyboardNavigation.destroy();a.renderTo&&a.renderTo.setAttribute("aria-hidden",!0);a.focusElement&&a.focusElement.removeFocusBorder()},getChartTypes:function(){var a={};this.chart.series.forEach(function(b){a[b.type]=1});return Object.keys(a)}};g.Chart.prototype.updateA11yEnabled=function(){var a=this.accessibility,b=this.options.accessibility;b&&b.enabled?a?a.update():this.accessibility=new l(this):
a?(a.destroy&&a.destroy(),delete this.accessibility):this.renderTo.setAttribute("aria-hidden",!0)};w(g.Chart,"render",function(a){this.a11yDirty&&this.renderTo&&(delete this.a11yDirty,this.updateA11yEnabled());var b=this.accessibility;b&&b.getComponentOrder().forEach(function(a){b.components[a].onChartRender()})});w(g.Chart,"update",function(a){if(a=a.options.accessibility)a.customComponents&&(this.options.accessibility.customComponents=a.customComponents,delete a.customComponents),z(!0,this.options.accessibility,
a),this.accessibility&&this.accessibility.destroy&&(this.accessibility.destroy(),delete this.accessibility);this.a11yDirty=!0});w(p,"update",function(){this.series.chart.accessibility&&(this.series.chart.a11yDirty=!0)});["addSeries","init"].forEach(function(a){w(g.Chart,a,function(){this.a11yDirty=!0})});["update","updatedData","remove"].forEach(function(a){w(g.Series,a,function(){this.chart.accessibility&&(this.chart.a11yDirty=!0)})});["afterDrilldown","drillupall"].forEach(function(a){w(g.Chart,
a,function(){this.accessibility&&this.accessibility.update()})});w(g.Chart,"destroy",function(){this.accessibility&&this.accessibility.destroy()})});r(a,"masters/modules/accessibility.src.js",[],function(){})});
//# sourceMappingURL=accessibility.js.map