/*
 Highcharts JS v8.1.1 (2020-06-09)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(v){"object"===typeof module&&module.exports?(v["default"]=v,module.exports=v):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(r){v(r);v.Highcharts=r;return v}):v("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(v){function r(c,e,n,g){c.hasOwnProperty(e)||(c[e]=g.apply(null,n))}var c=v?v._modules:{};r(c,"annotations/eventEmitterMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,e){var q=e.addEvent,g=e.fireEvent,
d=e.inArray,a=e.objectEach,w=e.pick,C=e.removeEvent;return{addEvents:function(){var b=this,k=function(k){q(k,v.isTouchDevice?"touchstart":"mousedown",function(k){b.onMouseDown(k)})};k(this.graphic.element);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&k(b.graphic.text.element)});a(b.options.events,function(k,a){var l=function(f){"click"===a&&b.cancelClick||k.call(b,b.chart.pointer.normalize(f),b.target)};if(-1===d(a,b.nonDOMEvents||[]))b.graphic.on(a,l);else q(b,a,l)});if(b.options.draggable&&
(q(b,v.isTouchDevice?"touchmove":"drag",b.onDrag),!b.graphic.renderer.styledMode)){var m={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[b.options.draggable]};b.graphic.css(m);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&b.graphic.text.css(m)})}b.isUpdating||g(b,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(b){var k=this,a=k.chart.pointer;b.preventDefault&&
b.preventDefault();if(2!==b.button){b=a.normalize(b);var A=b.chartX;var l=b.chartY;k.cancelClick=!1;k.chart.hasDraggedAnnotation=!0;k.removeDrag=q(c.doc,v.isTouchDevice?"touchmove":"mousemove",function(b){k.hasDragged=!0;b=a.normalize(b);b.prevChartX=A;b.prevChartY=l;g(k,"drag",b);A=b.chartX;l=b.chartY});k.removeMouseUp=q(c.doc,v.isTouchDevice?"touchend":"mouseup",function(b){k.cancelClick=k.hasDragged;k.hasDragged=!1;k.chart.hasDraggedAnnotation=!1;g(w(k.target,k),"afterUpdate");k.onMouseUp(b)})}},
onMouseUp:function(b){var k=this.chart;b=this.target||this;var a=k.options.annotations;k=k.annotations.indexOf(b);this.removeDocEvents();a[k]=b.options},onDrag:function(b){if(this.chart.isInsidePlot(b.chartX-this.chart.plotLeft,b.chartY-this.chart.plotTop)){var a=this.mouseMoveToTranslation(b);"x"===this.options.draggable&&(a.y=0);"y"===this.options.draggable&&(a.x=0);this.points.length?this.translate(a.x,a.y):(this.shapes.forEach(function(b){b.translate(a.x,a.y)}),this.labels.forEach(function(b){b.translate(a.x,
a.y)}));this.redraw(!1)}},mouseMoveToRadians:function(b,a,m){var k=b.prevChartY-m,l=b.prevChartX-a;m=b.chartY-m;b=b.chartX-a;this.chart.inverted&&(a=l,l=k,k=a,a=b,b=m,m=a);return Math.atan2(m,b)-Math.atan2(k,l)},mouseMoveToTranslation:function(b){var a=b.chartX-b.prevChartX;b=b.chartY-b.prevChartY;if(this.chart.inverted){var m=b;b=a;a=m}return{x:a,y:b}},mouseMoveToScale:function(b,a,m){a=(b.chartX-a||1)/(b.prevChartX-a||1);b=(b.chartY-m||1)/(b.prevChartY-m||1);this.chart.inverted&&(m=b,b=a,a=m);return{x:a,
y:b}},destroy:function(){this.removeDocEvents();C(this);this.hcEvents=null}}});r(c,"annotations/ControlPoint.js",[c["parts/Utilities.js"],c["annotations/eventEmitterMixin.js"]],function(c,e){var q=c.merge,g=c.pick;return function(){function d(a,w,d,b){this.addEvents=e.addEvents;this.graphic=void 0;this.mouseMoveToRadians=e.mouseMoveToRadians;this.mouseMoveToScale=e.mouseMoveToScale;this.mouseMoveToTranslation=e.mouseMoveToTranslation;this.onDrag=e.onDrag;this.onMouseDown=e.onMouseDown;this.onMouseUp=
e.onMouseUp;this.removeDocEvents=e.removeDocEvents;this.nonDOMEvents=["drag"];this.chart=a;this.target=w;this.options=d;this.index=g(d.index,b)}d.prototype.setVisibility=function(a){this.graphic.attr("visibility",a?"visible":"hidden");this.options.visible=a};d.prototype.render=function(){var a=this.chart,w=this.options;this.graphic=a.renderer.symbol(w.symbol,0,0,w.width,w.height).add(a.controlPointsGroup).css(w.style);this.setVisibility(w.visible);this.addEvents()};d.prototype.redraw=function(a){this.graphic[a?
"animate":"attr"](this.options.positioner.call(this,this.target))};d.prototype.destroy=function(){e.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};d.prototype.update=function(a){var w=this.chart,d=this.target,b=this.index;a=q(!0,this.options,a);this.destroy();this.constructor(w,d,a,b);this.render(w.controlPointsGroup);this.redraw()};return d}()});r(c,"annotations/MockPoint.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,
e){var q=e.defined,g=e.fireEvent;return function(){function d(a,d,e){this.y=this.x=this.plotY=this.plotX=this.isInside=void 0;this.mock=!0;this.series={visible:!0,chart:a,getPlotBox:c.Series.prototype.getPlotBox};this.target=d||null;this.options=e;this.applyOptions(this.getOptions())}d.fromPoint=function(a){return new d(a.series.chart,null,{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis})};d.pointToPixels=function(a,d){var c=a.series,b=c.chart,k=a.plotX,m=a.plotY;b.inverted&&(a.mock?(k=a.plotY,
m=a.plotX):(k=b.plotWidth-a.plotY,m=b.plotHeight-a.plotX));c&&!d&&(a=c.getPlotBox(),k+=a.translateX,m+=a.translateY);return{x:k,y:m}};d.pointToOptions=function(a){return{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis}};d.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};d.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};d.prototype.applyOptions=function(a){this.command=a.command;this.setAxis(a,"x");this.setAxis(a,
"y");this.refresh()};d.prototype.setAxis=function(a,d){d+="Axis";a=a[d];var e=this.series.chart;this.series[d]=a instanceof c.Axis?a:q(a)?e[d][a]||e.get(a):null};d.prototype.toAnchor=function(){var a=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(a[0]=this.plotY,a[1]=this.plotX);return a};d.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};d.prototype.isInsidePlot=function(){var a=this.plotX,d=this.plotY,c=this.series.xAxis,b=this.series.yAxis,k={x:a,y:d,isInsidePlot:!0};
c&&(k.isInsidePlot=q(a)&&0<=a&&a<=c.len);b&&(k.isInsidePlot=k.isInsidePlot&&q(d)&&0<=d&&d<=b.len);g(this.series.chart,"afterIsInsidePlot",k);return k.isInsidePlot};d.prototype.refresh=function(){var a=this.series,d=a.xAxis;a=a.yAxis;var c=this.getOptions();d?(this.x=c.x,this.plotX=d.toPixels(c.x,!0)):(this.x=null,this.plotX=c.x);a?(this.y=c.y,this.plotY=a.toPixels(c.y,!0)):(this.y=null,this.plotY=c.y);this.isInside=this.isInsidePlot()};d.prototype.translate=function(a,d,c,b){this.hasDynamicOptions()||
(this.plotX+=c,this.plotY+=b,this.refreshOptions())};d.prototype.scale=function(a,d,c,b){if(!this.hasDynamicOptions()){var k=this.plotY*b;this.plotX=(1-c)*a+this.plotX*c;this.plotY=(1-b)*d+k;this.refreshOptions()}};d.prototype.rotate=function(a,d,c){if(!this.hasDynamicOptions()){var b=Math.cos(c);c=Math.sin(c);var k=this.plotX,m=this.plotY;k-=a;m-=d;this.plotX=k*b-m*c+a;this.plotY=k*c+m*b+d;this.refreshOptions()}};d.prototype.refreshOptions=function(){var a=this.series,d=a.xAxis;a=a.yAxis;this.x=
this.options.x=d?this.options.x=d.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=a?a.toValue(this.plotY,!0):this.plotY};return d}()});r(c,"annotations/controllable/controllableMixin.js",[c["annotations/ControlPoint.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"],c["parts/Utilities.js"]],function(c,e,n,g){var d=g.isObject,a=g.isString,q=g.merge,C=g.splat;return{init:function(b,a,d){this.annotation=b;this.chart=b.chart;this.options=a;this.points=[];this.controlPoints=[];this.index=
d;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var b=this.options;return b.points||b.point&&C(b.point)},attrsFromOptions:function(b){var a=this.constructor.attrsMap,d={},c,l=this.chart.styledMode;for(c in b){var e=a[c];!e||l&&-1!==["fill","stroke","stroke-width"].indexOf(e)||(d[e]=b[c])}return d},anchor:function(b){var a=b.series.getPlotBox();b=b.mock?b.toAnchor():n.prototype.getAnchor.call({chart:b.series.chart},
b);b={x:b[0]+(this.options.x||0),y:b[1]+(this.options.y||0),height:b[2]||0,width:b[3]||0};return{relativePosition:b,absolutePosition:q(b,{x:b.x+a.translateX,y:b.y+a.translateY})}},point:function(b,k){if(b&&b.series)return b;k&&null!==k.series||(d(b)?k=new e(this.chart,this,b):a(b)?k=this.chart.get(b)||null:"function"===typeof b&&(k=b.call(k,this),k=k.series?k:new e(this.chart,this,b)));return k},linkPoints:function(){var b=this.getPointsOptions(),a=this.points,d=b&&b.length||0,c;for(c=0;c<d;c++){var l=
this.point(b[c],a[c]);if(!l){a.length=0;return}l.mock&&l.refresh();a[c]=l}return a},addControlPoints:function(){var b=this.options.controlPoints;(b||[]).forEach(function(a,d){a=q(this.options.controlPointOptions,a);a.index||(a.index=d);b[d]=a;this.controlPoints.push(new c(this.chart,this,a))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(b){this.controlPoints.forEach(function(b){b.render()})},redraw:function(b){this.controlPoints.forEach(function(a){a.redraw(b)})},transform:function(b,
a,d,c,l){if(this.chart.inverted){var k=a;a=d;d=k}this.points.forEach(function(f,h){this.transformPoint(b,a,d,c,l,h)},this)},transformPoint:function(b,a,d,c,l,g){var f=this.points[g];f.mock||(f=this.points[g]=e.fromPoint(f));f[b](a,d,c,l)},translate:function(b,a){this.transform("translate",null,null,b,a)},translatePoint:function(b,a,d){this.transformPoint("translate",null,null,b,a,d)},translateShape:function(b,a){var d=this.annotation.chart,c=this.annotation.userOptions,l=d.annotations.indexOf(this.annotation);
d=d.options.annotations[l];this.translatePoint(b,a,0);d[this.collection][this.index].point=this.options.point;c[this.collection][this.index].point=this.options.point},rotate:function(b,a,d){this.transform("rotate",b,a,d)},scale:function(b,a,d,c){this.transform("scale",b,a,d,c)},setControlPointsVisibility:function(a){this.controlPoints.forEach(function(b){b.setVisibility(a)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());
this.controlPoints.forEach(function(a){a.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=null)},update:function(a){var b=this.annotation;a=q(!0,this.options,a);var d=this.graphic.parentGroup;this.destroy();this.constructor(b,a);this.render(d);this.redraw()}}});r(c,"annotations/controllable/markerMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,e){var q=e.addEvent,g=e.defined,d=e.merge,a=e.objectEach,w=e.uniqueKey,C={arrow:{tagName:"marker",
render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};c.SVGRenderer.prototype.addMarker=function(a,c){var b={id:a},k={stroke:c.color||"none",fill:c.color||"rgba(0, 0, 0, 0.75)"};b.children=c.children.map(function(a){return d(k,a)});c=this.definition(d(!0,
{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},c,b));c.id=a;return c};e=function(a){return function(b){this.attr(a,"url(#"+b+")")}};e={markerEndSetter:e("marker-end"),markerStartSetter:e("marker-start"),setItemMarkers:function(a){var b=a.options,c=a.chart,e=c.options.defs,l=b.fill,q=g(l)&&"none"!==l?l:b.stroke;["markerStart","markerEnd"].forEach(function(f){var h=b[f],l;if(h){for(l in e){var k=e[l];if(h===k.id&&"marker"===k.tagName){var p=k;break}}p&&(h=a[f]=c.renderer.addMarker((b.id||
w())+"-"+p.id,d(p,{color:q})),a.attr(f,h.attr("id")))}})}};q(c.Chart,"afterGetContainer",function(){this.options.defs=d(C,this.options.defs||{});a(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});return e});r(c,"annotations/controllable/ControllablePath.js",[c["annotations/controllable/controllableMixin.js"],c["parts/Globals.js"],c["annotations/controllable/markerMixin.js"],c["parts/Utilities.js"]],function(c,e,n,g){var d=g.extend;g=g.merge;
var a="rgba(192,192,192,"+(e.svg?.0001:.002)+")";e=function(a,c,b){this.init(a,c,b);this.collection="shapes"};e.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};g(!0,e.prototype,c,{type:"path",setMarkers:n.setItemMarkers,toD:function(){var a=this.options.d;if(a)return"function"===typeof a?a.call(this):a;a=this.points;var c=a.length,b=c,d=a[0],e=b&&this.anchor(d).absolutePosition,g=0,l=[];if(e)for(l.push(["M",e.x,e.y]);++g<c&&b;)d=a[g],b=d.command||
"L",e=this.anchor(d).absolutePosition,"M"===b?l.push([b,e.x,e.y]):"L"===b?l.push([b,e.x,e.y]):"Z"===b&&l.push([b]),b=d.series.visible;return b?this.chart.renderer.crispLine(l,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return c.shouldBeDrawn.call(this)||!!this.options.d},render:function(e){var g=this.options,b=this.attrsFromOptions(g);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(b).add(e);g.className&&this.graphic.addClass(g.className);this.tracker=this.annotation.chart.renderer.path([["M",
0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(e);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:a,fill:a,"stroke-width":this.graphic.strokeWidth()+2*g.snap});c.render.call(this);d(this.graphic,{markerStartSetter:n.markerStartSetter,markerEndSetter:n.markerEndSetter});this.setMarkers(this)},redraw:function(a){var d=this.toD(),b=a?"animate":"attr";d?(this.graphic[b]({d:d}),this.tracker[b]({d:d})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));
this.graphic.placed=this.tracker.placed=!!d;c.redraw.call(this,a)}});return e});r(c,"annotations/controllable/ControllableRect.js",[c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"],c["parts/Utilities.js"]],function(c,e,n){n=n.merge;var g=function(c,a,e){this.init(c,a,e);this.collection="shapes"};g.attrsMap=n(e.attrsMap,{width:"width",height:"height"});n(!0,g.prototype,c,{type:"rect",translate:c.translateShape,render:function(d){var a=this.attrsFromOptions(this.options);
this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(a).add(d);c.render.call(this)},redraw:function(d){var a=this.anchor(this.points[0]).absolutePosition;if(a)this.graphic[d?"animate":"attr"]({x:a.x,y:a.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!a;c.redraw.call(this,d)}});return g});r(c,"annotations/controllable/ControllableCircle.js",[c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"],
c["parts/Utilities.js"]],function(c,e,n){n=n.merge;var g=function(c,a,e){this.init(c,a,e);this.collection="shapes"};g.attrsMap=n(e.attrsMap,{r:"r"});n(!0,g.prototype,c,{type:"circle",translate:c.translateShape,render:function(d){var a=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(a).add(d);c.render.call(this)},redraw:function(d){var a=this.anchor(this.points[0]).absolutePosition;if(a)this.graphic[d?"animate":"attr"]({x:a.x,y:a.y,r:this.options.r});
else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!a;c.redraw.call(this,d)},setRadius:function(c){this.options.r=c}});return g});r(c,"annotations/controllable/ControllableLabel.js",[c["annotations/controllable/controllableMixin.js"],c["parts/Globals.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"],c["parts/Utilities.js"]],function(c,e,n,g,d){var a=d.extend,q=d.format,r=d.isNumber,b=d.merge,k=d.pick,m=function(a,b,c){this.init(a,b,c);this.collection="labels"};m.shapesWithoutBackground=
["connector"];m.alignedPosition=function(a,b){var c=a.align,f=a.verticalAlign,h=(b.x||0)+(a.x||0),d=(b.y||0)+(a.y||0),l,e;"right"===c?l=1:"center"===c&&(l=2);l&&(h+=(b.width-(a.width||0))/l);"bottom"===f?e=1:"middle"===f&&(e=2);e&&(d+=(b.height-(a.height||0))/e);return{x:Math.round(h),y:Math.round(d)}};m.justifiedOptions=function(a,b,c,f){var h=c.align,d=c.verticalAlign,e=b.box?0:b.padding||0,l=b.getBBox();b={align:h,verticalAlign:d,x:c.x,y:c.y,width:b.width,height:b.height};c=f.x-a.plotLeft;var t=
f.y-a.plotTop;f=c+e;0>f&&("right"===h?b.align="left":b.x=-f);f=c+l.width-e;f>a.plotWidth&&("left"===h?b.align="right":b.x=a.plotWidth-f);f=t+e;0>f&&("bottom"===d?b.verticalAlign="top":b.y=-f);f=t+l.height-e;f>a.plotHeight&&("top"===d?b.verticalAlign="bottom":b.y=a.plotHeight-f);return b};m.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};b(!0,m.prototype,c,{translatePoint:function(a,b){c.translatePoint.call(this,a,
b,0)},translate:function(a,b){var c=this.annotation.chart,f=this.annotation.userOptions,h=c.annotations.indexOf(this.annotation);h=c.options.annotations[h];c.inverted&&(c=a,a=b,b=c);this.options.x+=a;this.options.y+=b;h[this.collection][this.index].x=this.options.x;h[this.collection][this.index].y=this.options.y;f[this.collection][this.index].x=this.options.x;f[this.collection][this.index].y=this.options.y},render:function(a){var b=this.options,d=this.attrsFromOptions(b),f=b.style;this.graphic=this.annotation.chart.renderer.label("",
0,-9999,b.shape,null,null,b.useHTML,null,"annotation-label").attr(d).add(a);this.annotation.chart.styledMode||("contrast"===f.color&&(f.color=this.annotation.chart.renderer.getContrast(-1<m.shapesWithoutBackground.indexOf(b.shape)?"#FFFFFF":b.backgroundColor)),this.graphic.css(b.style).shadow(b.shadow));b.className&&this.graphic.addClass(b.className);this.graphic.labelrank=b.labelrank;c.render.call(this)},redraw:function(a){var b=this.options,d=this.text||b.format||b.text,f=this.graphic,h=this.points[0];
f.attr({text:d?q(d,h.getLabelConfig(),this.annotation.chart):b.formatter.call(h,this)});b=this.anchor(h);(d=this.position(b))?(f.alignAttr=d,d.anchorX=b.absolutePosition.x,d.anchorY=b.absolutePosition.y,f[a?"animate":"attr"](d)):f.attr({x:0,y:-9999});f.placed=!!d;c.redraw.call(this,a)},anchor:function(){var a=c.anchor.apply(this,arguments),b=this.options.x||0,d=this.options.y||0;a.absolutePosition.x-=b;a.absolutePosition.y-=d;a.relativePosition.x-=b;a.relativePosition.y-=d;return a},position:function(b){var c=
this.graphic,d=this.annotation.chart,f=this.points[0],h=this.options,e=b.absolutePosition,y=b.relativePosition;if(b=f.series.visible&&n.prototype.isInsidePlot.call(f)){if(h.distance)var p=g.prototype.getPosition.call({chart:d,distance:k(h.distance,16)},c.width,c.height,{plotX:y.x,plotY:y.y,negative:f.negative,ttBelow:f.ttBelow,h:y.height||y.width});else h.positioner?p=h.positioner.call(this):(f={x:e.x,y:e.y,width:0,height:0},p=m.alignedPosition(a(h,{width:c.width,height:c.height}),f),"justify"===
this.options.overflow&&(p=m.alignedPosition(m.justifiedOptions(d,c,h,p),f)));h.crop&&(h=p.x-d.plotLeft,f=p.y-d.plotTop,b=d.isInsidePlot(h,f)&&d.isInsidePlot(h+c.width,f+c.height))}return b?p:null}});e.SVGRenderer.prototype.symbols.connector=function(a,b,c,d,h){var f=h&&h.anchorX;h=h&&h.anchorY;var e=c/2;if(r(f)&&r(h)){var k=[["M",f,h]];var t=b-h;0>t&&(t=-d-t);t<c&&(e=f<a+c/2?t:c-t);h>b+d?k.push(["L",a+e,b+d]):h<b?k.push(["L",a+e,b]):f<a?k.push(["L",a,b+d/2]):f>a+c&&k.push(["L",a+c,b+d/2])}return k||
[]};return m});r(c,"annotations/controllable/ControllableImage.js",[c["annotations/controllable/ControllableLabel.js"],c["annotations/controllable/controllableMixin.js"],c["parts/Utilities.js"]],function(c,e,n){n=n.merge;var g=function(c,a,e){this.init(c,a,e);this.collection="shapes"};g.attrsMap={width:"width",height:"height",zIndex:"zIndex"};n(!0,g.prototype,e,{type:"image",translate:e.translateShape,render:function(c){var a=this.attrsFromOptions(this.options),d=this.options;this.graphic=this.annotation.chart.renderer.image(d.src,
0,-9E9,d.width,d.height).attr(a).add(c);this.graphic.width=d.width;this.graphic.height=d.height;e.render.call(this)},redraw:function(d){var a=this.anchor(this.points[0]);if(a=c.prototype.position.call(this,a))this.graphic[d?"animate":"attr"]({x:a.x,y:a.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!a;e.redraw.call(this,d)}});return g});r(c,"annotations/annotations.src.js",[c["parts/Chart.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableRect.js"],
c["annotations/controllable/ControllableCircle.js"],c["annotations/controllable/ControllablePath.js"],c["annotations/controllable/ControllableImage.js"],c["annotations/controllable/ControllableLabel.js"],c["annotations/ControlPoint.js"],c["annotations/eventEmitterMixin.js"],c["parts/Globals.js"],c["annotations/MockPoint.js"],c["parts/Pointer.js"],c["parts/Utilities.js"]],function(c,e,n,g,d,a,r,v,b,k,m,A,l){c=c.prototype;var q=l.addEvent,f=l.defined,h=l.destroyObjectProperties,u=l.erase,y=l.extend,
p=l.find,t=l.fireEvent,x=l.merge,D=l.pick,E=l.splat;l=l.wrap;var B=function(){function c(a,b){this.annotation=void 0;this.coll="annotations";this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.collection=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=x(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=
b.shapes;this.init(a,this.options)}c.prototype.init=function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.setLabelCollector()};c.prototype.getLabelsAndShapesOptions=function(a,b){var c={};["labels","shapes"].forEach(function(d){a[d]&&(c[d]=E(b[d]).map(function(b,c){return x(a[d][c],b)}))});return c};c.prototype.addShapes=function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);x(!0,this.options.shapes[b],a.options)},this)};c.prototype.addLabels=
function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);x(!0,this.options.labels[b],a.options)},this)};c.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};c.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,d){return[a[d&&d.point&&d.point.xAxis]||c[0],b[d&&d.point&&d.point.yAxis]||
c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]};c.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};c.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};c.prototype.setOptions=function(a){this.options=x(this.defaultOptions,
a)};c.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);e.redraw.call(this,a)};c.prototype.redrawItems=function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)};c.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};c.prototype.render=function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,
visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();e.render.call(this)};c.prototype.setVisibility=function(a){var b=this.options;a=D(a,!b.visible);this.graphic.attr("visibility",
a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a};c.prototype.setControlPointsVisibility=function(a){var b=function(b){b.setControlPointsVisibility(a)};e.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)};c.prototype.destroy=function(){var a=this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;u(a.labelCollectors,this.labelCollector);b.destroy.call(this);e.destroy.call(this);
h(this,a)};c.prototype.remove=function(){return this.chart.removeAnnotation(this)};c.prototype.update=function(a,b){var c=this.chart,d=this.getLabelsAndShapesOptions(this.userOptions,a),f=c.annotations.indexOf(this);a=x(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();this.constructor(c,a);c.options.annotations[f]=a;this.isUpdating=!0;D(b,!0)&&c.redraw();t(this,"afterUpdate");this.isUpdating=!1};c.prototype.initShape=function(a,b){a=x(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},
a);b=new c.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b};c.prototype.initLabel=function(a,b){a=x(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new r(this,a,b);b.itemType="label";this.labels.push(b);return b};c.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(D(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)};c.prototype.adjustVisibility=
function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()};c.prototype.destroyItem=function(a){u(this[a.itemType+"s"],a);a.destroy()};c.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};c.ControlPoint=v;c.MockPoint=m;c.shapesMap={rect:n,circle:g,path:d,image:a};c.types={};return c}();x(!0,B.prototype,e,b,x(B.prototype,{nonDOMEvents:["add","afterUpdate",
"drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return f(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",
r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6}}));k.extendAnnotation=function(a,b,c,d){b=b||B;x(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=x(a.prototype.defaultOptions,d||{})};y(c,{initAnnotation:function(a){a=new (B.types[a.type]||B)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);
D(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:p(b,function(b){return b.options.id===a});c&&(t(c,"remove"),u(this.options.annotations,c.options),u(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});c.collectionsWithUpdate.push("annotations");c.collectionsWithInit.annotations=[c.addAnnotation];c.callbacks.push(function(a){a.annotations=[];a.options.annotations||
(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();q(a,"redraw",a.drawAnnotations);q(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});l(A.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,
Array.prototype.slice.call(arguments,1))});return k.Annotation=B});r(c,"mixins/navigation.js",[],function(){return{initUpdate:function(c){c.navigation||(c.navigation={updates:[],update:function(c,n){this.updates.forEach(function(e){e.update.call(e.context,c,n)})}})},addUpdate:function(c,e){e.navigation||this.initUpdate(e);e.navigation.updates.push({update:c,context:e})}}});r(c,"annotations/navigationBindings.js",[c["annotations/annotations.src.js"],c["mixins/navigation.js"],c["parts/Globals.js"],
c["parts/Utilities.js"]],function(c,e,n,g){function d(a){var c=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click;z(!0,a.prototype.defaultOptions.events,{click:function(a){var d=this,f=d.chart.navigationBindings,h=f.activeAnnotation;c&&c.click.call(d,a);h!==d?(f.deselectAnnotation(),f.activeAnnotation=d,d.setControlPointsVisibility(!0),b(f,"showPopup",{annotation:d,formType:"annotation-toolbar",options:f.annotationToFields(d),onSubmit:function(a){var b={};"remove"===a.actionType?
(f.activeAnnotation=!1,f.chart.removeAnnotation(d)):(f.fieldsToOptions(a.fields,b),f.deselectAnnotation(),a=b.typeOptions,"measure"===d.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),d.update(b))}})):(f.deselectAnnotation(),b(f,"closePopup"));a.activeAnnotation=!0}})}var a=g.addEvent,q=g.attr,r=g.format,b=g.fireEvent,k=g.isArray,m=g.isFunction,A=g.isNumber,l=g.isObject,z=g.merge,f=g.objectEach,h=g.pick;g=g.setOptions;var u=n.doc,
y=n.win,p=function(){function c(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=u.getElementsByClassName(this.options.bindingsClassName||"")}c.prototype.initEvents=function(){var b=this,c=b.chart,d=b.container,h=b.options;b.boundClassNames={};f(h.bindings||{},function(a){b.boundClassNames[a.className]=a});[].forEach.call(d,function(c){b.eventsToUnbind.push(a(c,"click",function(a){var d=b.getButtonEvents(c,a);d&&b.bindingsButtonClick(d.button,
d.events,a)}))});f(h.events||{},function(c,d){m(c)&&b.eventsToUnbind.push(a(b,d,c))});b.eventsToUnbind.push(a(c.container,"click",function(a){!c.cancelClick&&c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&b.bindingsChartClick(this,a)}));b.eventsToUnbind.push(a(c.container,v.isTouchDevice?"touchmove":"mousemove",function(a){b.bindingsContainerMouseMove(this,a)}))};c.prototype.initUpdate=function(){var a=this;e.addUpdate(function(b){a.update(b)},this.chart)};c.prototype.bindingsButtonClick=
function(a,c,d){var f=this.chart;this.selectedButtonElement&&(b(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&f.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=c;this.selectedButtonElement=a;b(this,"selectButton",{button:a});c.init&&c.init.call(this,a,d);(c.start||c.steps)&&f.renderer.boxWrapper.addClass("highcharts-draw-mode")};c.prototype.bindingsChartClick=
function(a,c){a=this.chart;var d=this.selectedButton;a=a.renderer.boxWrapper;var f;if(f=this.activeAnnotation&&!c.activeAnnotation&&c.target.parentNode){a:{f=c.target;var h=y.Element.prototype,e=h.matches||h.msMatchesSelector||h.webkitMatchesSelector,t=null;if(h.closest)t=h.closest.call(f,".highcharts-popup");else{do{if(e.call(f,".highcharts-popup"))break a;f=f.parentElement||f.parentNode}while(null!==f&&1===f.nodeType)}f=t}f=!f}f&&(b(this,"closePopup"),this.deselectAnnotation());d&&d.start&&(this.nextEvent?
(this.nextEvent(c,this.currentUserDetails),this.steps&&(this.stepIndex++,d.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]:(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),d.end&&d.end.call(this,c,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=d.start.call(this,c),d.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]):
(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,d.end&&d.end.call(this,c,this.currentUserDetails))))};c.prototype.bindingsContainerMouseMove=function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)};c.prototype.fieldsToOptions=function(a,b){f(a,function(a,c){var d=parseFloat(a),f=c.split("."),e=b,t=f.length-1;!A(d)||a.match(/px/g)||c.match(/format/g)||(a=d);""!==a&&"undefined"!==a&&
f.forEach(function(b,c){var d=h(f[c+1],"");t===c?e[b]=a:(e[b]||(e[b]=d.match(/\d/g)?[]:{}),e=e[b])})});return b};c.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)};c.prototype.annotationToFields=function(a){function b(c,d,h,e){if(h&&-1===x.indexOf(d)&&(0<=(h.indexOf&&h.indexOf(d))||h[d]||!0===h))if(k(c))e[d]=[],c.forEach(function(a,c){l(a)?(e[d][c]={},f(a,function(a,f){b(a,f,t[d],e[d][c])})):b(a,0,t[d],
e[d])});else if(l(c)){var u={};k(e)?(e.push(u),u[d]={},u=u[d]):e[d]=u;f(c,function(a,c){b(a,c,0===d?h:t[d],u)})}else"format"===d?e[d]=[r(c,a.labels[0].points[0]).toString(),"text"]:k(e)?e.push([c,g(c)]):e[d]=[c,g(c)]}var d=a.options,e=c.annotationsEditable,t=e.nestedOptions,g=this.utils.getFieldType,u=h(d.type,d.shapes&&d.shapes[0]&&d.shapes[0].type,d.labels&&d.labels[0]&&d.labels[0].itemType,"label"),x=c.annotationsNonEditable[d.langKey]||[],p={langKey:d.langKey,type:u};f(d,function(a,c){"typeOptions"===
c?(p[c]={},f(d[c],function(a,d){b(a,d,t,p[c],!0)})):b(a,c,e[u],p)});return p};c.prototype.getClickedClassNames=function(a,b){var c=b.target;b=[];for(var d;c&&((d=q(c,"class"))&&(b=b.concat(d.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b};c.prototype.getButtonEvents=function(a,b){var c=this,d;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d};c.prototype.update=function(a){this.options=
z(!0,this.options,a);this.removeEvents();this.initEvents()};c.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){a()})};c.prototype.destroy=function(){this.removeEvents()};c.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill",
"strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:[]};c.annotationsNonEditable=
{rectangle:["crosshairX","crosshairY","label"]};return c}();p.prototype.utils={updateRectSize:function(a,b){var c=b.chart,d=b.options.typeOptions,f=c.pointer.getCoordinates(a);a=f.xAxis[0].value-d.point.x;d=d.point.y-f.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?d:a,height:c.inverted?a:d}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}};n.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&
a.navigation.bindings&&(this.navigationBindings=new p(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};a(n.Chart,"load",function(){this.initNavigationBindings()});a(n.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});a(p,"deselectButton",function(){this.selectedButtonElement=null});a(c,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});n.Annotation&&(d(c),f(c.types,
function(a){d(a)}));g({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",
padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(z({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5}]},b.annotationsOptions,
b.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,d=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var f=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(f?c-a.chartX:d-a.chartX,2)+Math.pow(f?d-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var b=this.chart.pointer.getCoordinates(a);a=this.chart.options.navigation;var c=b.xAxis[0].value;
b=b.yAxis[0].value;return this.chart.addAnnotation(z({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b}]}]},a.annotationsOptions,a.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].points,d=this.chart.pointer.getCoordinates(a);a=d.xAxis[0].value;d=d.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=d;c[3].y=d;b.update({shapes:[{points:c}]})}]},
labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(z({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},overflow:"none",crop:!0}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}});return p});r(c,"annotations/popup.js",[c["parts/Globals.js"],
c["annotations/navigationBindings.js"],c["parts/Pointer.js"],c["parts/Utilities.js"]],function(c,e,n,g){var d=g.addEvent,a=g.createElement,q=g.defined,r=g.getOptions,b=g.isArray,k=g.isObject,m=g.isString,v=g.objectEach,l=g.pick;g=g.wrap;var z=/\d/g;g(n.prototype,"onContainerMouseDown",function(a,b){var c=b.target&&b.target.className;m(c)&&0<=c.indexOf("highcharts-popup-field")||a.apply(this,Array.prototype.slice.call(arguments,1))});c.Popup=function(a,b){this.init(a,b)};c.Popup.prototype={init:function(b,
c){this.container=a("div",{className:"highcharts-popup"},null,b);this.lang=this.getLangpack();this.iconsURL=c;this.addCloseBtn()},addCloseBtn:function(){var b=this;var c=a("div",{className:"highcharts-popup-close"},null,this.container);c.style["background-image"]="url("+this.iconsURL+"close.svg)";["click","touchstart"].forEach(function(a){d(c,a,function(){b.closePopup()})})},addColsContainer:function(b){var c=a("div",{className:"highcharts-popup-lhs-col"},null,b);b=a("div",{className:"highcharts-popup-rhs-col"},
null,b);a("div",{className:"highcharts-popup-rhs-col-wrapper"},null,b);return{lhsCol:c,rhsCol:b}},addInput:function(b,c,d,e){var f=b.split(".");f=f[f.length-1];var h=this.lang;c="highcharts-"+c+"-"+f;c.match(z)||a("label",{innerHTML:h[f]||f,htmlFor:c},null,d);a("input",{name:c,value:e[0],type:e[1],className:"highcharts-popup-field"},null,d).setAttribute("highcharts-data-name",b)},addButton:function(b,c,e,k,g){var f=this,h=this.closePopup,u=this.getFields;var l=a("button",{innerHTML:c},null,b);["click",
"touchstart"].forEach(function(a){d(l,a,function(){h.call(f);return k(u(g,e))})});return l},getFields:function(a,b){var c=a.querySelectorAll("input"),d=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];var f,h;var e={actionType:b,linkedTo:d&&d.getAttribute("value"),fields:{}};[].forEach.call(c,function(a){h=a.getAttribute("highcharts-data-name");(f=a.getAttribute("highcharts-data-series-id"))?e.seriesId=a.value:
h?e.fields[h]=a.value:e.type=a.value});a&&(e.fields["params.volumeSeriesID"]=a.getAttribute("value"));return e},showPopup:function(){var a=this.container,b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display="none"},showForm:function(a,b,c,d){this.popup=
b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,d);"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,d);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d);"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0)},getLangpack:function(){return r().lang.navigation.popup},annotations:{addToolbar:function(b,c,d){var f=this,e=this.lang,h=this.popup.container,k=this.showForm;-1===h.className.indexOf("highcharts-annotation-toolbar")&&
(h.className+=" highcharts-annotation-toolbar");h.style.top=b.plotTop+10+"px";a("span",{innerHTML:l(e[c.langKey]||c.langKey,c.shapes&&c.shapes[0].type)},null,h);var g=this.addButton(h,e.removeButton||"remove","remove",d,h);g.className+=" highcharts-annotation-remove-button";g.style["background-image"]="url("+this.iconsURL+"destroy.svg)";g=this.addButton(h,e.editButton||"edit","edit",function(){k.call(f,"annotation-edit",b,c,d)},h);g.className+=" highcharts-annotation-edit-button";g.style["background-image"]=
"url("+this.iconsURL+"edit.svg)"},addForm:function(b,c,d,e){var f=this.popup.container,h=this.lang;a("h2",{innerHTML:h[c.langKey]||c.langKey,className:"highcharts-popup-main-title"},null,f);var k=a("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,f);var g=a("div",{className:"highcharts-popup-bottom-row"},null,f);this.annotations.addFormFields.call(this,k,b,"",c,[],!0);this.addButton(g,e?h.addButton||"add":h.saveButton||"save",e?"add":"save",d,f)},addFormFields:function(c,
d,e,g,l,t){var f=this,h=this.annotations.addFormFields,u=this.addInput,p=this.lang,m,y;v(g,function(a,g){m=""!==e?e+"."+g:g;k(a)&&(!b(a)||b(a)&&k(a[0])?(y=p[g]||g,y.match(z)||l.push([!0,y,c]),h.call(f,c,d,m,a,l,!1)):l.push([f,m,"annotation",c,a]))});t&&(l=l.sort(function(a){return a[1].match(/format/g)?-1:1}),l.forEach(function(b){!0===b[0]?a("span",{className:"highcharts-annotation-title",innerHTML:b[1]},null,b[2]):u.apply(b[0],b.splice(1))}))}},indicators:{addForm:function(a,b,c){var d=this.indicators,
f=this.lang;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");var e=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(e,f.addButton||"add","add",c,e);this.addColsContainer(b[1]);d.addIndicatorList.call(this,a,b[1],"edit");e=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(e,f.saveButton||"save","edit",c,e);this.addButton(e,f.removeButton||
"remove","remove",c,e)},addIndicatorList:function(b,c,e){var f=this,h=c.querySelectorAll(".highcharts-popup-lhs-col")[0];c=c.querySelectorAll(".highcharts-popup-rhs-col")[0];var g="edit"===e,k=g?b.series:b.options.plotOptions,l=this.indicators.addFormFields,u;var m=a("ul",{className:"highcharts-indicator-list"},null,h);var n=c.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];v(k,function(c,e){var h=c.options;if(c.params||h&&h.params){var p=f.indicators.getNameType(c,e),t=p.type;u=a("li",{className:"highcharts-indicator-list",
innerHTML:p.name},null,m);["click","touchstart"].forEach(function(e){d(u,e,function(){l.call(f,b,g?c:k[t],p.type,n);g&&c.options&&a("input",{type:"hidden",name:"highcharts-id-"+t,value:c.options.id},null,n).setAttribute("highcharts-data-series-id",c.options.id)})})}});0<m.childNodes.length&&m.childNodes[0].click()},getNameType:function(a,b){var d=a.options,e=c.seriesTypes;e=e[b]&&e[b].prototype.nameBase||b.toUpperCase();d&&d.type&&(b=a.options.type,e=a.name);return{name:e,type:b}},listAllSeries:function(b,
c,d,e,g){b="highcharts-"+c+"-type-"+b;var f;a("label",{innerHTML:this.lang[c]||c,htmlFor:b},null,e);var h=a("select",{name:b,className:"highcharts-popup-field"},null,e);h.setAttribute("id","highcharts-select-"+c);d.series.forEach(function(b){f=b.options;!f.params&&f.id&&"highcharts-navigator-series"!==f.id&&a("option",{innerHTML:f.name||f.id,value:f.id},null,h)});q(g)&&(h.value=g)},addFormFields:function(b,c,d,e){var f=c.params||c.options.params,h=this.indicators.getNameType;e.innerHTML="";a("h3",
{className:"highcharts-indicator-title",innerHTML:h(c,d).name},null,e);a("input",{type:"hidden",name:"highcharts-type-"+d,value:d},null,e);this.indicators.listAllSeries.call(this,d,"series",b,e,c.linkedParent&&f.volumeSeriesID);f.volumeSeriesID&&this.indicators.listAllSeries.call(this,d,"volume",b,e,c.linkedParent&&c.linkedParent.options.id);this.indicators.addParamInputs.call(this,b,"params",f,d,e)},addParamInputs:function(a,b,c,d,e){var f=this,h=this.indicators.addParamInputs,g=this.addInput,l;
v(c,function(c,m){l=b+"."+m;k(c)?h.call(f,a,l,c,d,e):"params.volumeSeriesID"!==l&&g.call(f,l,d,e,[c,"text"])})},getAmount:function(){var a=0;this.series.forEach(function(b){var c=b.options;(b.params||c&&c.params)&&a++});return a}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c=b.addMenuItem.call(this,"add");b.addMenuItem.call(this,"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(b,
c){var d=this.popup.container,e="highcharts-tab-item",f=this.lang;0===c&&(e+=" highcharts-tab-disabled");c=a("span",{innerHTML:f[b+"Button"]||b,className:e},null,d);c.setAttribute("highcharts-data-tab-type",b);return c},addContentItem:function(){return a("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},switchTabs:function(a){var b=this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(e,f){c=e.getAttribute("highcharts-data-tab-type");"edit"===
c&&0===a||["click","touchstart"].forEach(function(a){d(e,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,this,f)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=this.popup.container,b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");var c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),
a[c].classList.remove("highcharts-tab-item-show")}}};d(e,"showPopup",function(a){this.popup||(this.popup=new c.Popup(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/8.1.1/gfx/stock-icons/"));this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)});d(e,"closePopup",function(){this.popup&&this.popup.closePopup()})});r(c,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map