/*
 Highcharts JS v8.1.1 (2020-06-09)

 Exporting module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/export-data",["highcharts","highcharts/modules/exporting"],function(n){d(n);d.Highcharts=n;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function n(e,a,f,d){e.hasOwnProperty(a)||(e[a]=d.apply(null,f))}var g=d?d._modules:{};n(g,"mixins/ajax.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(e,a){var f=a.merge,
d=a.objectEach;e.ajax=function(a){var c=f(!0,{url:!1,type:"get",dataType:"json",success:!1,error:!1,data:!1,headers:{}},a);a={json:"application/json",xml:"application/xml",text:"text/plain",octet:"application/octet-stream"};var b=new XMLHttpRequest;if(!c.url)return!1;b.open(c.type.toUpperCase(),c.url,!0);c.headers["Content-Type"]||b.setRequestHeader("Content-Type",a[c.dataType]||a.text);d(c.headers,function(a,c){b.setRequestHeader(c,a)});b.onreadystatechange=function(){if(4===b.readyState){if(200===
b.status){var a=b.responseText;if("json"===c.dataType)try{a=JSON.parse(a)}catch(p){c.error&&c.error(b,p);return}return c.success&&c.success(a)}c.error&&c.error(b,b.responseText)}};try{c.data=JSON.stringify(c.data)}catch(D){}b.send(c.data||!0)};e.getJSON=function(a,c){e.ajax({url:a,success:c,dataType:"json",headers:{"Content-Type":"text/plain"}})}});n(g,"mixins/download-url.js",[g["parts/Globals.js"]],function(e){var a=e.win,f=a.navigator,d=a.document,g=a.URL||a.webkitURL||a,c=/Edge\/\d+/.test(f.userAgent);
e.dataURLtoBlob=function(b){if((b=b.match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/))&&3<b.length&&a.atob&&a.ArrayBuffer&&a.Uint8Array&&a.Blob&&g.createObjectURL){var c=a.atob(b[3]),e=new a.ArrayBuffer(c.length);e=new a.Uint8Array(e);for(var d=0;d<e.length;++d)e[d]=c.charCodeAt(d);b=new a.Blob([e],{type:b[1]});return g.createObjectURL(b)}};e.downloadURL=function(b,g){var p=d.createElement("a");if("string"===typeof b||b instanceof String||!f.msSaveOrOpenBlob){if(c||2E6<b.length)if(b=e.dataURLtoBlob(b),
!b)throw Error("Failed to convert to blob");if("undefined"!==typeof p.download)p.href=b,p.download=g,d.body.appendChild(p),p.click(),d.body.removeChild(p);else try{var n=a.open(b,"chart");if("undefined"===typeof n||null===n)throw Error("Failed to open window");}catch(E){a.location.href=b}}else f.msSaveOrOpenBlob(b,g)}});n(g,"modules/export-data.src.js",[g["parts/Chart.js"],g["parts/Globals.js"],g["parts/Utilities.js"]],function(e,a,f){function g(a,c){var e=b.navigator,d=-1<e.userAgent.indexOf("WebKit")&&
0>e.userAgent.indexOf("Chrome"),m=b.URL||b.webkitURL||b;try{if(e.msSaveOrOpenBlob&&b.MSBlobBuilder){var r=new b.MSBlobBuilder;r.append(a);return r.getBlob("image/svg+xml")}if(!d)return m.createObjectURL(new b.Blob(["\ufeff"+a],{type:c}))}catch(M){}}var n=a.doc,c=a.seriesTypes,b=a.win,D=f.addEvent,p=f.defined,I=f.extend,E=f.find,A=f.fireEvent,J=f.getOptions,K=f.isNumber,u=f.pick;f=f.setOptions;var F=a.downloadURL;f({exporting:{csv:{columnHeaderFormatter:null,dateFormat:"%Y-%m-%d %H:%M:%S",decimalPoint:null,
itemDelimiter:null,lineDelimiter:"\n"},showTable:!1,useMultiLevelHeaders:!0,useRowspanHeaders:!0},lang:{downloadCSV:"Download CSV",downloadXLS:"Download XLS",exportData:{categoryHeader:"Category",categoryDatetimeHeader:"DateTime"},viewData:"View data table"}});D(e,"render",function(){this.options&&this.options.exporting&&this.options.exporting.showTable&&!this.options.chart.forExport&&this.viewData()});e.prototype.setUpKeyToAxis=function(){c.arearange&&(c.arearange.prototype.keyToAxis={low:"y",high:"y"});
c.gantt&&(c.gantt.prototype.keyToAxis={start:"x",end:"x"})};e.prototype.getDataRows=function(a){var b=this.hasParallelCoordinates,c=this.time,e=this.options.exporting&&this.options.exporting.csv||{},m=this.xAxis,r={},f=[],g=[],n=[],y;var k=this.options.lang.exportData;var w=k.categoryHeader,t=k.categoryDatetimeHeader,G=function(h,b,c){if(e.columnHeaderFormatter){var f=e.columnHeaderFormatter(h,b,c);if(!1!==f)return f}return h?h instanceof d.Axis?h.options.title&&h.options.title.text||(h.dateTime?
t:w):a?{columnTitle:1<c?b:h.name,topLevelColumnTitle:h.name}:h.name+(1<c?" ("+b+")":""):w},H=function(h,a,b){var c={},e={};a.forEach(function(a){var f=(h.keyToAxis&&h.keyToAxis[a]||a)+"Axis";f=K(b)?h.chart[f][b]:h[f];c[a]=f&&f.categories||[];e[a]=f&&f.dateTime});return{categoryMap:c,dateTimeValueAxisMap:e}},L=function(h,a){return h.data.filter(function(a){return a.name}).length&&a&&!a.categories&&!h.keyToAxis?h.pointArrayMap&&h.pointArrayMap.filter(function(a){return"x"===a}).length?(h.pointArrayMap.unshift("x"),
h.pointArrayMap):["x","y"]:h.pointArrayMap||["y"]},l=[];var v=0;this.setUpKeyToAxis();this.series.forEach(function(h){var f=h.xAxis,t=h.options.keys||L(h,f),d=t.length,q=!h.requireSorting&&{},w=m.indexOf(f),z=H(h,t),k;if(!1!==h.options.includeInDataExport&&!h.options.isInternal&&!1!==h.visible){E(l,function(a){return a[0]===w})||l.push([w,v]);for(k=0;k<d;)y=G(h,t[k],t.length),n.push(y.columnTitle||y),a&&g.push(y.topLevelColumnTitle||y),k++;var p={chart:h.chart,autoIncrement:h.autoIncrement,options:h.options,
pointArrayMap:h.pointArrayMap};h.options.data.forEach(function(a,m){b&&(z=H(h,t,m));var l={series:p};h.pointClass.prototype.applyOptions.apply(l,[a]);a=l.x;var g=h.data[m]&&h.data[m].name;k=0;if(!f||"name"===h.exportKey||!b&&f&&f.hasNames&&g)a=g;q&&(q[a]&&(a+="|"+m),q[a]=!0);r[a]||(r[a]=[],r[a].xValues=[]);r[a].x=l.x;r[a].name=g;for(r[a].xValues[w]=l.x;k<d;)m=t[k],g=l[m],r[a][v+k]=u(z.categoryMap[m][g],z.dateTimeValueAxisMap[m]?c.dateFormat(e.dateFormat,g):null,g),k++});v+=k}});for(q in r)Object.hasOwnProperty.call(r,
q)&&f.push(r[q]);var q=a?[g,n]:[n];for(v=l.length;v--;){var B=l[v][0];var C=l[v][1];var x=m[B];f.sort(function(a,b){return a.xValues[B]-b.xValues[B]});k=G(x);q[0].splice(C,0,k);a&&q[1]&&q[1].splice(C,0,k);f.forEach(function(a){var b=a.name;x&&!p(b)&&(x.dateTime?(a.x instanceof Date&&(a.x=a.x.getTime()),b=c.dateFormat(e.dateFormat,a.x)):b=x.categories?u(x.names[a.x],x.categories[a.x],a.x):a.x);a.splice(C,0,b)})}q=q.concat(f);A(this,"exportData",{dataRows:q});return q};e.prototype.getCSV=function(a){var b=
"",c=this.getDataRows(),e=this.options.exporting.csv,f=u(e.decimalPoint,","!==e.itemDelimiter&&a?(1.1).toLocaleString()[1]:"."),m=u(e.itemDelimiter,","===f?";":","),g=e.lineDelimiter;c.forEach(function(a,e){for(var d,k=a.length;k--;)d=a[k],"string"===typeof d&&(d='"'+d+'"'),"number"===typeof d&&"."!==f&&(d=d.toString().replace(".",f)),a[k]=d;b+=a.join(m);e<c.length-1&&(b+=g)});return b};e.prototype.getTable=function(a){var b='<table id="highcharts-data-table-'+this.index+'">',c=this.options,e=a?(1.1).toLocaleString()[1]:
".",f=u(c.exporting.useMultiLevelHeaders,!0);a=this.getDataRows(f);var d=0,g=f?a.shift():null,m=a.shift(),n=function(a,b,c,f){var d=u(f,"");b="text"+(b?" "+b:"");"number"===typeof d?(d=d.toString(),","===e&&(d=d.replace(".",e)),b="number"):f||(b="empty");return"<"+a+(c?" "+c:"")+' class="'+b+'">'+d+"</"+a+">"};!1!==c.exporting.tableCaption&&(b+='<caption class="highcharts-table-caption">'+u(c.exporting.tableCaption,c.title.text?c.title.text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;"):"Chart")+"</caption>");for(var p=0,k=a.length;p<k;++p)a[p].length>d&&(d=a[p].length);b+=function(a,b,e){var d="<thead>",g=0;e=e||b&&b.length;var l,m=0;if(l=f&&a&&b){a:if(l=a.length,b.length===l){for(;l--;)if(a[l]!==b[l]){l=!1;break a}l=!0}else l=!1;l=!l}if(l){for(d+="<tr>";g<e;++g){l=a[g];var k=a[g+1];l===k?++m:m?(d+=n("th","highcharts-table-topheading",'scope="col" colspan="'+(m+1)+'"',l),m=0):(l===b[g]?c.exporting.useRowspanHeaders?
(k=2,delete b[g]):(k=1,b[g]=""):k=1,d+=n("th","highcharts-table-topheading",'scope="col"'+(1<k?' valign="top" rowspan="'+k+'"':""),l))}d+="</tr>"}if(b){d+="<tr>";g=0;for(e=b.length;g<e;++g)"undefined"!==typeof b[g]&&(d+=n("th",null,'scope="col"',b[g]));d+="</tr>"}return d+"</thead>"}(g,m,Math.max(d,m.length));b+="<tbody>";a.forEach(function(a){b+="<tr>";for(var c=0;c<d;c++)b+=n(c?"td":"th",null,c?"":'scope="row"',a[c]);b+="</tr>"});b+="</tbody></table>";a={html:b};A(this,"afterGetTable",a);return a.html};
e.prototype.downloadCSV=function(){var a=this.getCSV(!0);F(g(a,"text/csv")||"data:text/csv,\ufeff"+encodeURIComponent(a),this.getFilename()+".csv")};e.prototype.downloadXLS=function(){var a='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head>\x3c!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Ark1</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--\x3e<style>td{border:none;font-family: Calibri, sans-serif;} .number{mso-number-format:"0.00";} .text{ mso-number-format:"@";}</style><meta name=ProgId content=Excel.Sheet><meta charset=UTF-8></head><body>'+
this.getTable(!0)+"</body></html>";F(g(a,"application/vnd.ms-excel")||"data:application/vnd.ms-excel;base64,"+b.btoa(unescape(encodeURIComponent(a))),this.getFilename()+".xls")};e.prototype.viewData=function(){this.dataTableDiv||(this.dataTableDiv=n.createElement("div"),this.dataTableDiv.className="highcharts-data-table",this.renderTo.parentNode.insertBefore(this.dataTableDiv,this.renderTo.nextSibling));this.dataTableDiv.innerHTML=this.getTable();A(this,"afterViewData",this.dataTableDiv)};if(e=J().exporting)I(e.menuItemDefinitions,
{downloadCSV:{textKey:"downloadCSV",onclick:function(){this.downloadCSV()}},downloadXLS:{textKey:"downloadXLS",onclick:function(){this.downloadXLS()}},viewData:{textKey:"viewData",onclick:function(){this.viewData()}}}),e.buttons&&e.buttons.contextButton.menuItems.push("separator","downloadCSV","downloadXLS","viewData");c.map&&(c.map.prototype.exportKey="name");c.mapbubble&&(c.mapbubble.prototype.exportKey="name");c.treemap&&(c.treemap.prototype.exportKey="name")});n(g,"masters/modules/export-data.src.js",
[],function(){})});
//# sourceMappingURL=export-data.js.map