/*
 Highstock JS v8.1.1 (2020-06-09)

 Advanced Highstock tools

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(q){"object"===typeof module&&module.exports?(q["default"]=q,module.exports=q):"function"===typeof define&&define.amd?define("highcharts/modules/stock-tools",["highcharts","highcharts/modules/stock"],function(p){q(p);q.Highcharts=p;return q}):q("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(q){function p(f,e,n,l){f.hasOwnProperty(e)||(f[e]=l.apply(null,n))}var f=q?q._modules:{};p(f,"annotations/eventEmitterMixin.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(f,
e){var n=e.addEvent,l=e.fireEvent,d=e.inArray,c=e.objectEach,m=e.pick,D=e.removeEvent;return{addEvents:function(){var b=this,k=function(k){n(k,q.isTouchDevice?"touchstart":"mousedown",function(h){b.onMouseDown(h)})};k(this.graphic.element);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&k(b.graphic.text.element)});c(b.options.events,function(k,h){var a=function(a){"click"===h&&b.cancelClick||k.call(b,b.chart.pointer.normalize(a),b.target)};if(-1===d(h,b.nonDOMEvents||[]))b.graphic.on(h,
a);else n(b,h,a)});if(b.options.draggable&&(n(b,q.isTouchDevice?"touchmove":"drag",b.onDrag),!b.graphic.renderer.styledMode)){var u={cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[b.options.draggable]};b.graphic.css(u);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text&&b.graphic.text.css(u)})}b.isUpdating||l(b,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(b){var k=
this,c=k.chart.pointer;b.preventDefault&&b.preventDefault();if(2!==b.button){b=c.normalize(b);var C=b.chartX;var h=b.chartY;k.cancelClick=!1;k.chart.hasDraggedAnnotation=!0;k.removeDrag=n(f.doc,q.isTouchDevice?"touchmove":"mousemove",function(a){k.hasDragged=!0;a=c.normalize(a);a.prevChartX=C;a.prevChartY=h;l(k,"drag",a);C=a.chartX;h=a.chartY});k.removeMouseUp=n(f.doc,q.isTouchDevice?"touchend":"mouseup",function(a){k.cancelClick=k.hasDragged;k.hasDragged=!1;k.chart.hasDraggedAnnotation=!1;l(m(k.target,
k),"afterUpdate");k.onMouseUp(a)})}},onMouseUp:function(b){var k=this.chart;b=this.target||this;var c=k.options.annotations;k=k.annotations.indexOf(b);this.removeDocEvents();c[k]=b.options},onDrag:function(b){if(this.chart.isInsidePlot(b.chartX-this.chart.plotLeft,b.chartY-this.chart.plotTop)){var k=this.mouseMoveToTranslation(b);"x"===this.options.draggable&&(k.y=0);"y"===this.options.draggable&&(k.x=0);this.points.length?this.translate(k.x,k.y):(this.shapes.forEach(function(b){b.translate(k.x,k.y)}),
this.labels.forEach(function(b){b.translate(k.x,k.y)}));this.redraw(!1)}},mouseMoveToRadians:function(b,k,c){var m=b.prevChartY-c,h=b.prevChartX-k;c=b.chartY-c;b=b.chartX-k;this.chart.inverted&&(k=h,h=m,m=k,k=b,b=c,c=k);return Math.atan2(c,b)-Math.atan2(m,h)},mouseMoveToTranslation:function(b){var k=b.chartX-b.prevChartX;b=b.chartY-b.prevChartY;if(this.chart.inverted){var c=b;b=k;k=c}return{x:k,y:b}},mouseMoveToScale:function(b,k,c){k=(b.chartX-k||1)/(b.prevChartX-k||1);b=(b.chartY-c||1)/(b.prevChartY-
c||1);this.chart.inverted&&(c=b,b=k,k=c);return{x:k,y:b}},destroy:function(){this.removeDocEvents();D(this);this.hcEvents=null}}});p(f,"annotations/ControlPoint.js",[f["parts/Utilities.js"],f["annotations/eventEmitterMixin.js"]],function(f,e){var n=f.merge,l=f.pick;return function(){function d(c,m,d,b){this.addEvents=e.addEvents;this.graphic=void 0;this.mouseMoveToRadians=e.mouseMoveToRadians;this.mouseMoveToScale=e.mouseMoveToScale;this.mouseMoveToTranslation=e.mouseMoveToTranslation;this.onDrag=
e.onDrag;this.onMouseDown=e.onMouseDown;this.onMouseUp=e.onMouseUp;this.removeDocEvents=e.removeDocEvents;this.nonDOMEvents=["drag"];this.chart=c;this.target=m;this.options=d;this.index=l(d.index,b)}d.prototype.setVisibility=function(c){this.graphic.attr("visibility",c?"visible":"hidden");this.options.visible=c};d.prototype.render=function(){var c=this.chart,m=this.options;this.graphic=c.renderer.symbol(m.symbol,0,0,m.width,m.height).add(c.controlPointsGroup).css(m.style);this.setVisibility(m.visible);
this.addEvents()};d.prototype.redraw=function(c){this.graphic[c?"animate":"attr"](this.options.positioner.call(this,this.target))};d.prototype.destroy=function(){e.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};d.prototype.update=function(c){var m=this.chart,d=this.target,b=this.index;c=n(!0,this.options,c);this.destroy();this.constructor(m,d,c,b);this.render(m.controlPointsGroup);this.redraw()};return d}()});p(f,"annotations/MockPoint.js",
[f["parts/Globals.js"],f["parts/Utilities.js"]],function(f,e){var n=e.defined,l=e.fireEvent;return function(){function d(c,m,d){this.y=this.x=this.plotY=this.plotX=this.isInside=void 0;this.mock=!0;this.series={visible:!0,chart:c,getPlotBox:f.Series.prototype.getPlotBox};this.target=m||null;this.options=d;this.applyOptions(this.getOptions())}d.fromPoint=function(c){return new d(c.series.chart,null,{x:c.x,y:c.y,xAxis:c.series.xAxis,yAxis:c.series.yAxis})};d.pointToPixels=function(c,m){var d=c.series,
b=d.chart,k=c.plotX,e=c.plotY;b.inverted&&(c.mock?(k=c.plotY,e=c.plotX):(k=b.plotWidth-c.plotY,e=b.plotHeight-c.plotX));d&&!m&&(c=d.getPlotBox(),k+=c.translateX,e+=c.translateY);return{x:k,y:e}};d.pointToOptions=function(c){return{x:c.x,y:c.y,xAxis:c.series.xAxis,yAxis:c.series.yAxis}};d.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};d.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};d.prototype.applyOptions=function(c){this.command=
c.command;this.setAxis(c,"x");this.setAxis(c,"y");this.refresh()};d.prototype.setAxis=function(c,m){m+="Axis";c=c[m];var d=this.series.chart;this.series[m]=c instanceof f.Axis?c:n(c)?d[m][c]||d.get(c):null};d.prototype.toAnchor=function(){var c=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(c[0]=this.plotY,c[1]=this.plotX);return c};d.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};d.prototype.isInsidePlot=function(){var c=this.plotX,m=this.plotY,d=this.series.xAxis,
b=this.series.yAxis,k={x:c,y:m,isInsidePlot:!0};d&&(k.isInsidePlot=n(c)&&0<=c&&c<=d.len);b&&(k.isInsidePlot=k.isInsidePlot&&n(m)&&0<=m&&m<=b.len);l(this.series.chart,"afterIsInsidePlot",k);return k.isInsidePlot};d.prototype.refresh=function(){var c=this.series,d=c.xAxis;c=c.yAxis;var e=this.getOptions();d?(this.x=e.x,this.plotX=d.toPixels(e.x,!0)):(this.x=null,this.plotX=e.x);c?(this.y=e.y,this.plotY=c.toPixels(e.y,!0)):(this.y=null,this.plotY=e.y);this.isInside=this.isInsidePlot()};d.prototype.translate=
function(c,d,e,b){this.hasDynamicOptions()||(this.plotX+=e,this.plotY+=b,this.refreshOptions())};d.prototype.scale=function(c,d,e,b){if(!this.hasDynamicOptions()){var k=this.plotY*b;this.plotX=(1-e)*c+this.plotX*e;this.plotY=(1-b)*d+k;this.refreshOptions()}};d.prototype.rotate=function(c,d,e){if(!this.hasDynamicOptions()){var b=Math.cos(e);e=Math.sin(e);var k=this.plotX,m=this.plotY;k-=c;m-=d;this.plotX=k*b-m*e+c;this.plotY=k*e+m*b+d;this.refreshOptions()}};d.prototype.refreshOptions=function(){var c=
this.series,d=c.xAxis;c=c.yAxis;this.x=this.options.x=d?this.options.x=d.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=c?c.toValue(this.plotY,!0):this.plotY};return d}()});p(f,"annotations/controllable/controllableMixin.js",[f["annotations/ControlPoint.js"],f["annotations/MockPoint.js"],f["parts/Tooltip.js"],f["parts/Utilities.js"]],function(f,e,n,l){var d=l.isObject,c=l.isString,m=l.merge,y=l.splat;return{init:function(b,k,c){this.annotation=b;this.chart=b.chart;this.options=k;this.points=
[];this.controlPoints=[];this.index=c;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var b=this.options;return b.points||b.point&&y(b.point)},attrsFromOptions:function(b){var k=this.constructor.attrsMap,c={},d,h=this.chart.styledMode;for(d in b){var a=k[d];!a||h&&-1!==["fill","stroke","stroke-width"].indexOf(a)||(c[a]=b[d])}return c},anchor:function(b){var c=b.series.getPlotBox();b=b.mock?b.toAnchor():n.prototype.getAnchor.call({chart:b.series.chart},
b);b={x:b[0]+(this.options.x||0),y:b[1]+(this.options.y||0),height:b[2]||0,width:b[3]||0};return{relativePosition:b,absolutePosition:m(b,{x:b.x+c.translateX,y:b.y+c.translateY})}},point:function(b,k){if(b&&b.series)return b;k&&null!==k.series||(d(b)?k=new e(this.chart,this,b):c(b)?k=this.chart.get(b)||null:"function"===typeof b&&(k=b.call(k,this),k=k.series?k:new e(this.chart,this,b)));return k},linkPoints:function(){var b=this.getPointsOptions(),c=this.points,d=b&&b.length||0,e;for(e=0;e<d;e++){var h=
this.point(b[e],c[e]);if(!h){c.length=0;return}h.mock&&h.refresh();c[e]=h}return c},addControlPoints:function(){var b=this.options.controlPoints;(b||[]).forEach(function(c,d){c=m(this.options.controlPointOptions,c);c.index||(c.index=d);b[d]=c;this.controlPoints.push(new f(this.chart,this,c))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(b){this.controlPoints.forEach(function(b){b.render()})},redraw:function(b){this.controlPoints.forEach(function(c){c.redraw(b)})},transform:function(b,
c,d,e,h){if(this.chart.inverted){var a=c;c=d;d=a}this.points.forEach(function(a,v){this.transformPoint(b,c,d,e,h,v)},this)},transformPoint:function(b,c,d,m,h,a){var g=this.points[a];g.mock||(g=this.points[a]=e.fromPoint(g));g[b](c,d,m,h)},translate:function(b,c){this.transform("translate",null,null,b,c)},translatePoint:function(b,c,d){this.transformPoint("translate",null,null,b,c,d)},translateShape:function(b,c){var k=this.annotation.chart,d=this.annotation.userOptions,h=k.annotations.indexOf(this.annotation);
k=k.options.annotations[h];this.translatePoint(b,c,0);k[this.collection][this.index].point=this.options.point;d[this.collection][this.index].point=this.options.point},rotate:function(b,c,d){this.transform("rotate",b,c,d)},scale:function(b,c,d,e){this.transform("scale",b,c,d,e)},setControlPointsVisibility:function(b){this.controlPoints.forEach(function(c){c.setVisibility(b)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());
this.controlPoints.forEach(function(b){b.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=null)},update:function(b){var c=this.annotation;b=m(!0,this.options,b);var d=this.graphic.parentGroup;this.destroy();this.constructor(c,b);this.render(d);this.redraw()}}});p(f,"annotations/controllable/markerMixin.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(f,e){var n=e.addEvent,l=e.defined,d=e.merge,c=e.objectEach,m=e.uniqueKey,y={arrow:{tagName:"marker",
render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};f.SVGRenderer.prototype.addMarker=function(b,c){var k={id:b},e={stroke:c.color||"none",fill:c.color||"rgba(0, 0, 0, 0.75)"};k.children=c.children.map(function(b){return d(e,b)});c=this.definition(d(!0,
{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},c,k));c.id=b;return c};e=function(b){return function(c){this.attr(b,"url(#"+c+")")}};e={markerEndSetter:e("marker-end"),markerStartSetter:e("marker-start"),setItemMarkers:function(b){var c=b.options,e=b.chart,f=e.options.defs,h=c.fill,a=l(h)&&"none"!==h?h:c.stroke;["markerStart","markerEnd"].forEach(function(g){var h=c[g],r;if(h){for(r in f){var k=f[r];if(h===k.id&&"marker"===k.tagName){var t=k;break}}t&&(h=b[g]=e.renderer.addMarker((c.id||
m())+"-"+t.id,d(t,{color:a})),b.attr(g,h.attr("id")))}})}};n(f.Chart,"afterGetContainer",function(){this.options.defs=d(y,this.options.defs||{});c(this.options.defs,function(b){"marker"===b.tagName&&!1!==b.render&&this.renderer.addMarker(b.id,b)},this)});return e});p(f,"annotations/controllable/ControllablePath.js",[f["annotations/controllable/controllableMixin.js"],f["parts/Globals.js"],f["annotations/controllable/markerMixin.js"],f["parts/Utilities.js"]],function(f,e,n,l){var d=l.extend;l=l.merge;
var c="rgba(192,192,192,"+(e.svg?.0001:.002)+")";e=function(c,d,b){this.init(c,d,b);this.collection="shapes"};e.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};l(!0,e.prototype,f,{type:"path",setMarkers:n.setItemMarkers,toD:function(){var c=this.options.d;if(c)return"function"===typeof c?c.call(this):c;c=this.points;var d=c.length,b=d,e=c[0],f=b&&this.anchor(e).absolutePosition,l=0,h=[];if(f)for(h.push(["M",f.x,f.y]);++l<d&&b;)e=c[l],b=e.command||
"L",f=this.anchor(e).absolutePosition,"M"===b?h.push([b,f.x,f.y]):"L"===b?h.push([b,f.x,f.y]):"Z"===b&&h.push([b]),b=e.series.visible;return b?this.chart.renderer.crispLine(h,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return f.shouldBeDrawn.call(this)||!!this.options.d},render:function(e){var l=this.options,b=this.attrsFromOptions(l);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(b).add(e);l.className&&this.graphic.addClass(l.className);this.tracker=this.annotation.chart.renderer.path([["M",
0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(e);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:c,fill:c,"stroke-width":this.graphic.strokeWidth()+2*l.snap});f.render.call(this);d(this.graphic,{markerStartSetter:n.markerStartSetter,markerEndSetter:n.markerEndSetter});this.setMarkers(this)},redraw:function(c){var d=this.toD(),b=c?"animate":"attr";d?(this.graphic[b]({d:d}),this.tracker[b]({d:d})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));
this.graphic.placed=this.tracker.placed=!!d;f.redraw.call(this,c)}});return e});p(f,"annotations/controllable/ControllableRect.js",[f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/ControllablePath.js"],f["parts/Utilities.js"]],function(f,e,n){n=n.merge;var l=function(d,c,e){this.init(d,c,e);this.collection="shapes"};l.attrsMap=n(e.attrsMap,{width:"width",height:"height"});n(!0,l.prototype,f,{type:"rect",translate:f.translateShape,render:function(d){var c=this.attrsFromOptions(this.options);
this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(c).add(d);f.render.call(this)},redraw:function(d){var c=this.anchor(this.points[0]).absolutePosition;if(c)this.graphic[d?"animate":"attr"]({x:c.x,y:c.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!c;f.redraw.call(this,d)}});return l});p(f,"annotations/controllable/ControllableCircle.js",[f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/ControllablePath.js"],
f["parts/Utilities.js"]],function(f,e,n){n=n.merge;var l=function(d,c,e){this.init(d,c,e);this.collection="shapes"};l.attrsMap=n(e.attrsMap,{r:"r"});n(!0,l.prototype,f,{type:"circle",translate:f.translateShape,render:function(d){var c=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(c).add(d);f.render.call(this)},redraw:function(d){var c=this.anchor(this.points[0]).absolutePosition;if(c)this.graphic[d?"animate":"attr"]({x:c.x,y:c.y,r:this.options.r});
else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!c;f.redraw.call(this,d)},setRadius:function(d){this.options.r=d}});return l});p(f,"annotations/controllable/ControllableLabel.js",[f["annotations/controllable/controllableMixin.js"],f["parts/Globals.js"],f["annotations/MockPoint.js"],f["parts/Tooltip.js"],f["parts/Utilities.js"]],function(f,e,n,l,d){var c=d.extend,m=d.format,y=d.isNumber,b=d.merge,k=d.pick,u=function(b,c,a){this.init(b,c,a);this.collection="labels"};u.shapesWithoutBackground=
["connector"];u.alignedPosition=function(b,c){var a=b.align,g=b.verticalAlign,h=(c.x||0)+(b.x||0),d=(c.y||0)+(b.y||0),e,f;"right"===a?e=1:"center"===a&&(e=2);e&&(h+=(c.width-(b.width||0))/e);"bottom"===g?f=1:"middle"===g&&(f=2);f&&(d+=(c.height-(b.height||0))/f);return{x:Math.round(h),y:Math.round(d)}};u.justifiedOptions=function(b,c,a,g){var h=a.align,d=a.verticalAlign,e=c.box?0:c.padding||0,f=c.getBBox();c={align:h,verticalAlign:d,x:a.x,y:a.y,width:c.width,height:c.height};a=g.x-b.plotLeft;var w=
g.y-b.plotTop;g=a+e;0>g&&("right"===h?c.align="left":c.x=-g);g=a+f.width-e;g>b.plotWidth&&("left"===h?c.align="right":c.x=b.plotWidth-g);g=w+e;0>g&&("bottom"===d?c.verticalAlign="top":c.y=-g);g=w+f.height-e;g>b.plotHeight&&("top"===d?c.verticalAlign="bottom":c.y=b.plotHeight-g);return c};u.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};b(!0,u.prototype,f,{translatePoint:function(c,b){f.translatePoint.call(this,c,
b,0)},translate:function(c,b){var a=this.annotation.chart,g=this.annotation.userOptions,d=a.annotations.indexOf(this.annotation);d=a.options.annotations[d];a.inverted&&(a=c,c=b,b=a);this.options.x+=c;this.options.y+=b;d[this.collection][this.index].x=this.options.x;d[this.collection][this.index].y=this.options.y;g[this.collection][this.index].x=this.options.x;g[this.collection][this.index].y=this.options.y},render:function(c){var b=this.options,a=this.attrsFromOptions(b),g=b.style;this.graphic=this.annotation.chart.renderer.label("",
0,-9999,b.shape,null,null,b.useHTML,null,"annotation-label").attr(a).add(c);this.annotation.chart.styledMode||("contrast"===g.color&&(g.color=this.annotation.chart.renderer.getContrast(-1<u.shapesWithoutBackground.indexOf(b.shape)?"#FFFFFF":b.backgroundColor)),this.graphic.css(b.style).shadow(b.shadow));b.className&&this.graphic.addClass(b.className);this.graphic.labelrank=b.labelrank;f.render.call(this)},redraw:function(b){var c=this.options,a=this.text||c.format||c.text,g=this.graphic,d=this.points[0];
g.attr({text:a?m(a,d.getLabelConfig(),this.annotation.chart):c.formatter.call(d,this)});c=this.anchor(d);(a=this.position(c))?(g.alignAttr=a,a.anchorX=c.absolutePosition.x,a.anchorY=c.absolutePosition.y,g[b?"animate":"attr"](a)):g.attr({x:0,y:-9999});g.placed=!!a;f.redraw.call(this,b)},anchor:function(){var b=f.anchor.apply(this,arguments),c=this.options.x||0,a=this.options.y||0;b.absolutePosition.x-=c;b.absolutePosition.y-=a;b.relativePosition.x-=c;b.relativePosition.y-=a;return b},position:function(b){var d=
this.graphic,a=this.annotation.chart,g=this.points[0],e=this.options,f=b.absolutePosition,m=b.relativePosition;if(b=g.series.visible&&n.prototype.isInsidePlot.call(g)){if(e.distance)var t=l.prototype.getPosition.call({chart:a,distance:k(e.distance,16)},d.width,d.height,{plotX:m.x,plotY:m.y,negative:g.negative,ttBelow:g.ttBelow,h:m.height||m.width});else e.positioner?t=e.positioner.call(this):(g={x:f.x,y:f.y,width:0,height:0},t=u.alignedPosition(c(e,{width:d.width,height:d.height}),g),"justify"===
this.options.overflow&&(t=u.alignedPosition(u.justifiedOptions(a,d,e,t),g)));e.crop&&(e=t.x-a.plotLeft,g=t.y-a.plotTop,b=a.isInsidePlot(e,g)&&a.isInsidePlot(e+d.width,g+d.height))}return b?t:null}});e.SVGRenderer.prototype.symbols.connector=function(b,c,a,g,d){var e=d&&d.anchorX;d=d&&d.anchorY;var f=a/2;if(y(e)&&y(d)){var h=[["M",e,d]];var w=c-d;0>w&&(w=-g-w);w<a&&(f=e<b+a/2?w:a-w);d>c+g?h.push(["L",b+f,c+g]):d<c?h.push(["L",b+f,c]):e<b?h.push(["L",b,c+g/2]):e>b+a&&h.push(["L",b+a,c+g/2])}return h||
[]};return u});p(f,"annotations/controllable/ControllableImage.js",[f["annotations/controllable/ControllableLabel.js"],f["annotations/controllable/controllableMixin.js"],f["parts/Utilities.js"]],function(f,e,n){n=n.merge;var l=function(d,c,e){this.init(d,c,e);this.collection="shapes"};l.attrsMap={width:"width",height:"height",zIndex:"zIndex"};n(!0,l.prototype,e,{type:"image",translate:e.translateShape,render:function(d){var c=this.attrsFromOptions(this.options),f=this.options;this.graphic=this.annotation.chart.renderer.image(f.src,
0,-9E9,f.width,f.height).attr(c).add(d);this.graphic.width=f.width;this.graphic.height=f.height;e.render.call(this)},redraw:function(d){var c=this.anchor(this.points[0]);if(c=f.prototype.position.call(this,c))this.graphic[d?"animate":"attr"]({x:c.x,y:c.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!c;e.redraw.call(this,d)}});return l});p(f,"annotations/annotations.src.js",[f["parts/Chart.js"],f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/ControllableRect.js"],
f["annotations/controllable/ControllableCircle.js"],f["annotations/controllable/ControllablePath.js"],f["annotations/controllable/ControllableImage.js"],f["annotations/controllable/ControllableLabel.js"],f["annotations/ControlPoint.js"],f["annotations/eventEmitterMixin.js"],f["parts/Globals.js"],f["annotations/MockPoint.js"],f["parts/Pointer.js"],f["parts/Utilities.js"]],function(f,e,n,l,d,c,m,p,b,k,u,q,h){f=f.prototype;var a=h.addEvent,g=h.defined,v=h.destroyObjectProperties,r=h.erase,B=h.extend,
t=h.find,w=h.fireEvent,x=h.merge,A=h.pick,E=h.splat;h=h.wrap;var z=function(){function a(a,b){this.annotation=void 0;this.coll="annotations";this.shapesGroup=this.labelsGroup=this.labelCollector=this.group=this.graphic=this.collection=void 0;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=x(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=
b.shapes;this.init(a,this.options)}a.prototype.init=function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.setLabelCollector()};a.prototype.getLabelsAndShapesOptions=function(a,b){var c={};["labels","shapes"].forEach(function(g){a[g]&&(c[g]=E(b[g]).map(function(b,c){return x(a[g][c],b)}))});return c};a.prototype.addShapes=function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);x(!0,this.options.shapes[b],a.options)},this)};a.prototype.addLabels=
function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);x(!0,this.options.labels[b],a.options)},this)};a.prototype.addClipPaths=function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))};a.prototype.setClipAxes=function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,g){return[a[g&&g.point&&g.point.xAxis]||c[0],b[g&&g.point&&g.point.yAxis]||
c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]};a.prototype.getClipBox=function(){if(this.clipXAxis&&this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}};a.prototype.setLabelCollector=function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)};a.prototype.setOptions=function(a){this.options=x(this.defaultOptions,
a)};a.prototype.redraw=function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);e.redraw.call(this,a)};a.prototype.redrawItems=function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)};a.prototype.renderItems=function(a){for(var b=a.length;b--;)this.renderItem(a[b])};a.prototype.render=function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,
visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();e.render.call(this)};a.prototype.setVisibility=function(a){var b=this.options;a=A(a,!b.visible);this.graphic.attr("visibility",
a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a};a.prototype.setControlPointsVisibility=function(a){var b=function(b){b.setControlPointsVisibility(a)};e.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)};a.prototype.destroy=function(){var a=this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;r(a.labelCollectors,this.labelCollector);b.destroy.call(this);e.destroy.call(this);
v(this,a)};a.prototype.remove=function(){return this.chart.removeAnnotation(this)};a.prototype.update=function(a,b){var c=this.chart,g=this.getLabelsAndShapesOptions(this.userOptions,a),d=c.annotations.indexOf(this);a=x(!0,this.userOptions,a);a.labels=g.labels;a.shapes=g.shapes;this.destroy();this.constructor(c,a);c.options.annotations[d]=a;this.isUpdating=!0;A(b,!0)&&c.redraw();w(this,"afterUpdate");this.isUpdating=!1};a.prototype.initShape=function(b,c){b=x(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},
b);c=new a.shapesMap[b.type](this,b,c);c.itemType="shape";this.shapes.push(c);return c};a.prototype.initLabel=function(a,b){a=x(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new m(this,a,b);b.itemType="label";this.labels.push(b);return b};a.prototype.redrawItem=function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(A(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)};a.prototype.adjustVisibility=
function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()};a.prototype.destroyItem=function(a){r(this[a.itemType+"s"],a);a.destroy()};a.prototype.renderItem=function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)};a.ControlPoint=p;a.MockPoint=u;a.shapesMap={rect:n,circle:l,path:d,image:c};a.types={};return a}();x(!0,z.prototype,e,b,x(z.prototype,{nonDOMEvents:["add","afterUpdate",
"drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return g(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",
r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6}}));k.extendAnnotation=function(a,b,c,g){b=b||z;x(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=x(a.prototype.defaultOptions,g||{})};B(f,{initAnnotation:function(a){a=new (z.types[a.type]||z)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);
A(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:t(b,function(b){return b.options.id===a});c&&(w(c,"remove"),r(this.options.annotations,c.options),r(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});f.collectionsWithUpdate.push("annotations");f.collectionsWithInit.annotations=[f.addAnnotation];f.callbacks.push(function(b){b.annotations=[];b.options.annotations||
(b.options.annotations=[]);b.plotBoxClip=this.renderer.clipRect(this.plotBox);b.controlPointsGroup=b.renderer.g("control-points").attr({zIndex:99}).clip(b.plotBoxClip).add();b.options.annotations.forEach(function(a,c){a=b.initAnnotation(a);b.options.annotations[c]=a.options});b.drawAnnotations();a(b,"redraw",b.drawAnnotations);a(b,"destroy",function(){b.plotBoxClip.destroy();b.controlPointsGroup.destroy()})});h(q.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,
Array.prototype.slice.call(arguments,1))});return k.Annotation=z});p(f,"mixins/navigation.js",[],function(){return{initUpdate:function(f){f.navigation||(f.navigation={updates:[],update:function(e,f){this.updates.forEach(function(l){l.update.call(l.context,e,f)})}})},addUpdate:function(f,e){e.navigation||this.initUpdate(e);e.navigation.updates.push({update:f,context:e})}}});p(f,"annotations/navigationBindings.js",[f["annotations/annotations.src.js"],f["mixins/navigation.js"],f["parts/Globals.js"],
f["parts/Utilities.js"]],function(f,e,n,l){function d(c){var g=c.prototype.defaultOptions.events&&c.prototype.defaultOptions.events.click;a(!0,c.prototype.defaultOptions.events,{click:function(a){var c=this,d=c.chart.navigationBindings,e=d.activeAnnotation;g&&g.click.call(c,a);e!==c?(d.deselectAnnotation(),d.activeAnnotation=c,c.setControlPointsVisibility(!0),b(d,"showPopup",{annotation:c,formType:"annotation-toolbar",options:d.annotationToFields(c),onSubmit:function(a){var b={};"remove"===a.actionType?
(d.activeAnnotation=!1,d.chart.removeAnnotation(c)):(d.fieldsToOptions(a.fields,b),d.deselectAnnotation(),a=b.typeOptions,"measure"===c.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),c.update(b))}})):(d.deselectAnnotation(),b(d,"closePopup"));a.activeAnnotation=!0}})}var c=l.addEvent,m=l.attr,p=l.format,b=l.fireEvent,k=l.isArray,u=l.isFunction,y=l.isNumber,h=l.isObject,a=l.merge,g=l.objectEach,v=l.pick;l=l.setOptions;var r=n.doc,
B=n.win,t=function(){function d(a,b){this.selectedButton=this.boundClassNames=void 0;this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=r.getElementsByClassName(this.options.bindingsClassName||"")}d.prototype.initEvents=function(){var a=this,b=a.chart,d=a.container,e=a.options;a.boundClassNames={};g(e.bindings||{},function(b){a.boundClassNames[b.className]=b});[].forEach.call(d,function(b){a.eventsToUnbind.push(c(b,"click",function(c){var g=a.getButtonEvents(b,c);g&&a.bindingsButtonClick(g.button,
g.events,c)}))});g(e.events||{},function(b,g){u(b)&&a.eventsToUnbind.push(c(a,g,b))});a.eventsToUnbind.push(c(b.container,"click",function(c){!b.cancelClick&&b.isInsidePlot(c.chartX-b.plotLeft,c.chartY-b.plotTop)&&a.bindingsChartClick(this,c)}));a.eventsToUnbind.push(c(b.container,q.isTouchDevice?"touchmove":"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))};d.prototype.initUpdate=function(){var a=this;e.addUpdate(function(b){a.update(b)},this.chart)};d.prototype.bindingsButtonClick=
function(a,c,g){var d=this.chart;this.selectedButtonElement&&(b(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&d.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=c;this.selectedButtonElement=a;b(this,"selectButton",{button:a});c.init&&c.init.call(this,a,g);(c.start||c.steps)&&d.renderer.boxWrapper.addClass("highcharts-draw-mode")};d.prototype.bindingsChartClick=
function(a,c){a=this.chart;var g=this.selectedButton;a=a.renderer.boxWrapper;var d;if(d=this.activeAnnotation&&!c.activeAnnotation&&c.target.parentNode){a:{d=c.target;var e=B.Element.prototype,f=e.matches||e.msMatchesSelector||e.webkitMatchesSelector,h=null;if(e.closest)h=e.closest.call(d,".highcharts-popup");else{do{if(f.call(d,".highcharts-popup"))break a;d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType)}d=h}d=!d}d&&(b(this,"closePopup"),this.deselectAnnotation());g&&g.start&&(this.nextEvent?
(this.nextEvent(c,this.currentUserDetails),this.steps&&(this.stepIndex++,g.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=g.steps[this.stepIndex]:(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),g.end&&g.end.call(this,c,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=g.start.call(this,c),g.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=g.steps[this.stepIndex]):
(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,g.end&&g.end.call(this,c,this.currentUserDetails))))};d.prototype.bindingsContainerMouseMove=function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)};d.prototype.fieldsToOptions=function(a,b){g(a,function(a,c){var g=parseFloat(a),d=c.split("."),e=b,f=d.length-1;!y(g)||a.match(/px/g)||c.match(/format/g)||(a=g);""!==a&&"undefined"!==a&&
d.forEach(function(b,c){var g=v(d[c+1],"");f===c?e[b]=a:(e[b]||(e[b]=g.match(/\d/g)?[]:{}),e=e[b])})});return b};d.prototype.deselectAnnotation=function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)};d.prototype.annotationToFields=function(a){function b(c,d,e,r){if(e&&-1===l.indexOf(d)&&(0<=(e.indexOf&&e.indexOf(d))||e[d]||!0===e))if(k(c))r[d]=[],c.forEach(function(a,c){h(a)?(r[d][c]={},g(a,function(a,g){b(a,g,f[d],r[d][c])})):b(a,0,f[d],
r[d])});else if(h(c)){var v={};k(r)?(r.push(v),v[d]={},v=v[d]):r[d]=v;g(c,function(a,c){b(a,c,0===d?e:f[d],v)})}else"format"===d?r[d]=[p(c,a.labels[0].points[0]).toString(),"text"]:k(r)?r.push([c,w(c)]):r[d]=[c,w(c)]}var c=a.options,e=d.annotationsEditable,f=e.nestedOptions,w=this.utils.getFieldType,r=v(c.type,c.shapes&&c.shapes[0]&&c.shapes[0].type,c.labels&&c.labels[0]&&c.labels[0].itemType,"label"),l=d.annotationsNonEditable[c.langKey]||[],t={langKey:c.langKey,type:r};g(c,function(a,d){"typeOptions"===
d?(t[d]={},g(c[d],function(a,c){b(a,c,f,t[d],!0)})):b(a,d,e[r],t)});return t};d.prototype.getClickedClassNames=function(a,b){var c=b.target;b=[];for(var g;c&&((g=m(c,"class"))&&(b=b.concat(g.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b};d.prototype.getButtonEvents=function(a,b){var c=this,g;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!g&&(g={events:c.boundClassNames[a[0]],button:a[1]})});return g};d.prototype.update=function(b){this.options=
a(!0,this.options,b);this.removeEvents();this.initEvents()};d.prototype.removeEvents=function(){this.eventsToUnbind.forEach(function(a){a()})};d.prototype.destroy=function(){this.removeEvents()};d.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill",
"strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:[]};d.annotationsNonEditable=
{rectangle:["crosshairX","crosshairY","label"]};return d}();t.prototype.utils={updateRectSize:function(a,b){var c=b.chart,g=b.options.typeOptions,d=c.pointer.getCoordinates(a);a=d.xAxis[0].value-g.point.x;g=g.point.y-d.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?g:a,height:c.inverted?a:g}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}};n.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&
a.navigation.bindings&&(this.navigationBindings=new t(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};c(n.Chart,"load",function(){this.initNavigationBindings()});c(n.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});c(t,"deselectButton",function(){this.selectedButtonElement=null});c(f,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});n.Annotation&&(d(f),g(f.types,
function(a){d(a)}));l({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",
padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(b){b=this.chart.pointer.getCoordinates(b);var c=this.chart.options.navigation;return this.chart.addAnnotation(a({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:b.xAxis[0].value,y:b.yAxis[0].value},r:5}]},c.annotationsOptions,
c.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,g=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var d=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(d?c-a.chartX:g-a.chartX,2)+Math.pow(d?g-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(b){var c=this.chart.pointer.getCoordinates(b);b=this.chart.options.navigation;var g=c.xAxis[0].value;
c=c.yAxis[0].value;return this.chart.addAnnotation(a({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:g,y:c},{xAxis:0,yAxis:0,x:g,y:c},{xAxis:0,yAxis:0,x:g,y:c},{xAxis:0,yAxis:0,x:g,y:c}]}]},b.annotationsOptions,b.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].points,g=this.chart.pointer.getCoordinates(a);a=g.xAxis[0].value;g=g.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=g;c[3].y=g;b.update({shapes:[{points:c}]})}]},
labelAnnotation:{className:"highcharts-label-annotation",start:function(b){b=this.chart.pointer.getCoordinates(b);var c=this.chart.options.navigation;return this.chart.addAnnotation(a({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:b.xAxis[0].value,y:b.yAxis[0].value},overflow:"none",crop:!0}]},c.annotationsOptions,c.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}});return t});p(f,"modules/stock-tools-bindings.js",
[f["parts/Globals.js"],f["annotations/navigationBindings.js"],f["parts/Utilities.js"]],function(f,e,n){var l=n.correctFloat,d=n.defined,c=n.extend,m=n.fireEvent,p=n.isNumber,b=n.merge,k=n.pick,u=n.setOptions,q=n.uniqueKey,h=e.prototype.utils;h.addFlagFromForm=function(a){return function(b){var c=this,g=c.chart,d=g.stockTools,e=h.getFieldType;b=h.attractToPoint(b,g);var f={type:"flags",onSeries:b.series.id,shape:a,data:[{x:b.x,y:b.y}],point:{events:{click:function(){var a=this,b=a.options;m(c,"showPopup",
{point:a,formType:"annotation-toolbar",options:{langKey:"flags",type:"flags",title:[b.title,e(b.title)],name:[b.name,e(b.name)]},onSubmit:function(b){"remove"===b.actionType?a.remove():a.update(c.fieldsToOptions(b.fields,{}))}})}}}};d&&d.guiEnabled||g.addSeries(f);m(c,"showPopup",{formType:"flag",options:{langKey:"flags",type:"flags",title:["A",e("A")],name:["Flag A",e("Flag A")]},onSubmit:function(a){c.fieldsToOptions(a.fields,f.data[0]);g.addSeries(f)}})}};h.manageIndicators=function(a){var b=this.chart,
c={linkedTo:a.linkedTo,type:a.type},d=["ad","cmf","mfi","vbp","vwap"],e="ad atr cci cmf macd mfi roc rsi ao aroon aroonoscillator trix apo dpo ppo natr williamsr stochastic slowstochastic linearRegression linearRegressionSlope linearRegressionIntercept linearRegressionAngle".split(" ");if("edit"===a.actionType)this.fieldsToOptions(a.fields,c),(a=b.get(a.seriesId))&&a.update(c,!1);else if("remove"===a.actionType){if(a=b.get(a.seriesId)){var f=a.yAxis;a.linkedSeries&&a.linkedSeries.forEach(function(a){a.remove(!1)});
a.remove(!1);0<=e.indexOf(a.type)&&(f.remove(!1),this.resizeYAxes())}}else c.id=q(),this.fieldsToOptions(a.fields,c),0<=e.indexOf(a.type)?(f=b.addAxis({id:q(),offset:0,opposite:!0,title:{text:""},tickPixelInterval:40,showLastLabel:!1,labels:{align:"left",y:-2}},!1,!1),c.yAxis=f.options.id,this.resizeYAxes()):c.yAxis=b.get(a.linkedTo).options.yAxis,0<=d.indexOf(a.type)&&(c.params.volumeSeriesID=b.series.filter(function(a){return"column"===a.options.type})[0].options.id),b.addSeries(c,!1);m(this,"deselectButton",
{button:this.selectedButtonElement});b.redraw()};h.updateHeight=function(a,b){b.update({typeOptions:{height:this.chart.pointer.getCoordinates(a).yAxis[0].value-b.options.typeOptions.points[1].y}})};h.attractToPoint=function(a,b){a=b.pointer.getCoordinates(a);var c=a.xAxis[0].value;a=a.yAxis[0].value;var g=Number.MAX_VALUE,d;b.series.forEach(function(a){a.points.forEach(function(a){a&&g>Math.abs(a.x-c)&&(g=Math.abs(a.x-c),d=a)})});return{x:d.x,y:d.y,below:a<d.y,series:d.series,xAxis:d.series.xAxis.index||
0,yAxis:d.series.yAxis.index||0}};h.isNotNavigatorYAxis=function(a){return"highcharts-navigator-yaxis"!==a.userOptions.className};h.updateNthPoint=function(a){return function(b,c){var g=c.options.typeOptions;b=this.chart.pointer.getCoordinates(b);var d=b.xAxis[0].value,e=b.yAxis[0].value;g.points.forEach(function(b,c){c>=a&&(b.x=d,b.y=e)});c.update({typeOptions:{points:g.points}})}};c(e.prototype,{getYAxisPositions:function(a,b,c){function g(a){return d(a)&&!p(a)&&a.match("%")}var e=0;a=a.map(function(a){var d=
g(a.options.height)?parseFloat(a.options.height)/100:a.height/b;a=g(a.options.top)?parseFloat(a.options.top)/100:l(a.top-a.chart.plotTop)/b;p(d)||(d=c/100);e=l(e+d);return{height:100*d,top:100*a}});a.allAxesHeight=e;return a},getYAxisResizers:function(a){var b=[];a.forEach(function(c,g){c=a[g+1];b[g]=c?{enabled:!0,controlledAxis:{next:[k(c.options.id,c.options.index)]}}:{enabled:!1}});return b},resizeYAxes:function(a){a=a||20;var b=this.chart,c=b.yAxis.filter(h.isNotNavigatorYAxis),d=c.length;b=this.getYAxisPositions(c,
b.plotHeight,a);var e=this.getYAxisResizers(c),f=b.allAxesHeight,k=a;1<f?(6>d?(b[0].height=l(b[0].height-k),b=this.recalculateYAxisPositions(b,k)):(a=100/d,b=this.recalculateYAxisPositions(b,a/(d-1),!0,-1)),b[d-1]={top:l(100-a),height:a}):(k=100*l(1-f),5>d?(b[0].height=l(b[0].height+k),b=this.recalculateYAxisPositions(b,k)):b=this.recalculateYAxisPositions(b,k/d,!0,1));b.forEach(function(a,b){c[b].update({height:a.height+"%",top:a.top+"%",resize:e[b]},!1)})},recalculateYAxisPositions:function(a,b,
c,d){a.forEach(function(g,e){e=a[e-1];g.top=e?l(e.height+e.top):0;c&&(g.height=l(g.height+d*b))});return a}});n={segment:{className:"highcharts-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"segment",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.segment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},
arrowSegment:{className:"highcharts-arrow-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"arrowSegment",type:"crookedLine",typeOptions:{line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.arrowSegment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},ray:{className:"highcharts-ray",start:function(a){a=
this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"ray",type:"crookedLine",typeOptions:{type:"ray",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.ray.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},arrowRay:{className:"highcharts-arrow-ray",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"arrowRay",
type:"infinityLine",typeOptions:{type:"ray",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.arrowRay.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},infinityLine:{className:"highcharts-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"infinityLine",type:"infinityLine",typeOptions:{type:"line",
points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.infinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},arrowInfinityLine:{className:"highcharts-arrow-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"arrowInfinityLine",type:"infinityLine",typeOptions:{type:"line",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,
y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.arrowInfinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1)]},horizontalLine:{className:"highcharts-horizontal-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"horizontalLine",type:"infinityLine",draggable:"y",typeOptions:{type:"horizontalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,
c.bindings.horizontalLine.annotationsOptions);this.chart.addAnnotation(a)}},verticalLine:{className:"highcharts-vertical-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"verticalLine",type:"infinityLine",draggable:"x",typeOptions:{type:"verticalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.verticalLine.annotationsOptions);this.chart.addAnnotation(a)}},crooked3:{className:"highcharts-crooked3",
start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"crooked3",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.crooked3.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2)]},crooked5:{className:"highcharts-crooked5",start:function(a){a=this.chart.pointer.getCoordinates(a);
var c=this.chart.options.navigation;a=b({langKey:"crookedLine",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.crooked5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2),h.updateNthPoint(3),h.updateNthPoint(4)]},elliott3:{className:"highcharts-elliott3",
start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"elliott3",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.elliott3.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2),
h.updateNthPoint(3)]},elliott5:{className:"highcharts-elliott5",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"elliott5",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},
c.annotationsOptions,c.bindings.elliott5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2),h.updateNthPoint(3),h.updateNthPoint(4),h.updateNthPoint(5)]},measureX:{className:"highcharts-measure-x",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"measure",type:"measure",typeOptions:{selectType:"x",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{strokeWidth:1,stroke:"#000000"},
crosshairY:{enabled:!1,strokeWidth:0,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.measureX.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateRectSize]},measureY:{className:"highcharts-measure-y",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"measure",type:"measure",typeOptions:{selectType:"y",point:{x:a.xAxis[0].value,
y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{enabled:!1,strokeWidth:0,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.measureY.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateRectSize]},measureXY:{className:"highcharts-measure-xy",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"measure",
type:"measure",typeOptions:{selectType:"xy",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},background:{width:0,height:0,strokeWidth:10},crosshairX:{strokeWidth:1,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"}},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.measureXY.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateRectSize]},fibonacci:{className:"highcharts-fibonacci",start:function(a){a=this.chart.pointer.getCoordinates(a);
var c=this.chart.options.navigation;a=b({langKey:"fibonacci",type:"fibonacci",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},c.annotationsOptions,c.bindings.fibonacci.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateHeight]},parallelChannel:{className:"highcharts-parallel-channel",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;
a=b({langKey:"parallelChannel",type:"tunnel",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},c.annotationsOptions,c.bindings.parallelChannel.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateHeight]},pitchfork:{className:"highcharts-pitchfork",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation;a=b({langKey:"pitchfork",type:"pitchfork",typeOptions:{points:[{x:a.xAxis[0].value,
y:a.yAxis[0].value,controlPoint:{style:{fill:"red"}}},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}],innerBackground:{fill:"rgba(100, 170, 255, 0.8)"}},shapeOptions:{strokeWidth:2}},c.annotationsOptions,c.bindings.pitchfork.annotationsOptions);return this.chart.addAnnotation(a)},steps:[h.updateNthPoint(1),h.updateNthPoint(2)]},verticalCounter:{className:"highcharts-vertical-counter",start:function(a){a=h.attractToPoint(a,this.chart);var c=this.chart.options.navigation,
e=d(this.verticalCounter)?this.verticalCounter:0;a=b({langKey:"verticalCounter",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,text:e.toString()}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},c.annotationsOptions,c.bindings.verticalCounter.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalLabel:{className:"highcharts-vertical-label",
start:function(a){a=h.attractToPoint(a,this.chart);var c=this.chart.options.navigation;a=b({langKey:"verticalLabel",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},c.annotationsOptions,c.bindings.verticalLabel.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalArrow:{className:"highcharts-vertical-arrow",
start:function(a){a=h.attractToPoint(a,this.chart);var c=this.chart.options.navigation;a=b({langKey:"verticalArrow",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,format:" "},connector:{fill:"none",stroke:a.below?"red":"green"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},c.annotationsOptions,c.bindings.verticalArrow.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},flagCirclepin:{className:"highcharts-flag-circlepin",
start:h.addFlagFromForm("circlepin")},flagDiamondpin:{className:"highcharts-flag-diamondpin",start:h.addFlagFromForm("flag")},flagSquarepin:{className:"highcharts-flag-squarepin",start:h.addFlagFromForm("squarepin")},flagSimplepin:{className:"highcharts-flag-simplepin",start:h.addFlagFromForm("nopin")},zoomX:{className:"highcharts-zoom-x",init:function(a){this.chart.update({chart:{zoomType:"x"}});m(this,"deselectButton",{button:a})}},zoomY:{className:"highcharts-zoom-y",init:function(a){this.chart.update({chart:{zoomType:"y"}});
m(this,"deselectButton",{button:a})}},zoomXY:{className:"highcharts-zoom-xy",init:function(a){this.chart.update({chart:{zoomType:"xy"}});m(this,"deselectButton",{button:a})}},seriesTypeLine:{className:"highcharts-series-type-line",init:function(a){this.chart.series[0].update({type:"line",useOhlcData:!0});m(this,"deselectButton",{button:a})}},seriesTypeOhlc:{className:"highcharts-series-type-ohlc",init:function(a){this.chart.series[0].update({type:"ohlc"});m(this,"deselectButton",{button:a})}},seriesTypeCandlestick:{className:"highcharts-series-type-candlestick",
init:function(a){this.chart.series[0].update({type:"candlestick"});m(this,"deselectButton",{button:a})}},fullScreen:{className:"highcharts-full-screen",init:function(a){this.chart.fullscreen.toggle();m(this,"deselectButton",{button:a})}},currentPriceIndicator:{className:"highcharts-current-price-indicator",init:function(a){var c=this.chart,b=c.series[0],d=b.options,e=d.lastVisiblePrice&&d.lastVisiblePrice.enabled;d=d.lastPrice&&d.lastPrice.enabled;c=c.stockTools;var f=c.getIconsURL();c&&c.guiEnabled&&
(a.firstChild.style["background-image"]=d?'url("'+f+'current-price-show.svg")':'url("'+f+'current-price-hide.svg")');b.update({lastPrice:{enabled:!d,color:"red"},lastVisiblePrice:{enabled:!e,label:{enabled:!0}}});m(this,"deselectButton",{button:a})}},indicators:{className:"highcharts-indicators",init:function(){var a=this;m(a,"showPopup",{formType:"indicators",options:{},onSubmit:function(c){a.utils.manageIndicators.call(a,c)}})}},toggleAnnotations:{className:"highcharts-toggle-annotations",init:function(a){var c=
this.chart,b=c.stockTools,d=b.getIconsURL();this.toggledAnnotations=!this.toggledAnnotations;(c.annotations||[]).forEach(function(a){a.setVisibility(!this.toggledAnnotations)},this);b&&b.guiEnabled&&(a.firstChild.style["background-image"]=this.toggledAnnotations?'url("'+d+'annotations-hidden.svg")':'url("'+d+'annotations-visible.svg")');m(this,"deselectButton",{button:a})}},saveChart:{className:"highcharts-save-chart",init:function(a){var c=this.chart,b=[],d=[],e=[],k=[];c.annotations.forEach(function(a,
c){b[c]=a.userOptions});c.series.forEach(function(a){a.is("sma")?d.push(a.userOptions):"flags"===a.type&&e.push(a.userOptions)});c.yAxis.forEach(function(a){h.isNotNavigatorYAxis(a)&&k.push(a.options)});f.win.localStorage.setItem("highcharts-chart",JSON.stringify({annotations:b,indicators:d,flags:e,yAxes:k}));m(this,"deselectButton",{button:a})}}};u({navigation:{bindings:n}});e.prototype.utils=b(h,e.prototype.utils)});p(f,"modules/stock-tools-gui.js",[f["parts/Chart.js"],f["parts/Globals.js"],f["annotations/navigationBindings.js"],
f["parts/Utilities.js"]],function(f,e,n,l){var d=l.addEvent,c=l.createElement,m=l.css,p=l.extend,b=l.fireEvent,k=l.getStyle,u=l.isArray,q=l.merge,h=l.pick;l=l.setOptions;l({lang:{stockTools:{gui:{simpleShapes:"Simple shapes",lines:"Lines",crookedLines:"Crooked lines",measure:"Measure",advanced:"Advanced",toggleAnnotations:"Toggle annotations",verticalLabels:"Vertical labels",flags:"Flags",zoomChange:"Zoom change",typeChange:"Type change",saveChart:"Save chart",indicators:"Indicators",currentPriceIndicator:"Current Price Indicators",
zoomX:"Zoom X",zoomY:"Zoom Y",zoomXY:"Zooom XY",fullScreen:"Fullscreen",typeOHLC:"OHLC",typeLine:"Line",typeCandlestick:"Candlestick",circle:"Circle",label:"Label",rectangle:"Rectangle",flagCirclepin:"Flag circle",flagDiamondpin:"Flag diamond",flagSquarepin:"Flag square",flagSimplepin:"Flag simple",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",arrowLine:"Arrow line",horizontalLine:"Horizontal line",
verticalLine:"Vertical line",infinityLine:"Infinity line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel"}},navigation:{popup:{circle:"Circle",rectangle:"Rectangle",label:"Label",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",
arrowLine:"Arrow line",horizontalLine:"Horizontal line",verticalLine:"Vertical line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel",infinityLine:"Infinity line",measure:"Measure",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",flags:"Flags",addButton:"add",
saveButton:"save",editButton:"edit",removeButton:"remove",series:"Series",volume:"Volume",connector:"Connector",innerBackground:"Inner background",outerBackground:"Outer background",crosshairX:"Crosshair X",crosshairY:"Crosshair Y",tunnel:"Tunnel",background:"Background"}}},stockTools:{gui:{enabled:!0,className:"highcharts-bindings-wrapper",toolbarClassName:"stocktools-toolbar",buttons:"indicators separator simpleShapes lines crookedLines measure advanced toggleAnnotations separator verticalLabels flags separator zoomChange fullScreen typeChange separator currentPriceIndicator saveChart".split(" "),
definitions:{separator:{symbol:"separator.svg"},simpleShapes:{items:["label","circle","rectangle"],circle:{symbol:"circle.svg"},rectangle:{symbol:"rectangle.svg"},label:{symbol:"label.svg"}},flags:{items:["flagCirclepin","flagDiamondpin","flagSquarepin","flagSimplepin"],flagSimplepin:{symbol:"flag-basic.svg"},flagDiamondpin:{symbol:"flag-diamond.svg"},flagSquarepin:{symbol:"flag-trapeze.svg"},flagCirclepin:{symbol:"flag-elipse.svg"}},lines:{items:"segment arrowSegment ray arrowRay line arrowLine horizontalLine verticalLine".split(" "),
segment:{symbol:"segment.svg"},arrowSegment:{symbol:"arrow-segment.svg"},ray:{symbol:"ray.svg"},arrowRay:{symbol:"arrow-ray.svg"},line:{symbol:"line.svg"},arrowLine:{symbol:"arrow-line.svg"},verticalLine:{symbol:"vertical-line.svg"},horizontalLine:{symbol:"horizontal-line.svg"}},crookedLines:{items:["elliott3","elliott5","crooked3","crooked5"],crooked3:{symbol:"crooked-3.svg"},crooked5:{symbol:"crooked-5.svg"},elliott3:{symbol:"elliott-3.svg"},elliott5:{symbol:"elliott-5.svg"}},verticalLabels:{items:["verticalCounter",
"verticalLabel","verticalArrow"],verticalCounter:{symbol:"vertical-counter.svg"},verticalLabel:{symbol:"vertical-label.svg"},verticalArrow:{symbol:"vertical-arrow.svg"}},advanced:{items:["fibonacci","pitchfork","parallelChannel"],pitchfork:{symbol:"pitchfork.svg"},fibonacci:{symbol:"fibonacci.svg"},parallelChannel:{symbol:"parallel-channel.svg"}},measure:{items:["measureXY","measureX","measureY"],measureX:{symbol:"measure-x.svg"},measureY:{symbol:"measure-y.svg"},measureXY:{symbol:"measure-xy.svg"}},
toggleAnnotations:{symbol:"annotations-visible.svg"},currentPriceIndicator:{symbol:"current-price-show.svg"},indicators:{symbol:"indicators.svg"},zoomChange:{items:["zoomX","zoomY","zoomXY"],zoomX:{symbol:"zoom-x.svg"},zoomY:{symbol:"zoom-y.svg"},zoomXY:{symbol:"zoom-xy.svg"}},typeChange:{items:["typeOHLC","typeLine","typeCandlestick"],typeOHLC:{symbol:"series-ohlc.svg"},typeLine:{symbol:"series-line.svg"},typeCandlestick:{symbol:"series-candlestick.svg"}},fullScreen:{symbol:"fullscreen.svg"},saveChart:{symbol:"save-chart.svg"}}}}});
d(e.Chart,"afterGetContainer",function(){this.setStockTools()});d(e.Chart,"getMargins",function(){var a=this.stockTools&&this.stockTools.listWrapper;(a=a&&(a.startWidth+k(a,"padding-left")+k(a,"padding-right")||a.offsetWidth))&&a<this.plotWidth&&(this.plotLeft+=a)});d(e.Chart,"destroy",function(){this.stockTools&&this.stockTools.destroy()});d(e.Chart,"redraw",function(){this.stockTools&&this.stockTools.guiEnabled&&this.stockTools.redraw()});l=function(){function a(a,c,d){this.wrapper=this.toolbar=
this.submenu=this.showhideBtn=this.listWrapper=this.arrowWrapper=this.arrowUp=this.arrowDown=void 0;this.chart=d;this.options=a;this.lang=c;this.iconsURL=this.getIconsURL();this.guiEnabled=a.enabled;this.visible=h(a.visible,!0);this.placed=h(a.placed,!1);this.eventsToUnbind=[];this.guiEnabled&&(this.createHTML(),this.init(),this.showHideNavigatorion());b(this,"afterInit")}a.prototype.init=function(){var a=this,c=this.lang,b=this.options,e=this.toolbar,f=a.addSubmenu,h=b.definitions,k=e.childNodes,
l;b.buttons.forEach(function(b){l=a.addButton(e,h,b,c);a.eventsToUnbind.push(d(l.buttonWrapper,"click",function(){a.eraseActiveButtons(k,l.buttonWrapper)}));u(h[b].items)&&f.call(a,l,h[b])})};a.prototype.addSubmenu=function(a,b){var e=this,g=a.submenuArrow,f=a.buttonWrapper,h=k(f,"width"),l=this.wrapper,n=this.listWrapper,v=this.toolbar.childNodes,p=0,q;this.submenu=q=c("ul",{className:"highcharts-submenu-wrapper"},null,f);this.addSubmenuItems(f,b);e.eventsToUnbind.push(d(g,"click",function(a){a.stopPropagation();
e.eraseActiveButtons(v,f);0<=f.className.indexOf("highcharts-current")?(n.style.width=n.startWidth+"px",f.classList.remove("highcharts-current"),q.style.display="none"):(q.style.display="block",p=q.offsetHeight-f.offsetHeight-3,q.offsetHeight+f.offsetTop>l.offsetHeight&&f.offsetTop>p||(p=0),m(q,{top:-p+"px",left:h+3+"px"}),f.className+=" highcharts-current",n.startWidth=l.offsetWidth,n.style.width=n.startWidth+k(n,"padding-left")+q.offsetWidth+3+"px")}))};a.prototype.addSubmenuItems=function(a,c){var b=
this,e=this.submenu,g=this.lang,f=this.listWrapper,h;c.items.forEach(function(k){h=b.addButton(e,c,k,g);b.eventsToUnbind.push(d(h.mainButton,"click",function(){b.switchSymbol(this,a,!0);f.style.width=f.startWidth+"px";e.style.display="none"}))});var k=e.querySelectorAll("li > .highcharts-menu-item-btn")[0];b.switchSymbol(k,!1)};a.prototype.eraseActiveButtons=function(a,c,b){[].forEach.call(a,function(a){a!==c&&(a.classList.remove("highcharts-current"),a.classList.remove("highcharts-active"),b=a.querySelectorAll(".highcharts-submenu-wrapper"),
0<b.length&&(b[0].style.display="none"))})};a.prototype.addButton=function(b,d,e,f){void 0===f&&(f={});d=d[e];var g=d.items,k=d.className||"";e=c("li",{className:h(a.prototype.classMapping[e],"")+" "+k,title:f[e]||e},null,b);b=c("span",{className:"highcharts-menu-item-btn"},null,e);if(g&&g.length){var l=c("span",{className:"highcharts-submenu-item-arrow highcharts-arrow-right"},null,e);l.style["background-image"]="url("+this.iconsURL+"arrow-bottom.svg)"}else b.style["background-image"]="url("+this.iconsURL+
d.symbol+")";return{buttonWrapper:e,mainButton:b,submenuArrow:l}};a.prototype.addNavigation=function(){var a=this.wrapper;this.arrowWrapper=c("div",{className:"highcharts-arrow-wrapper"});this.arrowUp=c("div",{className:"highcharts-arrow-up"},null,this.arrowWrapper);this.arrowUp.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";this.arrowDown=c("div",{className:"highcharts-arrow-down"},null,this.arrowWrapper);this.arrowDown.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";
a.insertBefore(this.arrowWrapper,a.childNodes[0]);this.scrollButtons()};a.prototype.scrollButtons=function(){var a=0,c=this.wrapper,b=this.toolbar,e=.1*c.offsetHeight;this.eventsToUnbind.push(d(this.arrowUp,"click",function(){0<a&&(a-=e,b.style["margin-top"]=-a+"px")}));this.eventsToUnbind.push(d(this.arrowDown,"click",function(){c.offsetHeight+a<=b.offsetHeight+e&&(a+=e,b.style["margin-top"]=-a+"px")}))};a.prototype.createHTML=function(){var a=this.chart,b=this.options,d=a.container;a=a.options.navigation;
this.wrapper=a=c("div",{className:"highcharts-stocktools-wrapper "+b.className+" "+(a&&a.bindingsClassName)});d.parentNode.insertBefore(a,d);this.toolbar=d=c("ul",{className:"highcharts-stocktools-toolbar "+b.toolbarClassName});this.listWrapper=b=c("div",{className:"highcharts-menu-wrapper"});a.insertBefore(b,a.childNodes[0]);b.insertBefore(d,b.childNodes[0]);this.showHideToolbar();this.addNavigation()};a.prototype.showHideNavigatorion=function(){this.visible&&this.toolbar.offsetHeight>this.wrapper.offsetHeight-
50?this.arrowWrapper.style.display="block":(this.toolbar.style.marginTop="0px",this.arrowWrapper.style.display="none")};a.prototype.showHideToolbar=function(){var a=this.chart,b=this.wrapper,e=this.listWrapper,f=this.submenu,h=this.visible,l;this.showhideBtn=l=c("div",{className:"highcharts-toggle-toolbar highcharts-arrow-left"},null,b);l.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";h?(b.style.height="100%",l.style.top=k(e,"padding-top")+"px",l.style.left=b.offsetWidth+k(e,"padding-left")+
"px"):(f&&(f.style.display="none"),l.style.left="0px",this.visible=h=!1,e.classList.add("highcharts-hide"),l.classList.toggle("highcharts-arrow-right"),b.style.height=l.offsetHeight+"px");this.eventsToUnbind.push(d(l,"click",function(){a.update({stockTools:{gui:{visible:!h,placed:!0}}})}))};a.prototype.switchSymbol=function(a,b){var c=a.parentNode,d=c.classList.value;c=c.parentNode.parentNode;c.className="";d&&c.classList.add(d.trim());c.querySelectorAll(".highcharts-menu-item-btn")[0].style["background-image"]=
a.style["background-image"];b&&this.selectButton(c)};a.prototype.selectButton=function(a){0<=a.className.indexOf("highcharts-active")?a.classList.remove("highcharts-active"):a.classList.add("highcharts-active")};a.prototype.unselectAllButtons=function(a){var b=a.parentNode.querySelectorAll(".highcharts-active");[].forEach.call(b,function(b){b!==a&&b.classList.remove("highcharts-active")})};a.prototype.update=function(a){q(!0,this.chart.options.stockTools,a);this.destroy();this.chart.setStockTools(a);
this.chart.navigationBindings&&this.chart.navigationBindings.update()};a.prototype.destroy=function(){var a=this.wrapper,b=a&&a.parentNode;this.eventsToUnbind.forEach(function(a){a()});b&&b.removeChild(a);this.chart.isDirtyBox=!0;this.chart.redraw()};a.prototype.redraw=function(){this.showHideNavigatorion()};a.prototype.getIconsURL=function(){return this.chart.options.navigation.iconsURL||this.options.iconsURL||"https://code.highcharts.com/8.1.1/gfx/stock-icons/"};return a}();l.prototype.classMapping=
{circle:"highcharts-circle-annotation",rectangle:"highcharts-rectangle-annotation",label:"highcharts-label-annotation",segment:"highcharts-segment",arrowSegment:"highcharts-arrow-segment",ray:"highcharts-ray",arrowRay:"highcharts-arrow-ray",line:"highcharts-infinity-line",arrowLine:"highcharts-arrow-infinity-line",verticalLine:"highcharts-vertical-line",horizontalLine:"highcharts-horizontal-line",crooked3:"highcharts-crooked3",crooked5:"highcharts-crooked5",elliott3:"highcharts-elliott3",elliott5:"highcharts-elliott5",
pitchfork:"highcharts-pitchfork",fibonacci:"highcharts-fibonacci",parallelChannel:"highcharts-parallel-channel",measureX:"highcharts-measure-x",measureY:"highcharts-measure-y",measureXY:"highcharts-measure-xy",verticalCounter:"highcharts-vertical-counter",verticalLabel:"highcharts-vertical-label",verticalArrow:"highcharts-vertical-arrow",currentPriceIndicator:"highcharts-current-price-indicator",indicators:"highcharts-indicators",flagCirclepin:"highcharts-flag-circlepin",flagDiamondpin:"highcharts-flag-diamondpin",
flagSquarepin:"highcharts-flag-squarepin",flagSimplepin:"highcharts-flag-simplepin",zoomX:"highcharts-zoom-x",zoomY:"highcharts-zoom-y",zoomXY:"highcharts-zoom-xy",typeLine:"highcharts-series-type-line",typeOHLC:"highcharts-series-type-ohlc",typeCandlestick:"highcharts-series-type-candlestick",fullScreen:"highcharts-full-screen",toggleAnnotations:"highcharts-toggle-annotations",saveChart:"highcharts-save-chart",separator:"highcharts-separator"};p(f.prototype,{setStockTools:function(a){var b=this.options,
c=b.lang;a=q(b.stockTools&&b.stockTools.gui,a&&a.gui);this.stockTools=new e.Toolbar(a,c.stockTools&&c.stockTools.gui,this);this.stockTools.guiEnabled&&(this.isDirtyBox=!0)}});d(n,"selectButton",function(a){var b=a.button,c=this.chart.stockTools;c&&c.guiEnabled&&(c.unselectAllButtons(a.button),0<=b.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(b=b.parentNode.parentNode),c.selectButton(b))});d(n,"deselectButton",function(a){a=a.button;var b=this.chart.stockTools;b&&b.guiEnabled&&(0<=
a.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(a=a.parentNode.parentNode),b.selectButton(a))});e.Toolbar=l;return e.Toolbar});p(f,"masters/modules/stock-tools.src.js",[],function(){})});
//# sourceMappingURL=stock-tools.js.map